import type { Catalog, SupportedLocale } from './locale.js';

// Mounted dashboard localization for the remaining F-89 surfaces. Provider
// and authored values remain data; only operator-facing UI copy is catalogued.
const en: Catalog = {
  'dashboard.grok.statusNotChecked': 'Connection not checked',
  'dashboard.grok.checkSaved': 'Check saved Grok login',
  'dashboard.grok.connectAccount': 'Connect Grok account',
  'dashboard.grok.cancelLogin': 'Cancel Grok login',
  'dashboard.grok.loginCompleted': 'Grok login completed. Generation access has not yet been verified.',
  'dashboard.grok.credentialFound': 'Grok credential file found. Provider access has not yet been verified.',
  'dashboard.grok.noCredential': 'No saved Grok credential file found',
  'dashboard.grok.checkUnconfirmed': 'Connection not confirmed. Check status before trying again.',
  'dashboard.grok.cancelRequested': 'Cancellation requested. Check status before trying again.',
  'dashboard.grok.generationNote': 'This check detects saved sign-in credentials; it does not test live image or video access. A credential-file result is not a login failure. Reconnecting does not verify generation access. Generation also requires an available worker and workspace safety settings that permit it.',
  'dashboard.r2.title': 'Private R2 video storage',
  'dashboard.r2.description': 'Keep Grok ZDR enabled. Enter bucket-scoped R2 S3 credentials here, never in chat. Saving does not generate media or change bucket permissions.',
  'dashboard.r2.endpoint': 'S3 endpoint', 'dashboard.r2.bucket': 'Bucket', 'dashboard.r2.accessKey': 'Access key ID', 'dashboard.r2.secretKey': 'Secret access key',
  'dashboard.r2.restriction': 'These credentials are restricted to Object Read & Write for this private bucket.', 'dashboard.r2.save': 'Save R2 credentials', 'dashboard.r2.checkStatus': 'Check saved status', 'dashboard.r2.verify': 'Verify bucket access', 'dashboard.r2.remove': 'Remove saved R2 credentials',
  'dashboard.r2.statusNotChecked': 'Storage not checked', 'dashboard.r2.verified': 'R2 bucket read/write verified; the temporary probe object was removed.', 'dashboard.r2.saved': 'R2 configuration saved. Bucket access and video generation have not been verified.', 'dashboard.r2.notConfigured': 'No R2 configuration saved for this workspace and operator.', 'dashboard.r2.operationFailed': 'Storage operation not confirmed. Check saved status before trying again.', 'dashboard.r2.removalNote': 'Removal prevents future requests from loading these credentials. It does not revoke the Cloudflare keys, delete stored media, or cancel a running generation.', 'dashboard.r2.endpointPlaceholder': 'https://ACCOUNT_ID.r2.cloudflarestorage.com',
  'dashboard.performance.patternsUnavailable': 'Pattern analysis unavailable.', 'dashboard.performance.patternsNotEnough': 'Not enough verified examples yet. Each pattern needs at least {count} labeled exemplars.', 'dashboard.performance.scheduledTimeUnknown': 'Scheduled time unknown', 'dashboard.performance.unknownScheduledTime': 'Unknown scheduled time', 'dashboard.performance.publicationTimeUnavailable': 'Publication time unavailable', 'dashboard.performance.questionMark': 'contains a question mark', 'dashboard.performance.noQuestionMark': 'no question mark', 'dashboard.performance.recordedMedia': 'Recorded media', 'dashboard.performance.unknownFormat': 'unknown format', 'dashboard.performance.published': 'published', 'dashboard.performance.tosVerdict': 'ToS verdict at publication', 'dashboard.performance.labeledExemplars': '{count} labeled exemplars', 'dashboard.performance.meanRelativeScore': 'Mean relative engagement score: {score}', 'dashboard.performance.showingTopGroups': 'Showing the 20 highest-scoring groups.', 'dashboard.performance.exploratoryDisclaimer': 'Exploratory observations, not recommendations or statistical significance. Scores are engagement z-scores calculated when each exemplar was labeled; zero represents its then-current comparison average. These are retained labeled examples, not all posts, and scores may use different historical comparison windows. No conversion lift or causal effect is inferred.', 'dashboard.performance.hook': 'hook', 'dashboard.performance.format': 'format', 'dashboard.performance.timing': 'timing', 'dashboard.performance.title': 'What’s working: observed patterns', 'dashboard.performance.description': 'Grouped verified exemplars for this talent only. Caption length and question marks describe the recorded caption; time is its scheduled UTC bucket, not necessarily actual publication time.', 'dashboard.performance.ariaLabel': 'Observed performance patterns',
  'dashboard.newModel.addTalent': 'Add talent', 'dashboard.newModel.newProfile': 'New profile', 'dashboard.newModel.welcomeTalent': 'Welcome new talent', 'dashboard.newModel.close': 'Close', 'dashboard.newModel.creatorName': 'Creator name', 'dashboard.newModel.handle': 'Handle', 'dashboard.newModel.handlePlaceholder': 'luna.vex', 'dashboard.newModel.brandNote': 'Brand note', 'dashboard.newModel.optional': 'optional', 'dashboard.newModel.createProfile': 'Create profile', 'dashboard.newModel.creatingProfile': 'Creating profile...', 'dashboard.newModel.createFailed': 'Create failed', 'dashboard.newModel.creationUnconfirmed': 'Creation could not be confirmed. Retry without changing the form to safely check the same request.',
  'automation.thresholdMode': 'Threshold mode', 'automation.fixedThreshold': 'Fixed threshold', 'automation.learnedP90': 'Learned p90', 'automation.learnedP90Summary': 'learned p90 (minimum {count} samples)', 'automation.learnedP90Description': 'Uses the 90th percentile of verified provider metrics for this model and platform; it stays inactive until the minimum sample count is met.', 'automation.minimumSamples': 'Minimum samples',
  'dashboard.tabs.talentWorkspace': 'Talent workspace', 'dashboard.tabs.relayDelivery': 'Relay delivery', 'dashboard.tabs.agentAccess': 'Agent access', 'dashboard.tabs.cascadeSchedules': 'Cascade schedules', 'dashboard.tabs.automationRules': 'Automation rules', 'dashboard.tabs.variantExperiments': 'Variant experiments', 'dashboard.tabs.teamShifts': 'Team & shifts', 'dashboard.tabs.chatterRoleplay': 'Chatter & roleplay',
  'dashboard.signOutFailed': 'Sign-out could not be confirmed. Your session may still be active. Please try again.',
};

const es: Catalog = {
  ...en,
  'dashboard.performance.title': 'Qué funciona: patrones observados', 'dashboard.performance.description': 'Ejemplos verificados agrupados solo para este talento. La longitud y los signos de interrogación describen el texto registrado; la hora es su bloque UTC programado, no necesariamente la publicación real.', 'dashboard.performance.ariaLabel': 'Patrones de rendimiento observados',
  'dashboard.grok.statusNotChecked': 'Conexión no comprobada', 'dashboard.grok.checkSaved': 'Comprobar inicio de sesión de Grok guardado', 'dashboard.grok.connectAccount': 'Conectar cuenta de Grok', 'dashboard.grok.cancelLogin': 'Cancelar inicio de sesión de Grok', 'dashboard.grok.loginCompleted': 'Inicio de sesión de Grok completado. El acceso a la generación aún no se ha verificado.', 'dashboard.grok.credentialFound': 'Archivo de credenciales de Grok encontrado. El acceso al proveedor aún no se ha verificado.', 'dashboard.grok.noCredential': 'No se encontró un archivo de credenciales de Grok guardado', 'dashboard.grok.checkUnconfirmed': 'Conexión no confirmada. Comprueba el estado antes de volver a intentarlo.', 'dashboard.grok.cancelRequested': 'Cancelación solicitada. Comprueba el estado antes de volver a intentarlo.', 'dashboard.grok.generationNote': 'Esta comprobación detecta credenciales de inicio guardadas; no prueba el acceso real a imágenes o vídeos. Un resultado de archivo de credenciales no indica un fallo de inicio de sesión. Volver a conectar no verifica el acceso a la generación. La generación también requiere un worker disponible y ajustes de seguridad del espacio de trabajo que la permitan.',
  'dashboard.r2.title': 'Almacenamiento privado de vídeo R2', 'dashboard.r2.description': 'Mantén Grok ZDR activado. Introduce aquí las credenciales S3 de R2 limitadas al bucket, nunca en el chat. Guardarlas no genera medios ni cambia los permisos del bucket.', 'dashboard.r2.endpoint': 'Endpoint S3', 'dashboard.r2.bucket': 'Bucket', 'dashboard.r2.accessKey': 'ID de clave de acceso', 'dashboard.r2.secretKey': 'Clave de acceso secreta', 'dashboard.r2.restriction': 'Estas credenciales están limitadas a lectura y escritura de objetos en este bucket privado.', 'dashboard.r2.save': 'Guardar credenciales de R2', 'dashboard.r2.checkStatus': 'Comprobar estado guardado', 'dashboard.r2.verify': 'Verificar acceso al bucket', 'dashboard.r2.remove': 'Eliminar credenciales de R2 guardadas', 'dashboard.r2.statusNotChecked': 'Almacenamiento no comprobado', 'dashboard.r2.verified': 'Lectura y escritura del bucket R2 verificadas; se eliminó el objeto de prueba temporal.', 'dashboard.r2.saved': 'Configuración de R2 guardada. El acceso al bucket y la generación de vídeo aún no se han verificado.', 'dashboard.r2.notConfigured': 'No hay configuración de R2 guardada para este espacio de trabajo y operador.', 'dashboard.r2.operationFailed': 'Operación de almacenamiento no confirmada. Comprueba el estado guardado antes de volver a intentarlo.', 'dashboard.r2.removalNote': 'La eliminación impide que futuras solicitudes carguen estas credenciales. No revoca las claves de Cloudflare, elimina medios guardados ni cancela una generación en curso.',
  'dashboard.performance.patternsUnavailable': 'El análisis de patrones no está disponible.', 'dashboard.performance.patternsNotEnough': 'Aún no hay suficientes ejemplos verificados. Cada patrón necesita al menos {count} ejemplos etiquetados.', 'dashboard.performance.scheduledTimeUnknown': 'Hora programada desconocida', 'dashboard.performance.unknownScheduledTime': 'Hora programada desconocida', 'dashboard.performance.publicationTimeUnavailable': 'Hora de publicación no disponible', 'dashboard.performance.questionMark': 'contiene un signo de interrogación', 'dashboard.performance.noQuestionMark': 'sin signo de interrogación', 'dashboard.performance.recordedMedia': 'Medio registrado', 'dashboard.performance.unknownFormat': 'formato desconocido', 'dashboard.performance.published': 'publicado', 'dashboard.performance.tosVerdict': 'Veredicto de ToS en la publicación', 'dashboard.performance.labeledExemplars': '{count} ejemplos etiquetados', 'dashboard.performance.meanRelativeScore': 'Puntuación relativa media de interacción: {score}', 'dashboard.performance.showingTopGroups': 'Se muestran los 20 grupos con mayor puntuación.', 'dashboard.performance.exploratoryDisclaimer': 'Observaciones exploratorias, no recomendaciones ni significancia estadística. Las puntuaciones son z de interacción calculadas al etiquetar cada ejemplo; cero representa su media de comparación en ese momento. Son ejemplos etiquetados conservados, no todas las publicaciones, y pueden usar ventanas históricas distintas. No se infiere aumento de conversión ni efecto causal.', 'dashboard.performance.hook': 'gancho', 'dashboard.performance.format': 'formato', 'dashboard.performance.timing': 'momento',
  'dashboard.newModel.addTalent': 'Añadir talento', 'dashboard.newModel.newProfile': 'Nuevo perfil', 'dashboard.newModel.welcomeTalent': 'Da la bienvenida al nuevo talento', 'dashboard.newModel.close': 'Cerrar', 'dashboard.newModel.creatorName': 'Nombre del creador', 'dashboard.newModel.handle': 'Usuario', 'dashboard.newModel.brandNote': 'Nota de marca', 'dashboard.newModel.optional': 'opcional', 'dashboard.newModel.createProfile': 'Crear perfil', 'dashboard.newModel.creatingProfile': 'Creando perfil...', 'dashboard.newModel.createFailed': 'No se pudo crear', 'dashboard.newModel.creationUnconfirmed': 'No se pudo confirmar la creación. Reintenta sin cambiar el formulario para comprobar de forma segura la misma solicitud.',
  'automation.thresholdMode': 'Modo de umbral', 'automation.fixedThreshold': 'Umbral fijo', 'automation.learnedP90': 'P90 aprendido', 'automation.learnedP90Summary': 'P90 aprendido (mínimo {count} muestras)', 'automation.learnedP90Description': 'Usa el percentil 90 de las métricas verificadas del proveedor para este modelo y plataforma; permanece inactivo hasta alcanzar el mínimo de muestras.', 'automation.minimumSamples': 'Muestras mínimas',
  'dashboard.tabs.talentWorkspace': 'Espacio de trabajo del talento', 'dashboard.tabs.relayDelivery': 'Entrega Relay', 'dashboard.tabs.agentAccess': 'Acceso de agentes', 'dashboard.tabs.cascadeSchedules': 'Programaciones en cascada', 'dashboard.tabs.automationRules': 'Reglas de automatización', 'dashboard.tabs.variantExperiments': 'Experimentos de variantes', 'dashboard.tabs.teamShifts': 'Equipo y turnos', 'dashboard.tabs.chatterRoleplay': 'Chatter y roleplay', 'dashboard.signOutFailed': 'No se pudo confirmar el cierre de sesión. Tu sesión podría seguir activa. Inténtalo de nuevo.',
};

const ja: Catalog = {
  ...en,
  'dashboard.performance.title': '効果があるもの: 観測されたパターン', 'dashboard.performance.description': 'このタレントだけの検証済み例をグループ化しています。キャプションの長さと疑問符は記録されたキャプションを示し、時刻は実際の公開時刻とは限らない予定UTC区分です。', 'dashboard.performance.ariaLabel': '観測されたパフォーマンスパターン',
  'dashboard.grok.statusNotChecked': '接続を確認していません', 'dashboard.grok.checkSaved': '保存済みのGrokログインを確認', 'dashboard.grok.connectAccount': 'Grokアカウントを接続', 'dashboard.grok.cancelLogin': 'Grokログインをキャンセル', 'dashboard.grok.loginCompleted': 'Grokログインが完了しました。生成アクセスはまだ確認されていません。', 'dashboard.grok.credentialFound': 'Grokの認証情報ファイルが見つかりました。プロバイダーアクセスはまだ確認されていません。', 'dashboard.grok.noCredential': '保存済みのGrok認証情報ファイルが見つかりません', 'dashboard.grok.checkUnconfirmed': '接続を確認できません。再試行する前に状態を確認してください。', 'dashboard.grok.cancelRequested': 'キャンセルを要求しました。再試行する前に状態を確認してください。', 'dashboard.grok.generationNote': 'この確認は保存済みのログイン認証情報を検出します。実際の画像・動画アクセスはテストしません。認証情報ファイルの結果はログイン失敗を意味しません。再接続しても生成アクセスは確認されません。生成には利用可能なワーカーと、生成を許可するワークスペース安全設定も必要です。',
  'dashboard.r2.title': 'プライベートR2動画ストレージ', 'dashboard.r2.description': 'Grok ZDRを有効にしてください。バケット限定のR2 S3認証情報をここに入力し、チャットには貼り付けないでください。保存してもメディア生成やバケット権限は変更されません。', 'dashboard.r2.endpoint': 'S3エンドポイント', 'dashboard.r2.bucket': 'バケット', 'dashboard.r2.accessKey': 'アクセスキーID', 'dashboard.r2.secretKey': 'シークレットアクセスキー', 'dashboard.r2.restriction': 'この認証情報はプライベートバケットのオブジェクト読み書きに限定されています。', 'dashboard.r2.save': 'R2認証情報を保存', 'dashboard.r2.checkStatus': '保存状態を確認', 'dashboard.r2.verify': 'バケットアクセスを確認', 'dashboard.r2.remove': '保存済みR2認証情報を削除', 'dashboard.r2.statusNotChecked': 'ストレージ未確認', 'dashboard.r2.verified': 'R2バケットの読み書きを確認しました。一時プローブオブジェクトは削除されました。', 'dashboard.r2.saved': 'R2設定を保存しました。バケットアクセスと動画生成はまだ確認されていません。', 'dashboard.r2.notConfigured': 'このワークスペースとオペレーターにはR2設定が保存されていません。', 'dashboard.r2.operationFailed': 'ストレージ操作を確認できません。再試行する前に保存状態を確認してください。', 'dashboard.r2.removalNote': '削除すると今後のリクエストでこの認証情報を読み込まなくなります。Cloudflareキーの失効、保存メディアの削除、実行中の生成のキャンセルは行いません。',
  'dashboard.performance.patternsUnavailable': 'パターン分析を利用できません。', 'dashboard.performance.patternsNotEnough': '検証済みの例がまだ足りません。各パターンには少なくとも{count}件のラベル付き例が必要です。', 'dashboard.performance.scheduledTimeUnknown': '予定時刻不明', 'dashboard.performance.unknownScheduledTime': '予定時刻不明', 'dashboard.performance.publicationTimeUnavailable': '公開時刻を利用できません', 'dashboard.performance.questionMark': '疑問符を含む', 'dashboard.performance.noQuestionMark': '疑問符なし', 'dashboard.performance.recordedMedia': '記録されたメディア', 'dashboard.performance.unknownFormat': '形式不明', 'dashboard.performance.published': '公開済み', 'dashboard.performance.tosVerdict': '公開時のToS判定', 'dashboard.performance.labeledExemplars': '{count}件のラベル付き例', 'dashboard.performance.meanRelativeScore': '平均相対エンゲージメントスコア: {score}', 'dashboard.performance.showingTopGroups': 'スコア上位20グループを表示しています。', 'dashboard.performance.exploratoryDisclaimer': '探索的な観測であり、推奨や統計的有意性ではありません。スコアは各例のラベル付け時に計算したエンゲージメントzスコアで、ゼロは当時の比較平均を表します。保持されたラベル付き例であり全投稿ではなく、異なる履歴比較期間を使う場合があります。コンバージョン向上や因果効果は推定しません。', 'dashboard.performance.hook': 'フック', 'dashboard.performance.format': '形式', 'dashboard.performance.timing': 'タイミング',
  'dashboard.newModel.addTalent': 'タレントを追加', 'dashboard.newModel.newProfile': '新しいプロフィール', 'dashboard.newModel.welcomeTalent': '新しいタレントを登録', 'dashboard.newModel.close': '閉じる', 'dashboard.newModel.creatorName': 'クリエイター名', 'dashboard.newModel.handle': 'ハンドル', 'dashboard.newModel.brandNote': 'ブランドメモ', 'dashboard.newModel.optional': '任意', 'dashboard.newModel.createProfile': 'プロフィールを作成', 'dashboard.newModel.creatingProfile': 'プロフィールを作成中...', 'dashboard.newModel.createFailed': '作成に失敗しました', 'dashboard.newModel.creationUnconfirmed': '作成を確認できません。フォームを変更せずに再試行して同じリクエストを安全に確認してください。',
  'automation.thresholdMode': 'しきい値モード', 'automation.fixedThreshold': '固定しきい値', 'automation.learnedP90': '学習済みP90', 'automation.learnedP90Summary': '学習済みP90（最小{count}サンプル）', 'automation.learnedP90Description': 'このモデルとプラットフォームの検証済みプロバイダーメトリクスの90パーセンタイルを使用します。最小サンプル数に達するまで無効です。', 'automation.minimumSamples': '最小サンプル数',
  'dashboard.tabs.talentWorkspace': 'タレントワークスペース', 'dashboard.tabs.relayDelivery': 'Relay配信', 'dashboard.tabs.agentAccess': 'エージェントアクセス', 'dashboard.tabs.cascadeSchedules': 'カスケードスケジュール', 'dashboard.tabs.automationRules': '自動化ルール', 'dashboard.tabs.variantExperiments': 'バリアント実験', 'dashboard.tabs.teamShifts': 'チームとシフト', 'dashboard.tabs.chatterRoleplay': 'Chatterとロールプレイ', 'dashboard.signOutFailed': 'サインアウトを確認できません。セッションが有効な可能性があります。もう一度お試しください。',
};

const it: Catalog = {
  ...en,
  'dashboard.performance.title': 'Cosa funziona: pattern osservati', 'dashboard.performance.description': 'Esempi verificati raggruppati solo per questo talento. Lunghezza e punti interrogativi descrivono la didascalia registrata; l’orario è la fascia UTC programmata, non necessariamente l’orario di pubblicazione effettivo.', 'dashboard.performance.ariaLabel': 'Pattern di rendimento osservati',
  'dashboard.grok.statusNotChecked': 'Connessione non verificata', 'dashboard.grok.checkSaved': 'Controlla l’accesso Grok salvato', 'dashboard.grok.connectAccount': 'Collega account Grok', 'dashboard.grok.cancelLogin': 'Annulla accesso Grok', 'dashboard.grok.loginCompleted': 'Accesso Grok completato. L’accesso alla generazione non è ancora stato verificato.', 'dashboard.grok.credentialFound': 'File delle credenziali Grok trovato. L’accesso al provider non è ancora stato verificato.', 'dashboard.grok.noCredential': 'Nessun file di credenziali Grok salvato trovato', 'dashboard.grok.checkUnconfirmed': 'Connessione non confermata. Controlla lo stato prima di riprovare.', 'dashboard.grok.cancelRequested': 'Annullamento richiesto. Controlla lo stato prima di riprovare.', 'dashboard.grok.generationNote': 'Questo controllo rileva le credenziali di accesso salvate; non verifica l’accesso reale a immagini o video. Un risultato del file delle credenziali non indica un errore di accesso. Riconnettersi non verifica l’accesso alla generazione. La generazione richiede anche un worker disponibile e impostazioni di sicurezza del workspace che la consentano.',
  'dashboard.r2.title': 'Archiviazione video R2 privata', 'dashboard.r2.description': 'Mantieni attivo Grok ZDR. Inserisci qui le credenziali S3 R2 limitate al bucket, mai nella chat. Il salvataggio non genera media né modifica i permessi del bucket.', 'dashboard.r2.endpoint': 'Endpoint S3', 'dashboard.r2.bucket': 'Bucket', 'dashboard.r2.accessKey': 'ID chiave di accesso', 'dashboard.r2.secretKey': 'Chiave di accesso segreta', 'dashboard.r2.restriction': 'Queste credenziali sono limitate alla lettura e scrittura degli oggetti per questo bucket privato.', 'dashboard.r2.save': 'Salva credenziali R2', 'dashboard.r2.checkStatus': 'Controlla stato salvato', 'dashboard.r2.verify': 'Verifica accesso al bucket', 'dashboard.r2.remove': 'Rimuovi credenziali R2 salvate', 'dashboard.r2.statusNotChecked': 'Archiviazione non verificata', 'dashboard.r2.verified': 'Lettura e scrittura del bucket R2 verificate; l’oggetto di prova temporaneo è stato rimosso.', 'dashboard.r2.saved': 'Configurazione R2 salvata. L’accesso al bucket e la generazione video non sono ancora stati verificati.', 'dashboard.r2.notConfigured': 'Nessuna configurazione R2 salvata per questo workspace e operatore.', 'dashboard.r2.operationFailed': 'Operazione di archiviazione non confermata. Controlla lo stato salvato prima di riprovare.', 'dashboard.r2.removalNote': 'La rimozione impedisce alle richieste future di caricare queste credenziali. Non revoca le chiavi Cloudflare, non elimina i media salvati e non annulla una generazione in corso.',
  'dashboard.performance.patternsUnavailable': 'Analisi dei pattern non disponibile.', 'dashboard.performance.patternsNotEnough': 'Non ci sono ancora abbastanza esempi verificati. Ogni pattern richiede almeno {count} esempi etichettati.', 'dashboard.performance.scheduledTimeUnknown': 'Orario programmato sconosciuto', 'dashboard.performance.unknownScheduledTime': 'Orario programmato sconosciuto', 'dashboard.performance.publicationTimeUnavailable': 'Orario di pubblicazione non disponibile', 'dashboard.performance.questionMark': 'contiene un punto interrogativo', 'dashboard.performance.noQuestionMark': 'nessun punto interrogativo', 'dashboard.performance.recordedMedia': 'Media registrato', 'dashboard.performance.unknownFormat': 'formato sconosciuto', 'dashboard.performance.published': 'pubblicato', 'dashboard.performance.tosVerdict': 'Verdetto ToS alla pubblicazione', 'dashboard.performance.labeledExemplars': '{count} esempi etichettati', 'dashboard.performance.meanRelativeScore': 'Punteggio medio relativo di coinvolgimento: {score}', 'dashboard.performance.showingTopGroups': 'Mostra i 20 gruppi con il punteggio più alto.', 'dashboard.performance.exploratoryDisclaimer': 'Osservazioni esplorative, non raccomandazioni né significatività statistica. I punteggi sono z-score di coinvolgimento calcolati quando ogni esempio è stato etichettato; zero rappresenta la media di confronto corrente. Sono esempi etichettati conservati, non tutti i post, e possono usare finestre storiche diverse. Non si deduce alcun aumento della conversione o effetto causale.', 'dashboard.performance.hook': 'hook', 'dashboard.performance.format': 'formato', 'dashboard.performance.timing': 'tempistica',
  'dashboard.newModel.addTalent': 'Aggiungi talento', 'dashboard.newModel.newProfile': 'Nuovo profilo', 'dashboard.newModel.welcomeTalent': 'Benvenuto al nuovo talento', 'dashboard.newModel.close': 'Chiudi', 'dashboard.newModel.creatorName': 'Nome del creator', 'dashboard.newModel.handle': 'Handle', 'dashboard.newModel.brandNote': 'Nota del brand', 'dashboard.newModel.optional': 'facoltativo', 'dashboard.newModel.createProfile': 'Crea profilo', 'dashboard.newModel.creatingProfile': 'Creazione profilo...', 'dashboard.newModel.createFailed': 'Creazione non riuscita', 'dashboard.newModel.creationUnconfirmed': 'La creazione non è stata confermata. Riprova senza modificare il modulo per controllare in sicurezza la stessa richiesta.',
  'automation.thresholdMode': 'Modalità soglia', 'automation.fixedThreshold': 'Soglia fissa', 'automation.learnedP90': 'P90 appreso', 'automation.learnedP90Summary': 'P90 appreso (minimo {count} campioni)', 'automation.learnedP90Description': 'Usa il 90° percentile delle metriche del provider verificate per questo modello e questa piattaforma; resta inattivo finché non viene raggiunto il numero minimo di campioni.', 'automation.minimumSamples': 'Campioni minimi',
  'dashboard.tabs.talentWorkspace': 'Workspace del talento', 'dashboard.tabs.relayDelivery': 'Consegna Relay', 'dashboard.tabs.agentAccess': 'Accesso agenti', 'dashboard.tabs.cascadeSchedules': 'Programmazioni in cascata', 'dashboard.tabs.automationRules': 'Regole di automazione', 'dashboard.tabs.variantExperiments': 'Esperimenti di varianti', 'dashboard.tabs.teamShifts': 'Team e turni', 'dashboard.tabs.chatterRoleplay': 'Chatter e roleplay', 'dashboard.signOutFailed': 'La disconnessione non è stata confermata. La sessione potrebbe essere ancora attiva. Riprova.',
};

const ptBR: Catalog = {
  ...en,
  'dashboard.performance.title': 'O que funciona: padrões observados', 'dashboard.performance.description': 'Exemplos verificados agrupados somente para este talento. O tamanho da legenda e os pontos de interrogação descrevem a legenda registrada; o horário é a faixa UTC programada, não necessariamente a publicação real.', 'dashboard.performance.ariaLabel': 'Padrões de desempenho observados',
  'dashboard.grok.statusNotChecked': 'Conexão não verificada', 'dashboard.grok.checkSaved': 'Verificar login salvo do Grok', 'dashboard.grok.connectAccount': 'Conectar conta do Grok', 'dashboard.grok.cancelLogin': 'Cancelar login do Grok', 'dashboard.grok.loginCompleted': 'Login do Grok concluído. O acesso à geração ainda não foi verificado.', 'dashboard.grok.credentialFound': 'Arquivo de credenciais do Grok encontrado. O acesso ao provedor ainda não foi verificado.', 'dashboard.grok.noCredential': 'Nenhum arquivo de credenciais do Grok salvo foi encontrado', 'dashboard.grok.checkUnconfirmed': 'Conexão não confirmada. Verifique o status antes de tentar novamente.', 'dashboard.grok.cancelRequested': 'Cancelamento solicitado. Verifique o status antes de tentar novamente.', 'dashboard.grok.generationNote': 'Esta verificação detecta credenciais de login salvas; ela não testa o acesso real a imagens ou vídeos. Um resultado de arquivo de credenciais não indica falha de login. Reconectar não verifica o acesso à geração. A geração também exige um worker disponível e configurações de segurança do workspace que permitam isso.',
  'dashboard.r2.title': 'Armazenamento privado de vídeo R2', 'dashboard.r2.description': 'Mantenha o Grok ZDR ativado. Insira aqui as credenciais S3 do R2 limitadas ao bucket, nunca no chat. Salvar não gera mídia nem altera permissões do bucket.', 'dashboard.r2.endpoint': 'Endpoint S3', 'dashboard.r2.bucket': 'Bucket', 'dashboard.r2.accessKey': 'ID da chave de acesso', 'dashboard.r2.secretKey': 'Chave de acesso secreta', 'dashboard.r2.restriction': 'Estas credenciais são restritas à leitura e gravação de objetos neste bucket privado.', 'dashboard.r2.save': 'Salvar credenciais do R2', 'dashboard.r2.checkStatus': 'Verificar status salvo', 'dashboard.r2.verify': 'Verificar acesso ao bucket', 'dashboard.r2.remove': 'Remover credenciais do R2 salvas', 'dashboard.r2.statusNotChecked': 'Armazenamento não verificado', 'dashboard.r2.verified': 'Leitura e gravação do bucket R2 verificadas; o objeto de teste temporário foi removido.', 'dashboard.r2.saved': 'Configuração do R2 salva. O acesso ao bucket e a geração de vídeo ainda não foram verificados.', 'dashboard.r2.notConfigured': 'Nenhuma configuração do R2 foi salva para este workspace e operador.', 'dashboard.r2.operationFailed': 'Operação de armazenamento não confirmada. Verifique o status salvo antes de tentar novamente.', 'dashboard.r2.removalNote': 'A remoção impede que futuras solicitações carreguem essas credenciais. Ela não revoga as chaves da Cloudflare, não exclui mídias salvas nem cancela uma geração em andamento.',
  'dashboard.performance.patternsUnavailable': 'A análise de padrões não está disponível.', 'dashboard.performance.patternsNotEnough': 'Ainda não há exemplos verificados suficientes. Cada padrão precisa de pelo menos {count} exemplos rotulados.', 'dashboard.performance.scheduledTimeUnknown': 'Horário programado desconhecido', 'dashboard.performance.unknownScheduledTime': 'Horário programado desconhecido', 'dashboard.performance.publicationTimeUnavailable': 'Horário de publicação indisponível', 'dashboard.performance.questionMark': 'contém um ponto de interrogação', 'dashboard.performance.noQuestionMark': 'sem ponto de interrogação', 'dashboard.performance.recordedMedia': 'Mídia registrada', 'dashboard.performance.unknownFormat': 'formato desconhecido', 'dashboard.performance.published': 'publicado', 'dashboard.performance.tosVerdict': 'Veredito de ToS na publicação', 'dashboard.performance.labeledExemplars': '{count} exemplos rotulados', 'dashboard.performance.meanRelativeScore': 'Pontuação média relativa de engajamento: {score}', 'dashboard.performance.showingTopGroups': 'Mostrando os 20 grupos com maior pontuação.', 'dashboard.performance.exploratoryDisclaimer': 'Observações exploratórias, não recomendações nem significância estatística. As pontuações são z-scores de engajamento calculados quando cada exemplo foi rotulado; zero representa a média de comparação daquele momento. São exemplos rotulados mantidos, não todas as postagens, e podem usar janelas históricas diferentes. Nenhum aumento de conversão ou efeito causal é inferido.', 'dashboard.performance.hook': 'gancho', 'dashboard.performance.format': 'formato', 'dashboard.performance.timing': 'momento',
  'dashboard.newModel.addTalent': 'Adicionar talento', 'dashboard.newModel.newProfile': 'Novo perfil', 'dashboard.newModel.welcomeTalent': 'Boas-vindas ao novo talento', 'dashboard.newModel.close': 'Fechar', 'dashboard.newModel.creatorName': 'Nome do criador', 'dashboard.newModel.handle': 'Identificador', 'dashboard.newModel.brandNote': 'Nota de marca', 'dashboard.newModel.optional': 'opcional', 'dashboard.newModel.createProfile': 'Criar perfil', 'dashboard.newModel.creatingProfile': 'Criando perfil...', 'dashboard.newModel.createFailed': 'Falha ao criar', 'dashboard.newModel.creationUnconfirmed': 'Não foi possível confirmar a criação. Tente novamente sem alterar o formulário para verificar a mesma solicitação com segurança.',
  'automation.thresholdMode': 'Modo de limite', 'automation.fixedThreshold': 'Limite fixo', 'automation.learnedP90': 'P90 aprendido', 'automation.learnedP90Summary': 'P90 aprendido (mínimo de {count} amostras)', 'automation.learnedP90Description': 'Usa o percentil 90 das métricas verificadas do provedor para este modelo e plataforma; permanece inativo até atingir o número mínimo de amostras.', 'automation.minimumSamples': 'Amostras mínimas',
  'dashboard.tabs.talentWorkspace': 'Workspace do talento', 'dashboard.tabs.relayDelivery': 'Entrega Relay', 'dashboard.tabs.agentAccess': 'Acesso de agentes', 'dashboard.tabs.cascadeSchedules': 'Programações em cascata', 'dashboard.tabs.automationRules': 'Regras de automação', 'dashboard.tabs.variantExperiments': 'Experimentos de variantes', 'dashboard.tabs.teamShifts': 'Equipe e turnos', 'dashboard.tabs.chatterRoleplay': 'Chatter e roleplay', 'dashboard.signOutFailed': 'Não foi possível confirmar o logout. Sua sessão pode continuar ativa. Tente novamente.',
};

const de: Catalog = {
  ...en,
  'dashboard.performance.title': 'Was funktioniert: beobachtete Muster', 'dashboard.performance.description': 'Verifizierte Beispiele nur für dieses Talent gruppiert. Caption-Länge und Fragezeichen beschreiben die aufgezeichnete Caption; die Zeit ist das geplante UTC-Fenster und nicht zwingend die tatsächliche Veröffentlichung.', 'dashboard.performance.ariaLabel': 'Beobachtete Leistungsmuster',
  'dashboard.grok.statusNotChecked': 'Verbindung nicht geprüft', 'dashboard.grok.checkSaved': 'Gespeicherten Grok-Login prüfen', 'dashboard.grok.connectAccount': 'Grok-Konto verbinden', 'dashboard.grok.cancelLogin': 'Grok-Login abbrechen', 'dashboard.grok.loginCompleted': 'Grok-Login abgeschlossen. Der Generierungszugriff wurde noch nicht bestätigt.', 'dashboard.grok.credentialFound': 'Grok-Anmeldedatei gefunden. Der Providerzugriff wurde noch nicht bestätigt.', 'dashboard.grok.noCredential': 'Keine gespeicherte Grok-Anmeldedatei gefunden', 'dashboard.grok.checkUnconfirmed': 'Verbindung nicht bestätigt. Prüfe den Status, bevor du es erneut versuchst.', 'dashboard.grok.cancelRequested': 'Abbruch angefordert. Prüfe den Status, bevor du es erneut versuchst.', 'dashboard.grok.generationNote': 'Diese Prüfung erkennt gespeicherte Anmeldedaten; sie testet keinen Live-Zugriff auf Bilder oder Videos. Ein Ergebnis der Anmeldedatei ist kein Loginfehler. Eine erneute Verbindung bestätigt keinen Generierungszugriff. Für die Generierung sind außerdem ein verfügbarer Worker und passende Workspace-Sicherheitseinstellungen erforderlich.',
  'dashboard.r2.title': 'Privater R2-Videospeicher', 'dashboard.r2.description': 'Lass Grok ZDR aktiviert. Gib hier auf den Bucket beschränkte R2-S3-Anmeldedaten ein, niemals im Chat. Das Speichern erzeugt keine Medien und ändert keine Bucket-Berechtigungen.', 'dashboard.r2.endpoint': 'S3-Endpunkt', 'dashboard.r2.bucket': 'Bucket', 'dashboard.r2.accessKey': 'Zugriffsschlüssel-ID', 'dashboard.r2.secretKey': 'Geheimer Zugriffsschlüssel', 'dashboard.r2.restriction': 'Diese Anmeldedaten sind auf das Lesen und Schreiben von Objekten in diesem privaten Bucket beschränkt.', 'dashboard.r2.save': 'R2-Anmeldedaten speichern', 'dashboard.r2.checkStatus': 'Gespeicherten Status prüfen', 'dashboard.r2.verify': 'Bucketzugriff prüfen', 'dashboard.r2.remove': 'Gespeicherte R2-Anmeldedaten entfernen', 'dashboard.r2.statusNotChecked': 'Speicher nicht geprüft', 'dashboard.r2.verified': 'Lesen und Schreiben im R2-Bucket bestätigt; das temporäre Prüfobjekt wurde entfernt.', 'dashboard.r2.saved': 'R2-Konfiguration gespeichert. Bucketzugriff und Videogenerierung wurden noch nicht bestätigt.', 'dashboard.r2.notConfigured': 'Für diesen Workspace und Operator ist keine R2-Konfiguration gespeichert.', 'dashboard.r2.operationFailed': 'Speichervorgang nicht bestätigt. Prüfe den gespeicherten Status, bevor du es erneut versuchst.', 'dashboard.r2.removalNote': 'Durch das Entfernen laden zukünftige Anfragen diese Anmeldedaten nicht mehr. Cloudflare-Schlüssel werden nicht widerrufen, gespeicherte Medien nicht gelöscht und laufende Generierungen nicht abgebrochen.',
  'dashboard.performance.patternsUnavailable': 'Musteranalyse nicht verfügbar.', 'dashboard.performance.patternsNotEnough': 'Noch nicht genügend geprüfte Beispiele vorhanden. Jedes Muster benötigt mindestens {count} gekennzeichnete Beispiele.', 'dashboard.performance.scheduledTimeUnknown': 'Geplante Zeit unbekannt', 'dashboard.performance.unknownScheduledTime': 'Unbekannte geplante Zeit', 'dashboard.performance.publicationTimeUnavailable': 'Veröffentlichungszeit nicht verfügbar', 'dashboard.performance.questionMark': 'enthält ein Fragezeichen', 'dashboard.performance.noQuestionMark': 'kein Fragezeichen', 'dashboard.performance.recordedMedia': 'Erfasstes Medium', 'dashboard.performance.unknownFormat': 'unbekanntes Format', 'dashboard.performance.published': 'veröffentlicht', 'dashboard.performance.tosVerdict': 'ToS-Bewertung bei Veröffentlichung', 'dashboard.performance.labeledExemplars': '{count} gekennzeichnete Beispiele', 'dashboard.performance.meanRelativeScore': 'Mittlerer relativer Engagement-Score: {score}', 'dashboard.performance.showingTopGroups': 'Die 20 Gruppen mit den höchsten Scores werden angezeigt.', 'dashboard.performance.exploratoryDisclaimer': 'Explorative Beobachtungen, keine Empfehlungen und keine statistische Signifikanz. Scores sind Engagement-z-Scores, die bei der Kennzeichnung jedes Beispiels berechnet wurden; null entspricht dem damaligen Vergleichsmittel. Dies sind gespeicherte gekennzeichnete Beispiele, nicht alle Beiträge, und unterschiedliche historische Vergleichsfenster sind möglich. Eine Conversion-Steigerung oder kausale Wirkung wird nicht abgeleitet.', 'dashboard.performance.hook': 'Hook', 'dashboard.performance.format': 'Format', 'dashboard.performance.timing': 'Timing',
  'dashboard.newModel.addTalent': 'Talent hinzufügen', 'dashboard.newModel.newProfile': 'Neues Profil', 'dashboard.newModel.welcomeTalent': 'Neues Talent begrüßen', 'dashboard.newModel.close': 'Schließen', 'dashboard.newModel.creatorName': 'Name des Creators', 'dashboard.newModel.handle': 'Handle', 'dashboard.newModel.brandNote': 'Markennotiz', 'dashboard.newModel.optional': 'optional', 'dashboard.newModel.createProfile': 'Profil erstellen', 'dashboard.newModel.creatingProfile': 'Profil wird erstellt...', 'dashboard.newModel.createFailed': 'Erstellung fehlgeschlagen', 'dashboard.newModel.creationUnconfirmed': 'Die Erstellung konnte nicht bestätigt werden. Versuche es ohne Änderungen am Formular erneut, um dieselbe Anfrage sicher zu prüfen.',
  'automation.thresholdMode': 'Grenzwertmodus', 'automation.fixedThreshold': 'Fester Grenzwert', 'automation.learnedP90': 'Gelerntes P90', 'automation.learnedP90Summary': 'Gelerntes P90 (mindestens {count} Stichproben)', 'automation.learnedP90Description': 'Verwendet das 90. Perzentil verifizierter Provider-Metriken für dieses Modell und diese Plattform; bleibt inaktiv, bis die Mindestanzahl an Stichproben erreicht ist.', 'automation.minimumSamples': 'Mindestanzahl an Stichproben',
  'dashboard.tabs.talentWorkspace': 'Talent-Arbeitsbereich', 'dashboard.tabs.relayDelivery': 'Relay-Zustellung', 'dashboard.tabs.agentAccess': 'Agentenzugriff', 'dashboard.tabs.cascadeSchedules': 'Kaskadenplanung', 'dashboard.tabs.automationRules': 'Automatisierungsregeln', 'dashboard.tabs.variantExperiments': 'Variantenexperimente', 'dashboard.tabs.teamShifts': 'Team und Schichten', 'dashboard.tabs.chatterRoleplay': 'Chatter und Rollenspiel', 'dashboard.signOutFailed': 'Die Abmeldung konnte nicht bestätigt werden. Deine Sitzung könnte noch aktiv sein. Bitte versuche es erneut.',
};

export const DASHBOARD_REMAINING_CATALOGS: Record<SupportedLocale, Catalog> = { en, es, ja, it, 'pt-BR': ptBR, de };
export const DASHBOARD_REMAINING_MESSAGE_KEYS = Object.keys(en) as Array<keyof typeof en>;
