import type { Catalog, SupportedLocale } from './locale.js';

/** Feature-owned copy for the fan CRM page and its record-only controls. */
export const FAN_CRM_MESSAGE_KEYS = [
  'fans.accessTitle',
  'fans.accessDescription',
  'fans.back',
  'fans.title',
  'fans.description',
  'fans.close',
  'fans.timeline',
  'fans.timelineError',
  'fans.activity',
  'fans.activityDisclaimer',
  'fans.noInteractions',
  'fans.noText',
  'fans.linkedRequests',
  'fans.noLinkedRequests',
  'fans.contactsTitle',
  'fans.contactsLoadFailed',
  'fans.noMoreContacts',
  'fans.noContacts',
  'fans.fanColumn',
  'fans.platformColumn',
  'fans.tierColumn',
  'fans.lifetimeColumn',
  'fans.firstContacts',
  'fans.nextContacts',
  'fans.requestsTitle',
  'fans.requestsLoadFailed',
  'fans.noRequests',
  'fans.requestTitleColumn',
  'fans.statusColumn',
  'fans.priceColumn',
  'fans.noPrice',
  'fans.add',
  'fans.contactDescription',
  'fans.saveContactAria',
  'fans.platform',
  'fans.fanAccountId',
  'fans.displayName',
  'fans.tier',
  'fans.tierKeep',
  'fans.tierNew',
  'fans.tierLoyal',
  'fans.tierWhale',
  'fans.tierExpired',
  'fans.lifetime',
  'fans.saving',
  'fans.retrySame',
  'fans.save',
  'fans.invalidContact',
  'fans.invalidTier',
  'fans.invalidLifetime',
  'fans.saveContactHttp',
  'fans.saveContactUnconfirmed',
  'fans.contactSaved',
  'fans.record',
  'fans.interactionDescription',
  'fans.interactionType',
  'fans.interactionTypePlaceholder',
  'fans.direction',
  'fans.fromFan',
  'fans.toFan',
  'fans.details',
  'fans.invalidInteraction',
  'fans.invalidDirection',
  'fans.invalidContent',
  'fans.interactionSaveHttp',
  'fans.interactionSaveUnconfirmed',
  'fans.interactionSaved',
  'fans.createRequest',
  'fans.updateStatusFor',
  'fans.requestTitle',
  'fans.requestDescription',
  'fans.linkedFanOptional',
  'fans.noLinkedContact',
  'fans.requestFormDescription',
  'fans.requestPriceOptional',
  'fans.requestStatus',
  'fans.requestInvalidStatus',
  'fans.requestInvalidFields',
  'fans.requestInvalidPrice',
  'fans.requestSaveHttp',
  'fans.requestSaveUnconfirmed',
  'fans.requestCreated',
  'fans.statusSaved',
  'fans.status.pending',
  'fans.status.filming',
  'fans.status.editing',
  'fans.status.delivered',
] as const;

export type FanCrmMessageKey = (typeof FAN_CRM_MESSAGE_KEYS)[number];

const en: Record<FanCrmMessageKey, string> = {
  'fans.accessTitle': 'Fan CRM access unavailable',
  'fans.accessDescription': 'Your role does not include these fan records.',
  'fans.back': 'Back to workspace',
  'fans.title': 'Fan relationships',
  'fans.description':
    'Browse saved fan contacts and track requests for custom content. Lifetime value is the recorded total spent by a fan.',
  'fans.close': 'Close fan details',
  'fans.timeline': 'Fan timeline',
  'fans.timelineError':
    'This fan timeline could not be loaded for this talent. Select a contact from the list or try again.',
  'fans.activity': '{name} — recorded activity',
  'fans.activityDisclaimer':
    'Up to 100 most recent saved interactions. This is not a live inbox or proof that all platforms have synchronized.',
  'fans.noInteractions': 'No recorded interactions yet.',
  'fans.noText': 'No text recorded.',
  'fans.linkedRequests': 'Linked custom requests',
  'fans.noLinkedRequests': 'No linked requests.',
  'fans.contactsTitle': 'High-value contacts',
  'fans.contactsLoadFailed': 'Fan contacts could not be loaded. Reload this page to try again.',
  'fans.noMoreContacts': 'No more contacts on this page.',
  'fans.noContacts': 'No fan contacts yet.',
  'fans.fanColumn': 'Fan',
  'fans.platformColumn': 'Platform',
  'fans.tierColumn': 'Tier',
  'fans.lifetimeColumn': 'Lifetime value',
  'fans.firstContacts': 'First contacts',
  'fans.nextContacts': 'Next contacts',
  'fans.requestsTitle': 'Custom requests',
  'fans.requestsLoadFailed': 'Custom requests could not be loaded. Reload this page to try again.',
  'fans.noRequests': 'No custom request tickets.',
  'fans.requestTitleColumn': 'Title',
  'fans.statusColumn': 'Status',
  'fans.priceColumn': 'Price',
  'fans.noPrice': '—',
  'fans.add': 'Add or update a fan',
  'fans.contactDescription':
    'The same platform and fan account ID updates the existing contact. Optional fields left blank keep existing values. This records a contact; it does not send a message.',
  'fans.saveContactAria': 'Save fan contact',
  'fans.platform': 'Platform',
  'fans.fanAccountId': 'Fan account ID',
  'fans.displayName': 'Display name',
  'fans.tier': 'Tier',
  'fans.tierKeep': 'Keep existing / new contact',
  'fans.tierNew': 'New',
  'fans.tierLoyal': 'Loyal',
  'fans.tierWhale': 'Whale',
  'fans.tierExpired': 'Expired',
  'fans.lifetime': 'Recorded lifetime value (USD)',
  'fans.saving': 'Saving...',
  'fans.retrySame': 'Retry same entry',
  'fans.save': 'Save contact',
  'fans.invalidContact': 'Enter a platform and its fan account ID; check the field lengths.',
  'fans.invalidTier': 'Choose a valid tier.',
  'fans.invalidLifetime': 'Lifetime value must be a nonnegative amount.',
  'fans.saveContactHttp':
    'Contact was not saved (HTTP {status}). Check your permissions and fields, or retry the same save.',
  'fans.saveContactUnconfirmed':
    'Save not confirmed. Retry the same contact before entering another.',
  'fans.contactSaved': 'Contact saved.',
  'fans.record': 'Record an interaction',
  'fans.interactionDescription':
    'Save an interaction that already happened. This does not send a message. The record is timestamped when saved.',
  'fans.interactionType': 'Interaction type',
  'fans.interactionTypePlaceholder': 'message, comment, purchase...',
  'fans.direction': 'Direction',
  'fans.fromFan': 'From fan',
  'fans.toFan': 'To fan (already sent)',
  'fans.details': 'Details',
  'fans.invalidInteraction': 'Enter a platform and interaction type (up to 50 characters each).',
  'fans.invalidDirection': 'Choose an interaction direction.',
  'fans.invalidContent': 'Interaction text must be at most 4,000 characters.',
  'fans.interactionSaveHttp':
    'Interaction was not saved (HTTP {status}). Check your permissions and fields, or retry the same save.',
  'fans.interactionSaveUnconfirmed':
    'Save not confirmed. Retry the same interaction before recording another.',
  'fans.interactionSaved': 'Interaction recorded. No message was sent.',
  'fans.createRequest': 'Create custom request',
  'fans.updateStatusFor': 'Update status for {title}',
  'fans.requestTitle': 'Title',
  'fans.requestDescription': 'Description',
  'fans.linkedFanOptional': 'Fan (optional)',
  'fans.noLinkedContact': 'No linked contact',
  'fans.requestFormDescription':
    'Choose from contacts loaded on this page. Creating a request records work only; it does not charge or message the fan.',
  'fans.requestPriceOptional': 'Price (USD, optional)',
  'fans.requestStatus': 'Request status',
  'fans.requestInvalidStatus': 'Choose a valid request status.',
  'fans.requestInvalidFields': 'Enter a title and check the description length.',
  'fans.requestInvalidPrice': 'Price must be a nonnegative amount.',
  'fans.requestSaveHttp':
    'Request was not saved (HTTP {status}). Check your permissions and fields, or retry the same save.',
  'fans.requestSaveUnconfirmed':
    'Save not confirmed. Retry the same request before making another change.',
  'fans.requestCreated': 'Request created.',
  'fans.statusSaved': 'Status saved.',
  'fans.status.pending': 'Pending',
  'fans.status.filming': 'Filming',
  'fans.status.editing': 'Editing',
  'fans.status.delivered': 'Delivered',
};

const es: Record<FanCrmMessageKey, string> = {
  ...en,
  'fans.accessTitle': 'CRM de fans no disponible',
  'fans.accessDescription': 'Tu rol no incluye estos registros de fans.',
  'fans.back': 'Volver al espacio de trabajo',
  'fans.title': 'Relaciones con fans',
  'fans.description':
    'Consulta contactos guardados y solicitudes de contenido personalizado. El valor de vida es el total registrado gastado por un fan.',
  'fans.close': 'Cerrar detalles del fan',
  'fans.timeline': 'Cronología del fan',
  'fans.timelineError':
    'No se pudo cargar la cronología de este fan para este talento. Selecciona un contacto de la lista o inténtalo de nuevo.',
  'fans.activity': '{name} — actividad registrada',
  'fans.activityDisclaimer':
    'Hasta las 100 interacciones guardadas más recientes. No es una bandeja de entrada en vivo ni prueba de que todas las plataformas estén sincronizadas.',
  'fans.noInteractions': 'Aún no hay interacciones registradas.',
  'fans.noText': 'No hay texto registrado.',
  'fans.linkedRequests': 'Solicitudes personalizadas vinculadas',
  'fans.noLinkedRequests': 'No hay solicitudes vinculadas.',
  'fans.contactsTitle': 'Contactos de alto valor',
  'fans.contactsLoadFailed':
    'No se pudieron cargar los contactos. Recarga la página para intentarlo de nuevo.',
  'fans.noMoreContacts': 'No hay más contactos en esta página.',
  'fans.noContacts': 'Aún no hay contactos de fans.',
  'fans.fanColumn': 'Fan',
  'fans.platformColumn': 'Plataforma',
  'fans.tierColumn': 'Nivel',
  'fans.lifetimeColumn': 'Valor de vida',
  'fans.firstContacts': 'Primeros contactos',
  'fans.nextContacts': 'Contactos siguientes',
  'fans.requestsTitle': 'Solicitudes personalizadas',
  'fans.requestsLoadFailed':
    'No se pudieron cargar las solicitudes. Recarga la página para intentarlo de nuevo.',
  'fans.noRequests': 'No hay tickets de solicitudes personalizadas.',
  'fans.requestTitleColumn': 'Título',
  'fans.statusColumn': 'Estado',
  'fans.priceColumn': 'Precio',
  'fans.noPrice': '—',
  'fans.add': 'Añadir o actualizar un fan',
  'fans.contactDescription':
    'La misma plataforma y el ID de cuenta actualizan el contacto existente. Los campos opcionales vacíos conservan los valores existentes. Esto registra un contacto; no envía mensajes.',
  'fans.saveContactAria': 'Guardar contacto de fan',
  'fans.platform': 'Plataforma',
  'fans.fanAccountId': 'ID de cuenta del fan',
  'fans.displayName': 'Nombre visible',
  'fans.tier': 'Nivel',
  'fans.tierKeep': 'Conservar existente / contacto nuevo',
  'fans.tierNew': 'Nuevo',
  'fans.tierLoyal': 'Leal',
  'fans.tierWhale': 'Premium',
  'fans.tierExpired': 'Expirado',
  'fans.lifetime': 'Valor de vida registrado (USD)',
  'fans.saving': 'Guardando...',
  'fans.retrySame': 'Reintentar la misma entrada',
  'fans.save': 'Guardar contacto',
  'fans.invalidContact':
    'Escribe una plataforma y el ID de cuenta del fan; revisa la longitud de los campos.',
  'fans.invalidTier': 'Elige un nivel válido.',
  'fans.invalidLifetime': 'El valor de vida debe ser una cantidad no negativa.',
  'fans.saveContactHttp':
    'No se guardó el contacto (HTTP {status}). Revisa permisos y campos o repite el guardado.',
  'fans.saveContactUnconfirmed':
    'Guardado no confirmado. Reintenta el mismo contacto antes de introducir otro.',
  'fans.contactSaved': 'Contacto guardado.',
  'fans.record': 'Registrar una interacción',
  'fans.interactionDescription':
    'Guarda una interacción que ya ocurrió. Esto no envía mensajes. El registro recibe una marca de tiempo al guardarse.',
  'fans.interactionType': 'Tipo de interacción',
  'fans.interactionTypePlaceholder': 'mensaje, comentario, compra...',
  'fans.direction': 'Dirección',
  'fans.fromFan': 'Del fan',
  'fans.toFan': 'Al fan (ya enviado)',
  'fans.details': 'Detalles',
  'fans.invalidInteraction':
    'Escribe una plataforma y un tipo de interacción (hasta 50 caracteres cada uno).',
  'fans.invalidDirection': 'Elige una dirección de interacción.',
  'fans.invalidContent': 'El texto debe tener como máximo 4.000 caracteres.',
  'fans.interactionSaveHttp':
    'No se guardó la interacción (HTTP {status}). Revisa permisos y campos o repite el guardado.',
  'fans.interactionSaveUnconfirmed':
    'Guardado no confirmado. Reintenta la misma interacción antes de registrar otra.',
  'fans.interactionSaved': 'Interacción registrada. No se envió ningún mensaje.',
  'fans.createRequest': 'Crear solicitud personalizada',
  'fans.updateStatusFor': 'Actualizar estado de {title}',
  'fans.requestTitle': 'Título',
  'fans.requestDescription': 'Descripción',
  'fans.linkedFanOptional': 'Fan (opcional)',
  'fans.noLinkedContact': 'Sin contacto vinculado',
  'fans.requestFormDescription':
    'Elige entre los contactos cargados en esta página. Crear una solicitud solo registra trabajo; no cobra ni envía mensajes al fan.',
  'fans.requestPriceOptional': 'Precio (USD, opcional)',
  'fans.requestStatus': 'Estado de la solicitud',
  'fans.requestInvalidStatus': 'Elige un estado válido.',
  'fans.requestInvalidFields': 'Escribe un título y revisa la longitud de la descripción.',
  'fans.requestInvalidPrice': 'El precio debe ser una cantidad no negativa.',
  'fans.requestSaveHttp':
    'No se guardó la solicitud (HTTP {status}). Revisa permisos y campos o repite el guardado.',
  'fans.requestSaveUnconfirmed':
    'Guardado no confirmado. Reintenta la misma solicitud antes de cambiarla.',
  'fans.requestCreated': 'Solicitud creada.',
  'fans.statusSaved': 'Estado guardado.',
  'fans.status.pending': 'Pendiente',
  'fans.status.filming': 'Grabando',
  'fans.status.editing': 'Editando',
  'fans.status.delivered': 'Entregada',
};

const ja: Record<FanCrmMessageKey, string> = {
  ...en,
  'fans.accessTitle': 'ファンCRMを利用できません',
  'fans.accessDescription': 'このファン記録を利用できる権限がありません。',
  'fans.back': 'ワークスペースに戻る',
  'fans.title': 'ファンとの関係',
  'fans.description':
    '保存済みのファン連絡先とカスタムコンテンツの依頼を確認します。生涯価値は記録された合計支出です。',
  'fans.close': 'ファン詳細を閉じる',
  'fans.timeline': 'ファンのタイムライン',
  'fans.timelineError':
    'このタレントのファンのタイムラインを読み込めませんでした。リストから連絡先を選ぶか、再試行してください。',
  'fans.activity': '{name} — 記録された活動',
  'fans.activityDisclaimer':
    '保存された最新100件までのインタラクションです。ライブ受信箱や全プラットフォームの同期を示すものではありません。',
  'fans.noInteractions': '記録されたインタラクションはまだありません。',
  'fans.noText': '記録されたテキストはありません。',
  'fans.linkedRequests': 'リンクされたカスタム依頼',
  'fans.noLinkedRequests': 'リンクされた依頼はありません。',
  'fans.contactsTitle': '高価値の連絡先',
  'fans.contactsLoadFailed':
    'ファン連絡先を読み込めませんでした。ページを更新して再試行してください。',
  'fans.noMoreContacts': 'このページにこれ以上の連絡先はありません。',
  'fans.noContacts': 'ファン連絡先はまだありません。',
  'fans.fanColumn': 'ファン',
  'fans.platformColumn': 'プラットフォーム',
  'fans.tierColumn': 'ティア',
  'fans.lifetimeColumn': '生涯価値',
  'fans.firstContacts': '最初の連絡先',
  'fans.nextContacts': '次の連絡先',
  'fans.requestsTitle': 'カスタム依頼',
  'fans.requestsLoadFailed':
    'カスタム依頼を読み込めませんでした。ページを更新して再試行してください。',
  'fans.noRequests': 'カスタム依頼チケットはありません。',
  'fans.requestTitleColumn': 'タイトル',
  'fans.statusColumn': '状態',
  'fans.priceColumn': '価格',
  'fans.add': 'ファンを追加または更新',
  'fans.contactDescription':
    '同じプラットフォームとファンアカウントIDで既存の連絡先を更新します。空の任意項目は既存値を保持します。連絡先を記録するだけで、メッセージは送信しません。',
  'fans.saveContactAria': 'ファン連絡先を保存',
  'fans.platform': 'プラットフォーム',
  'fans.fanAccountId': 'ファンアカウントID',
  'fans.displayName': '表示名',
  'fans.tier': 'ティア',
  'fans.tierKeep': '既存値を保持 / 新しい連絡先',
  'fans.tierNew': '新規',
  'fans.tierLoyal': 'ロイヤル',
  'fans.tierWhale': '上位',
  'fans.tierExpired': '期限切れ',
  'fans.lifetime': '記録された生涯価値（USD）',
  'fans.saving': '保存中...',
  'fans.retrySame': '同じ入力を再試行',
  'fans.save': '連絡先を保存',
  'fans.invalidContact':
    'プラットフォームとファンアカウントIDを入力し、項目の長さを確認してください。',
  'fans.invalidTier': '有効なティアを選択してください。',
  'fans.invalidLifetime': '生涯価値は0以上で入力してください。',
  'fans.saveContactHttp':
    '連絡先を保存できませんでした（HTTP {status}）。権限と入力を確認して同じ保存を再試行してください。',
  'fans.saveContactUnconfirmed':
    '保存を確認できませんでした。別の連絡先を入力する前に同じ連絡先を再試行してください。',
  'fans.contactSaved': '連絡先を保存しました。',
  'fans.record': 'インタラクションを記録',
  'fans.interactionDescription':
    'すでに発生したインタラクションを保存します。メッセージは送信しません。保存時に時刻が記録されます。',
  'fans.interactionType': 'インタラクション種別',
  'fans.interactionTypePlaceholder': 'メッセージ、コメント、購入...',
  'fans.direction': '方向',
  'fans.fromFan': 'ファンから',
  'fans.toFan': 'ファンへ（送信済み）',
  'fans.details': '詳細',
  'fans.invalidInteraction':
    'プラットフォームとインタラクション種別を入力してください（各50文字以内）。',
  'fans.invalidDirection': 'インタラクションの方向を選択してください。',
  'fans.invalidContent': 'テキストは4,000文字以内です。',
  'fans.interactionSaveHttp':
    'インタラクションを保存できませんでした（HTTP {status}）。権限と入力を確認してください。',
  'fans.interactionSaveUnconfirmed':
    '保存を確認できませんでした。同じインタラクションを再試行してください。',
  'fans.interactionSaved': 'インタラクションを記録しました。メッセージは送信されていません。',
  'fans.createRequest': 'カスタム依頼を作成',
  'fans.updateStatusFor': '{title}の状態を更新',
  'fans.requestTitle': 'タイトル',
  'fans.requestDescription': '説明',
  'fans.linkedFanOptional': 'ファン（任意）',
  'fans.noLinkedContact': 'リンクされた連絡先なし',
  'fans.requestFormDescription':
    'このページに読み込まれた連絡先から選択します。依頼の作成は作業を記録するだけで、料金請求やメッセージ送信は行いません。',
  'fans.requestPriceOptional': '価格（USD、任意）',
  'fans.requestStatus': '依頼の状態',
  'fans.requestInvalidStatus': '有効な依頼状態を選択してください。',
  'fans.requestInvalidFields': 'タイトルを入力し、説明の長さを確認してください。',
  'fans.requestInvalidPrice': '価格は0以上で入力してください。',
  'fans.requestSaveHttp':
    '依頼を保存できませんでした（HTTP {status}）。権限と入力を確認してください。',
  'fans.requestSaveUnconfirmed': '保存を確認できませんでした。同じ依頼を再試行してください。',
  'fans.requestCreated': '依頼を作成しました。',
  'fans.statusSaved': '状態を保存しました。',
  'fans.status.pending': '保留中',
  'fans.status.filming': '撮影中',
  'fans.status.editing': '編集中',
  'fans.status.delivered': '納品済み',
};

const it: Record<FanCrmMessageKey, string> = {
  ...en,
  'fans.accessTitle': 'CRM dei fan non disponibile',
  'fans.accessDescription': 'Il tuo ruolo non include questi record dei fan.',
  'fans.back': 'Torna allo spazio di lavoro',
  'fans.title': 'Relazioni con i fan',
  'fans.description':
    'Consulta i contatti salvati e monitora le richieste di contenuti personalizzati. Il valore complessivo è la spesa totale registrata di un fan.',
  'fans.close': 'Chiudi dettagli fan',
  'fans.timeline': 'Cronologia del fan',
  'fans.timelineError':
    'Impossibile caricare la cronologia di questo fan per questo talent. Seleziona un contatto dall’elenco o riprova.',
  'fans.activity': '{name} — attività registrata',
  'fans.activityDisclaimer':
    'Fino alle 100 interazioni salvate più recenti. Non è una posta in arrivo live né una prova di sincronizzazione completa.',
  'fans.noInteractions': 'Nessuna interazione registrata.',
  'fans.noText': 'Nessun testo registrato.',
  'fans.linkedRequests': 'Richieste personalizzate collegate',
  'fans.noLinkedRequests': 'Nessuna richiesta collegata.',
  'fans.contactsTitle': 'Contatti di alto valore',
  'fans.contactsLoadFailed': 'Impossibile caricare i contatti. Ricarica la pagina per riprovare.',
  'fans.noMoreContacts': 'Nessun altro contatto in questa pagina.',
  'fans.noContacts': 'Nessun contatto fan.',
  'fans.fanColumn': 'Fan',
  'fans.platformColumn': 'Piattaforma',
  'fans.tierColumn': 'Livello',
  'fans.lifetimeColumn': 'Valore complessivo',
  'fans.firstContacts': 'Primi contatti',
  'fans.nextContacts': 'Contatti successivi',
  'fans.requestsTitle': 'Richieste personalizzate',
  'fans.requestsLoadFailed': 'Impossibile caricare le richieste. Ricarica la pagina per riprovare.',
  'fans.noRequests': 'Nessun ticket di richiesta personalizzata.',
  'fans.requestTitleColumn': 'Titolo',
  'fans.statusColumn': 'Stato',
  'fans.priceColumn': 'Prezzo',
  'fans.add': 'Aggiungi o aggiorna un fan',
  'fans.contactDescription':
    'La stessa piattaforma e lo stesso ID account aggiornano il contatto esistente. I campi opzionali vuoti mantengono i valori attuali. Registra un contatto; non invia messaggi.',
  'fans.saveContactAria': 'Salva contatto fan',
  'fans.platform': 'Piattaforma',
  'fans.fanAccountId': 'ID account fan',
  'fans.displayName': 'Nome visualizzato',
  'fans.tier': 'Livello',
  'fans.tierKeep': 'Mantieni esistente / nuovo contatto',
  'fans.tierNew': 'Nuovo',
  'fans.tierLoyal': 'Fedele',
  'fans.tierWhale': 'Premium',
  'fans.tierExpired': 'Scaduto',
  'fans.lifetime': 'Valore complessivo registrato (USD)',
  'fans.saving': 'Salvataggio...',
  'fans.retrySame': 'Riprova stessa voce',
  'fans.save': 'Salva contatto',
  'fans.invalidContact':
    'Inserisci una piattaforma e l’ID account del fan; controlla la lunghezza dei campi.',
  'fans.invalidTier': 'Scegli un livello valido.',
  'fans.invalidLifetime': 'Il valore complessivo deve essere un importo non negativo.',
  'fans.saveContactHttp':
    'Contatto non salvato (HTTP {status}). Controlla permessi e campi o riprova lo stesso salvataggio.',
  'fans.saveContactUnconfirmed':
    'Salvataggio non confermato. Riprova lo stesso contatto prima di inserirne un altro.',
  'fans.contactSaved': 'Contatto salvato.',
  'fans.record': 'Registra un’interazione',
  'fans.interactionDescription':
    'Salva un’interazione già avvenuta. Non invia messaggi. Il record riceve un timestamp al salvataggio.',
  'fans.interactionType': 'Tipo di interazione',
  'fans.interactionTypePlaceholder': 'messaggio, commento, acquisto...',
  'fans.direction': 'Direzione',
  'fans.fromFan': 'Dal fan',
  'fans.toFan': 'Al fan (già inviato)',
  'fans.details': 'Dettagli',
  'fans.invalidInteraction':
    'Inserisci piattaforma e tipo di interazione (massimo 50 caratteri ciascuno).',
  'fans.invalidDirection': 'Scegli una direzione.',
  'fans.invalidContent': 'Il testo può contenere al massimo 4.000 caratteri.',
  'fans.interactionSaveHttp':
    'Interazione non salvata (HTTP {status}). Controlla permessi e campi o riprova.',
  'fans.interactionSaveUnconfirmed':
    'Salvataggio non confermato. Riprova la stessa interazione prima di registrarne un’altra.',
  'fans.interactionSaved': 'Interazione registrata. Nessun messaggio inviato.',
  'fans.createRequest': 'Crea richiesta personalizzata',
  'fans.updateStatusFor': 'Aggiorna stato di {title}',
  'fans.requestTitle': 'Titolo',
  'fans.requestDescription': 'Descrizione',
  'fans.linkedFanOptional': 'Fan (facoltativo)',
  'fans.noLinkedContact': 'Nessun contatto collegato',
  'fans.requestFormDescription':
    'Scegli tra i contatti caricati in questa pagina. Creare una richiesta registra solo il lavoro; non addebita né invia messaggi al fan.',
  'fans.requestPriceOptional': 'Prezzo (USD, facoltativo)',
  'fans.requestStatus': 'Stato della richiesta',
  'fans.requestInvalidStatus': 'Scegli uno stato valido.',
  'fans.requestInvalidFields': 'Inserisci un titolo e controlla la lunghezza della descrizione.',
  'fans.requestInvalidPrice': 'Il prezzo deve essere un importo non negativo.',
  'fans.requestSaveHttp':
    'Richiesta non salvata (HTTP {status}). Controlla permessi e campi o riprova.',
  'fans.requestSaveUnconfirmed':
    'Salvataggio non confermato. Riprova la stessa richiesta prima di modificarla.',
  'fans.requestCreated': 'Richiesta creata.',
  'fans.statusSaved': 'Stato salvato.',
  'fans.status.pending': 'In attesa',
  'fans.status.filming': 'In ripresa',
  'fans.status.editing': 'In modifica',
  'fans.status.delivered': 'Consegnata',
};

const pt: Record<FanCrmMessageKey, string> = {
  ...en,
  'fans.accessTitle': 'CRM de fãs indisponível',
  'fans.accessDescription': 'Seu papel não inclui estes registros de fãs.',
  'fans.back': 'Voltar ao espaço de trabalho',
  'fans.title': 'Relacionamentos com fãs',
  'fans.description':
    'Veja contatos salvos e acompanhe pedidos de conteúdo personalizado. O valor vitalício é o total registrado gasto por um fã.',
  'fans.close': 'Fechar detalhes do fã',
  'fans.timeline': 'Linha do tempo do fã',
  'fans.timelineError':
    'Não foi possível carregar a linha do tempo deste fã para este talento. Selecione um contato da lista ou tente novamente.',
  'fans.activity': '{name} — atividade registrada',
  'fans.activityDisclaimer':
    'Até as 100 interações salvas mais recentes. Não é uma caixa de entrada ao vivo nem prova de sincronização de todas as plataformas.',
  'fans.noInteractions': 'Nenhuma interação registrada ainda.',
  'fans.noText': 'Nenhum texto registrado.',
  'fans.linkedRequests': 'Pedidos personalizados vinculados',
  'fans.noLinkedRequests': 'Nenhum pedido vinculado.',
  'fans.contactsTitle': 'Contatos de alto valor',
  'fans.contactsLoadFailed':
    'Não foi possível carregar os contatos. Recarregue a página para tentar novamente.',
  'fans.noMoreContacts': 'Não há mais contatos nesta página.',
  'fans.noContacts': 'Ainda não há contatos de fãs.',
  'fans.fanColumn': 'Fã',
  'fans.platformColumn': 'Plataforma',
  'fans.tierColumn': 'Nível',
  'fans.lifetimeColumn': 'Valor vitalício',
  'fans.firstContacts': 'Primeiros contatos',
  'fans.nextContacts': 'Próximos contatos',
  'fans.requestsTitle': 'Pedidos personalizados',
  'fans.requestsLoadFailed':
    'Não foi possível carregar os pedidos. Recarregue a página para tentar novamente.',
  'fans.noRequests': 'Nenhum ticket de pedido personalizado.',
  'fans.requestTitleColumn': 'Título',
  'fans.statusColumn': 'Status',
  'fans.priceColumn': 'Preço',
  'fans.add': 'Adicionar ou atualizar fã',
  'fans.contactDescription':
    'A mesma plataforma e o ID da conta do fã atualizam o contato existente. Campos opcionais vazios mantêm os valores atuais. Isso registra um contato; não envia mensagem.',
  'fans.saveContactAria': 'Salvar contato do fã',
  'fans.platform': 'Plataforma',
  'fans.fanAccountId': 'ID da conta do fã',
  'fans.displayName': 'Nome de exibição',
  'fans.tier': 'Nível',
  'fans.tierKeep': 'Manter existente / novo contato',
  'fans.tierNew': 'Novo',
  'fans.tierLoyal': 'Fiel',
  'fans.tierWhale': 'Premium',
  'fans.tierExpired': 'Expirado',
  'fans.lifetime': 'Valor vitalício registrado (USD)',
  'fans.saving': 'Salvando...',
  'fans.retrySame': 'Tentar a mesma entrada novamente',
  'fans.save': 'Salvar contato',
  'fans.invalidContact':
    'Informe uma plataforma e o ID da conta do fã; confira o tamanho dos campos.',
  'fans.invalidTier': 'Escolha um nível válido.',
  'fans.invalidLifetime': 'O valor vitalício deve ser um valor não negativo.',
  'fans.saveContactHttp':
    'O contato não foi salvo (HTTP {status}). Confira permissões e campos ou tente salvar novamente.',
  'fans.saveContactUnconfirmed':
    'Salvamento não confirmado. Tente o mesmo contato novamente antes de inserir outro.',
  'fans.contactSaved': 'Contato salvo.',
  'fans.record': 'Registrar interação',
  'fans.interactionDescription':
    'Salve uma interação que já aconteceu. Isso não envia mensagem. O registro recebe um horário ao ser salvo.',
  'fans.interactionType': 'Tipo de interação',
  'fans.interactionTypePlaceholder': 'mensagem, comentário, compra...',
  'fans.direction': 'Direção',
  'fans.fromFan': 'Do fã',
  'fans.toFan': 'Para o fã (já enviado)',
  'fans.details': 'Detalhes',
  'fans.invalidInteraction':
    'Informe uma plataforma e um tipo de interação (até 50 caracteres cada).',
  'fans.invalidDirection': 'Escolha uma direção de interação.',
  'fans.invalidContent': 'O texto da interação deve ter no máximo 4.000 caracteres.',
  'fans.interactionSaveHttp':
    'A interação não foi salva (HTTP {status}). Confira permissões e campos ou tente novamente.',
  'fans.interactionSaveUnconfirmed':
    'Salvamento não confirmado. Tente a mesma interação novamente antes de registrar outra.',
  'fans.interactionSaved': 'Interação registrada. Nenhuma mensagem foi enviada.',
  'fans.createRequest': 'Criar pedido personalizado',
  'fans.updateStatusFor': 'Atualizar status de {title}',
  'fans.requestTitle': 'Título',
  'fans.requestDescription': 'Descrição',
  'fans.linkedFanOptional': 'Fã (opcional)',
  'fans.noLinkedContact': 'Nenhum contato vinculado',
  'fans.requestFormDescription':
    'Escolha entre os contatos carregados nesta página. Criar um pedido registra apenas o trabalho; não cobra nem envia mensagem ao fã.',
  'fans.requestPriceOptional': 'Preço (USD, opcional)',
  'fans.requestStatus': 'Status do pedido',
  'fans.requestInvalidStatus': 'Escolha um status válido.',
  'fans.requestInvalidFields': 'Informe um título e confira o tamanho da descrição.',
  'fans.requestInvalidPrice': 'O preço deve ser um valor não negativo.',
  'fans.requestSaveHttp':
    'O pedido não foi salvo (HTTP {status}). Confira permissões e campos ou tente novamente.',
  'fans.requestSaveUnconfirmed':
    'Salvamento não confirmado. Tente o mesmo pedido novamente antes de fazer outra alteração.',
  'fans.requestCreated': 'Pedido criado.',
  'fans.statusSaved': 'Status salvo.',
  'fans.status.pending': 'Pendente',
  'fans.status.filming': 'Filmando',
  'fans.status.editing': 'Editando',
  'fans.status.delivered': 'Entregue',
};

const de: Record<FanCrmMessageKey, string> = {
  ...en,
  'fans.accessTitle': 'Fan-CRM nicht verfügbar',
  'fans.accessDescription': 'Ihre Rolle umfasst diese Fan-Datensätze nicht.',
  'fans.back': 'Zurück zum Arbeitsbereich',
  'fans.title': 'Fan-Beziehungen',
  'fans.description':
    'Gespeicherte Fan-Kontakte und Anfragen für individuelle Inhalte verwalten. Der Lebenszeitwert ist die erfasste Gesamtausgabe eines Fans.',
  'fans.close': 'Fan-Details schließen',
  'fans.timeline': 'Fan-Zeitleiste',
  'fans.timelineError':
    'Die Zeitleiste dieses Fans konnte für dieses Talent nicht geladen werden. Wählen Sie einen Kontakt aus oder versuchen Sie es erneut.',
  'fans.activity': '{name} — erfasste Aktivität',
  'fans.activityDisclaimer':
    'Bis zu 100 der neuesten gespeicherten Interaktionen. Dies ist kein Live-Posteingang und bestätigt keine vollständige Plattform-Synchronisierung.',
  'fans.noInteractions': 'Noch keine Interaktionen erfasst.',
  'fans.noText': 'Kein Text erfasst.',
  'fans.linkedRequests': 'Verknüpfte individuelle Anfragen',
  'fans.noLinkedRequests': 'Keine verknüpften Anfragen.',
  'fans.contactsTitle': 'Kontakte mit hohem Wert',
  'fans.contactsLoadFailed': 'Fan-Kontakte konnten nicht geladen werden. Laden Sie die Seite neu.',
  'fans.noMoreContacts': 'Keine weiteren Kontakte auf dieser Seite.',
  'fans.noContacts': 'Noch keine Fan-Kontakte.',
  'fans.fanColumn': 'Fan',
  'fans.platformColumn': 'Plattform',
  'fans.tierColumn': 'Stufe',
  'fans.lifetimeColumn': 'Lebenszeitwert',
  'fans.firstContacts': 'Erste Kontakte',
  'fans.nextContacts': 'Weitere Kontakte',
  'fans.requestsTitle': 'Individuelle Anfragen',
  'fans.requestsLoadFailed':
    'Individuelle Anfragen konnten nicht geladen werden. Laden Sie die Seite neu.',
  'fans.noRequests': 'Keine Tickets für individuelle Anfragen.',
  'fans.requestTitleColumn': 'Titel',
  'fans.statusColumn': 'Status',
  'fans.priceColumn': 'Preis',
  'fans.add': 'Fan hinzufügen oder aktualisieren',
  'fans.contactDescription':
    'Dieselbe Plattform und Fan-Konto-ID aktualisieren den vorhandenen Kontakt. Leere optionale Felder behalten bestehende Werte. Es wird nur ein Kontakt erfasst; es wird keine Nachricht gesendet.',
  'fans.saveContactAria': 'Fan-Kontakt speichern',
  'fans.platform': 'Plattform',
  'fans.fanAccountId': 'Fan-Konto-ID',
  'fans.displayName': 'Anzeigename',
  'fans.tier': 'Stufe',
  'fans.tierKeep': 'Vorhandene behalten / neuer Kontakt',
  'fans.tierNew': 'Neu',
  'fans.tierLoyal': 'Treuer Fan',
  'fans.tierWhale': 'Premium',
  'fans.tierExpired': 'Abgelaufen',
  'fans.lifetime': 'Erfasster Lebenszeitwert (USD)',
  'fans.saving': 'Wird gespeichert...',
  'fans.retrySame': 'Denselben Eintrag erneut versuchen',
  'fans.save': 'Kontakt speichern',
  'fans.invalidContact':
    'Geben Sie eine Plattform und die Fan-Konto-ID ein; prüfen Sie die Feldlängen.',
  'fans.invalidTier': 'Wählen Sie eine gültige Stufe.',
  'fans.invalidLifetime': 'Der Lebenszeitwert muss ein nicht negativer Betrag sein.',
  'fans.saveContactHttp':
    'Kontakt wurde nicht gespeichert (HTTP {status}). Prüfen Sie Berechtigungen und Felder oder wiederholen Sie den Speichervorgang.',
  'fans.saveContactUnconfirmed':
    'Speichern nicht bestätigt. Wiederholen Sie denselben Kontakt, bevor Sie einen weiteren eingeben.',
  'fans.contactSaved': 'Kontakt gespeichert.',
  'fans.record': 'Interaktion erfassen',
  'fans.interactionDescription':
    'Eine bereits erfolgte Interaktion speichern. Es wird keine Nachricht gesendet. Beim Speichern wird ein Zeitstempel gesetzt.',
  'fans.interactionType': 'Interaktionstyp',
  'fans.interactionTypePlaceholder': 'Nachricht, Kommentar, Kauf...',
  'fans.direction': 'Richtung',
  'fans.fromFan': 'Vom Fan',
  'fans.toFan': 'An den Fan (bereits gesendet)',
  'fans.details': 'Details',
  'fans.invalidInteraction':
    'Geben Sie Plattform und Interaktionstyp ein (jeweils höchstens 50 Zeichen).',
  'fans.invalidDirection': 'Wählen Sie eine Interaktionsrichtung.',
  'fans.invalidContent': 'Der Interaktionstext darf höchstens 4.000 Zeichen enthalten.',
  'fans.interactionSaveHttp':
    'Interaktion wurde nicht gespeichert (HTTP {status}). Prüfen Sie Berechtigungen und Felder oder versuchen Sie es erneut.',
  'fans.interactionSaveUnconfirmed':
    'Speichern nicht bestätigt. Wiederholen Sie dieselbe Interaktion, bevor Sie eine weitere erfassen.',
  'fans.interactionSaved': 'Interaktion erfasst. Es wurde keine Nachricht gesendet.',
  'fans.createRequest': 'Individuelle Anfrage erstellen',
  'fans.updateStatusFor': 'Status von {title} aktualisieren',
  'fans.requestTitle': 'Titel',
  'fans.requestDescription': 'Beschreibung',
  'fans.linkedFanOptional': 'Fan (optional)',
  'fans.noLinkedContact': 'Kein verknüpfter Kontakt',
  'fans.requestFormDescription':
    'Wählen Sie aus den auf dieser Seite geladenen Kontakten. Eine Anfrage erfasst nur Arbeit; sie belastet oder kontaktiert den Fan nicht.',
  'fans.requestPriceOptional': 'Preis (USD, optional)',
  'fans.requestStatus': 'Anfragestatus',
  'fans.requestInvalidStatus': 'Wählen Sie einen gültigen Anfragestatus.',
  'fans.requestInvalidFields': 'Geben Sie einen Titel ein und prüfen Sie die Beschreibungslänge.',
  'fans.requestInvalidPrice': 'Der Preis muss ein nicht negativer Betrag sein.',
  'fans.requestSaveHttp':
    'Anfrage wurde nicht gespeichert (HTTP {status}). Prüfen Sie Berechtigungen und Felder oder versuchen Sie es erneut.',
  'fans.requestSaveUnconfirmed':
    'Speichern nicht bestätigt. Wiederholen Sie dieselbe Anfrage, bevor Sie eine weitere Änderung vornehmen.',
  'fans.requestCreated': 'Anfrage erstellt.',
  'fans.statusSaved': 'Status gespeichert.',
  'fans.status.pending': 'Ausstehend',
  'fans.status.filming': 'Dreh',
  'fans.status.editing': 'Bearbeitung',
  'fans.status.delivered': 'Geliefert',
};

export const FAN_CRM_CATALOGS: Record<SupportedLocale, Catalog> = {
  en,
  es,
  ja,
  it,
  'pt-BR': pt,
  de,
};

export function fanCrmCatalogIsComplete(locale: SupportedLocale): boolean {
  return FAN_CRM_MESSAGE_KEYS.every(
    (key) =>
      typeof FAN_CRM_CATALOGS[locale][key] === 'string' && FAN_CRM_CATALOGS[locale][key].length > 0,
  );
}
