import type { Catalog, SupportedLocale } from './locale.js';

/**
 * Feature-owned copy for the mounted Fanvue account-analytics card.
 *
 * This stays separate from the large generated base catalog so feature slices
 * can add a complete, testable surface without hand-editing generated output.
 */
export const FANVUE_ANALYTICS_KEYS = [
  'fans.analytics.title',
  'fans.analytics.description',
  'fans.analytics.sync',
  'fans.analytics.queueing',
  'fans.analytics.loadUnavailable',
  'fans.analytics.syncQueued',
  'fans.analytics.syncFailed',
  'fans.analytics.noSnapshot',
  'fans.analytics.subscribers',
  'fans.analytics.netEarnings',
  'fans.analytics.unreadMessages',
  'fans.analytics.topSpenders',
  'fans.analytics.contactsSummary',
  'fans.analytics.contactFallback',
  'fans.analytics.crmContacts',
  'fans.analytics.lifetimeValue',
] as const;

export type FanvueAnalyticsKey = (typeof FANVUE_ANALYTICS_KEYS)[number];

export const FANVUE_ANALYTICS_CATALOGS: Record<SupportedLocale, Catalog> = {
  en: {
    'fans.analytics.title': 'Fanvue account analytics',
    'fans.analytics.description': 'Account-level subscribers, earnings, unread messages and top-spender CRM facts.',
    'fans.analytics.sync': 'Sync Fanvue analytics',
    'fans.analytics.queueing': 'Queueing…',
    'fans.analytics.loadUnavailable': 'Fanvue account analytics are not available yet.',
    'fans.analytics.syncQueued': 'Fanvue analytics sync queued. Refresh this card after the worker completes.',
    'fans.analytics.syncFailed': 'Fanvue analytics could not be queued. Check the account connection and try again.',
    'fans.analytics.noSnapshot': 'No account snapshot has been synchronized yet.',
    'fans.analytics.subscribers': 'Subscribers',
    'fans.analytics.netEarnings': 'Net earnings',
    'fans.analytics.unreadMessages': 'Unread messages',
    'fans.analytics.topSpenders': 'Top spenders',
    'fans.analytics.contactsSummary': 'Synced Fanvue CRM contacts',
    'fans.analytics.contactFallback': 'Fan',
    'fans.analytics.crmContacts': '{count} synced CRM contacts',
    'fans.analytics.lifetimeValue': 'Lifetime value: {value}',
  },
  es: {
    'fans.analytics.title': 'Analítica de la cuenta de Fanvue',
    'fans.analytics.description': 'Suscriptores, ingresos, mensajes sin leer y datos CRM de los mayores gastadores a nivel de cuenta.',
    'fans.analytics.sync': 'Sincronizar analítica de Fanvue',
    'fans.analytics.queueing': 'Encolando…',
    'fans.analytics.loadUnavailable': 'La analítica de la cuenta de Fanvue aún no está disponible.',
    'fans.analytics.syncQueued': 'La sincronización de analítica de Fanvue está en cola. Actualiza esta tarjeta cuando termine el trabajador.',
    'fans.analytics.syncFailed': 'No se pudo encolar la analítica de Fanvue. Comprueba la conexión de la cuenta e inténtalo de nuevo.',
    'fans.analytics.noSnapshot': 'Aún no se ha sincronizado ninguna instantánea de la cuenta.',
    'fans.analytics.subscribers': 'Suscriptores',
    'fans.analytics.netEarnings': 'Ingresos netos',
    'fans.analytics.unreadMessages': 'Mensajes sin leer',
    'fans.analytics.topSpenders': 'Mayores gastadores',
    'fans.analytics.contactsSummary': 'Contactos CRM de Fanvue sincronizados',
    'fans.analytics.contactFallback': 'Fan',
    'fans.analytics.crmContacts': '{count} contactos CRM sincronizados',
    'fans.analytics.lifetimeValue': 'Valor de vida: {value}',
  },
  ja: {
    'fans.analytics.title': 'Fanvueアカウント分析',
    'fans.analytics.description': 'アカウント単位の購読者、収益、未読メッセージ、上位支出者のCRM情報です。',
    'fans.analytics.sync': 'Fanvue分析を同期',
    'fans.analytics.queueing': 'キューに追加中…',
    'fans.analytics.loadUnavailable': 'Fanvueアカウント分析はまだ利用できません。',
    'fans.analytics.syncQueued': 'Fanvue分析の同期をキューに追加しました。処理が終わったらこのカードを更新してください。',
    'fans.analytics.syncFailed': 'Fanvue分析をキューに追加できませんでした。アカウント接続を確認して再試行してください。',
    'fans.analytics.noSnapshot': 'アカウントのスナップショットはまだ同期されていません。',
    'fans.analytics.subscribers': '購読者',
    'fans.analytics.netEarnings': '純収益',
    'fans.analytics.unreadMessages': '未読メッセージ',
    'fans.analytics.topSpenders': '上位支出者',
    'fans.analytics.contactsSummary': '同期済みFanvue CRM連絡先',
    'fans.analytics.contactFallback': 'ファン',
    'fans.analytics.crmContacts': '{count}件のCRM連絡先を同期済み',
    'fans.analytics.lifetimeValue': '生涯価値: {value}',
  },
  it: {
    'fans.analytics.title': 'Analisi dell’account Fanvue',
    'fans.analytics.description': 'Dati CRM a livello di account su iscritti, guadagni, messaggi non letti e utenti con maggiore spesa.',
    'fans.analytics.sync': 'Sincronizza analisi Fanvue',
    'fans.analytics.queueing': 'Accodamento…',
    'fans.analytics.loadUnavailable': 'Le analisi dell’account Fanvue non sono ancora disponibili.',
    'fans.analytics.syncQueued': 'Sincronizzazione delle analisi Fanvue accodata. Aggiorna questa scheda al termine del worker.',
    'fans.analytics.syncFailed': 'Impossibile accodare le analisi Fanvue. Controlla la connessione dell’account e riprova.',
    'fans.analytics.noSnapshot': 'Nessuna istantanea dell’account è stata ancora sincronizzata.',
    'fans.analytics.subscribers': 'Iscritti',
    'fans.analytics.netEarnings': 'Guadagni netti',
    'fans.analytics.unreadMessages': 'Messaggi non letti',
    'fans.analytics.topSpenders': 'Utenti con maggiore spesa',
    'fans.analytics.contactsSummary': 'Contatti CRM Fanvue sincronizzati',
    'fans.analytics.contactFallback': 'Fan',
    'fans.analytics.crmContacts': '{count} contatti CRM sincronizzati',
    'fans.analytics.lifetimeValue': 'Valore complessivo: {value}',
  },
  'pt-BR': {
    'fans.analytics.title': 'Análises da conta Fanvue',
    'fans.analytics.description': 'Assinantes, ganhos, mensagens não lidas e dados de CRM dos maiores gastadores no nível da conta.',
    'fans.analytics.sync': 'Sincronizar análises do Fanvue',
    'fans.analytics.queueing': 'Enfileirando…',
    'fans.analytics.loadUnavailable': 'As análises da conta Fanvue ainda não estão disponíveis.',
    'fans.analytics.syncQueued': 'A sincronização das análises do Fanvue foi enfileirada. Atualize este cartão quando o worker terminar.',
    'fans.analytics.syncFailed': 'Não foi possível enfileirar as análises do Fanvue. Verifique a conexão da conta e tente novamente.',
    'fans.analytics.noSnapshot': 'Nenhum instantâneo da conta foi sincronizado ainda.',
    'fans.analytics.subscribers': 'Assinantes',
    'fans.analytics.netEarnings': 'Ganhos líquidos',
    'fans.analytics.unreadMessages': 'Mensagens não lidas',
    'fans.analytics.topSpenders': 'Maiores gastadores',
    'fans.analytics.contactsSummary': 'Contatos de CRM do Fanvue sincronizados',
    'fans.analytics.contactFallback': 'Fã',
    'fans.analytics.crmContacts': '{count} contatos de CRM sincronizados',
    'fans.analytics.lifetimeValue': 'Valor ao longo da vida: {value}',
  },
  de: {
    'fans.analytics.title': 'Fanvue-Kontoanalysen',
    'fans.analytics.description': 'Kontoweite CRM-Fakten zu Abonnenten, Einnahmen, ungelesenen Nachrichten und Top-Ausgebern.',
    'fans.analytics.sync': 'Fanvue-Analysen synchronisieren',
    'fans.analytics.queueing': 'Wird eingereiht…',
    'fans.analytics.loadUnavailable': 'Fanvue-Kontoanalysen sind noch nicht verfügbar.',
    'fans.analytics.syncQueued': 'Die Synchronisierung der Fanvue-Analysen wurde eingereiht. Aktualisieren Sie diese Karte nach Abschluss des Workers.',
    'fans.analytics.syncFailed': 'Fanvue-Analysen konnten nicht eingereiht werden. Prüfen Sie die Kontoverbindung und versuchen Sie es erneut.',
    'fans.analytics.noSnapshot': 'Es wurde noch keine Konto-Schnappschuss synchronisiert.',
    'fans.analytics.subscribers': 'Abonnenten',
    'fans.analytics.netEarnings': 'Nettoeinnahmen',
    'fans.analytics.unreadMessages': 'Ungelesene Nachrichten',
    'fans.analytics.topSpenders': 'Top-Ausgeber',
    'fans.analytics.contactsSummary': 'Synchronisierte Fanvue-CRM-Kontakte',
    'fans.analytics.contactFallback': 'Fan',
    'fans.analytics.crmContacts': '{count} synchronisierte CRM-Kontakte',
    'fans.analytics.lifetimeValue': 'Lebenszeitwert: {value}',
  },
};
