import type { Catalog, SupportedLocale } from './locale.js';

/** UI copy for operator-confirmed publish reconciliation. */
export const INCIDENT_RECONCILIATION_CATALOGS: Record<SupportedLocale, Catalog> = {
  en: {
    'incidents.reconcileHeading': 'Reconcile unknown publish outcome',
    'incidents.reconcileDescription': "Check the provider's own dashboard or API first. Recording an outcome only updates FanThynks; it never contacts the provider or sends anything. If you confirm nothing was published, the job stays stopped until you separately choose Replay.",
    'incidents.reconcileRemoteId': 'Provider post ID (optional, if published)',
    'incidents.reconcilePublished': 'I confirmed it was published',
    'incidents.reconcileNotPublished': 'I confirmed it was not published',
    'incidents.reconcileConfirmPublished': 'Confirm that you checked the provider and verified this post was published. FanThynks will only record your result and will not contact the provider.',
    'incidents.reconcileConfirmNotPublished': 'Confirm that you checked the provider and verified no post was created. FanThynks will only record your result; nothing will be sent unless you separately choose Replay.',
    'incidents.reconcilePublishedSaved': 'Provider outcome recorded as published. No provider request was made.',
    'incidents.reconcileNotPublishedSaved': 'Provider outcome recorded. Nothing was sent; Replay remains a separate action.',
    'incidents.reconcileFailed': 'Could not record the provider outcome.',
    'incidents.reconcileNotConfirmed': 'The outcome could not be confirmed. Refresh incidents before retrying.',
  },
  es: {
    'incidents.reconcileHeading': 'Conciliar un resultado de publicación desconocido',
    'incidents.reconcileDescription': 'Primero revisa el panel o la API del proveedor. Registrar un resultado solo actualiza FanThynks; nunca contacta al proveedor ni envía nada. Si confirmas que no se publicó nada, el trabajo seguirá detenido hasta que elijas Reintentar por separado.',
    'incidents.reconcileRemoteId': 'ID de la publicación en el proveedor (opcional, si se publicó)',
    'incidents.reconcilePublished': 'Confirmé que se publicó',
    'incidents.reconcileNotPublished': 'Confirmé que no se publicó',
    'incidents.reconcileConfirmPublished': 'Confirma que revisaste el proveedor y verificaste que esta publicación se publicó. FanThynks solo registrará el resultado y no contactará al proveedor.',
    'incidents.reconcileConfirmNotPublished': 'Confirma que revisaste el proveedor y verificaste que no se creó ninguna publicación. FanThynks solo registrará el resultado; no se enviará nada hasta que elijas Reintentar por separado.',
    'incidents.reconcilePublishedSaved': 'Resultado registrado como publicado. No se hizo ninguna solicitud al proveedor.',
    'incidents.reconcileNotPublishedSaved': 'Resultado registrado. No se envió nada; Reintentar sigue siendo una acción separada.',
    'incidents.reconcileFailed': 'No se pudo registrar el resultado del proveedor.',
    'incidents.reconcileNotConfirmed': 'No se pudo confirmar el resultado. Actualiza los incidentes antes de reintentar.',
  },
  ja: {
    'incidents.reconcileHeading': '不明な投稿結果を照合',
    'incidents.reconcileDescription': '先にプロバイダーのダッシュボードまたは API を確認してください。結果の記録で更新されるのは FanThynks のみです。プロバイダーへの連絡や送信は行いません。投稿されていないと確認した場合、再試行を別途選ぶまでジョブは停止したままです。',
    'incidents.reconcileRemoteId': 'プロバイダーの投稿 ID（公開済みの場合は任意）',
    'incidents.reconcilePublished': '投稿済みと確認しました',
    'incidents.reconcileNotPublished': '未投稿と確認しました',
    'incidents.reconcileConfirmPublished': 'プロバイダーを確認し、この投稿が公開済みであることを確認した場合のみ確定してください。FanThynks は結果を記録するだけで、プロバイダーには接続しません。',
    'incidents.reconcileConfirmNotPublished': 'プロバイダーを確認し、投稿が作成されていないことを確認した場合のみ確定してください。FanThynks は結果を記録するだけです。再試行を別途選ぶまで送信されません。',
    'incidents.reconcilePublishedSaved': '投稿済みとして記録しました。プロバイダーへのリクエストは行っていません。',
    'incidents.reconcileNotPublishedSaved': '結果を記録しました。送信は行っていません。再試行は別の操作です。',
    'incidents.reconcileFailed': 'プロバイダーの結果を記録できませんでした。',
    'incidents.reconcileNotConfirmed': '結果を確認できませんでした。再試行する前にインシデントを更新してください。',
  },
  it: {
    'incidents.reconcileHeading': 'Riconcilia un esito di pubblicazione sconosciuto',
    'incidents.reconcileDescription': 'Controlla prima il pannello o l’API del provider. Registrare un esito aggiorna solo FanThynks: non contatta il provider e non invia nulla. Se confermi che non è stato pubblicato nulla, il processo resta fermo finché non scegli separatamente Ripeti.',
    'incidents.reconcileRemoteId': 'ID del post sul provider (facoltativo, se pubblicato)',
    'incidents.reconcilePublished': 'Ho confermato la pubblicazione',
    'incidents.reconcileNotPublished': 'Ho confermato che non è stato pubblicato',
    'incidents.reconcileConfirmPublished': 'Conferma solo dopo aver verificato sul provider che il post è stato pubblicato. FanThynks registrerà l’esito senza contattare il provider.',
    'incidents.reconcileConfirmNotPublished': 'Conferma solo dopo aver verificato sul provider che non è stato creato alcun post. FanThynks registrerà l’esito; non verrà inviato nulla finché non scegli separatamente Ripeti.',
    'incidents.reconcilePublishedSaved': 'Esito registrato come pubblicato. Non è stata inviata alcuna richiesta al provider.',
    'incidents.reconcileNotPublishedSaved': 'Esito registrato. Non è stato inviato nulla; Ripeti è un’azione separata.',
    'incidents.reconcileFailed': 'Impossibile registrare l’esito del provider.',
    'incidents.reconcileNotConfirmed': 'Impossibile confermare l’esito. Aggiorna gli incidenti prima di riprovare.',
  },
  'pt-BR': {
    'incidents.reconcileHeading': 'Conferir resultado de publicação desconhecido',
    'incidents.reconcileDescription': 'Confira primeiro o painel ou a API do provedor. Registrar um resultado atualiza apenas o FanThynks; não contata o provedor nem envia nada. Se confirmar que nada foi publicado, o trabalho continuará parado até você escolher Repetir separadamente.',
    'incidents.reconcileRemoteId': 'ID da publicação no provedor (opcional, se publicada)',
    'incidents.reconcilePublished': 'Confirmei que foi publicado',
    'incidents.reconcileNotPublished': 'Confirmei que não foi publicado',
    'incidents.reconcileConfirmPublished': 'Confirme somente depois de verificar no provedor que esta publicação foi feita. O FanThynks apenas registrará o resultado e não contatará o provedor.',
    'incidents.reconcileConfirmNotPublished': 'Confirme somente depois de verificar no provedor que nenhuma publicação foi criada. O FanThynks apenas registrará o resultado; nada será enviado até você escolher Repetir separadamente.',
    'incidents.reconcilePublishedSaved': 'Resultado registrado como publicado. Nenhuma solicitação foi feita ao provedor.',
    'incidents.reconcileNotPublishedSaved': 'Resultado registrado. Nada foi enviado; Repetir continua sendo uma ação separada.',
    'incidents.reconcileFailed': 'Não foi possível registrar o resultado do provedor.',
    'incidents.reconcileNotConfirmed': 'Não foi possível confirmar o resultado. Atualize os incidentes antes de tentar novamente.',
  },
  de: {
    'incidents.reconcileHeading': 'Unbekanntes Veröffentlichungsergebnis abgleichen',
    'incidents.reconcileDescription': 'Prüfen Sie zuerst das Dashboard oder die API des Anbieters. Das Erfassen eines Ergebnisses aktualisiert nur FanThynks; es kontaktiert den Anbieter nicht und sendet nichts. Wenn Sie bestätigen, dass nichts veröffentlicht wurde, bleibt der Auftrag angehalten, bis Sie separat Wiederholen wählen.',
    'incidents.reconcileRemoteId': 'Beitrags-ID beim Anbieter (optional, falls veröffentlicht)',
    'incidents.reconcilePublished': 'Veröffentlichung bestätigt',
    'incidents.reconcileNotPublished': 'Keine Veröffentlichung bestätigt',
    'incidents.reconcileConfirmPublished': 'Bestätigen Sie nur, wenn Sie beim Anbieter geprüft haben, dass dieser Beitrag veröffentlicht wurde. FanThynks erfasst nur Ihr Ergebnis und kontaktiert den Anbieter nicht.',
    'incidents.reconcileConfirmNotPublished': 'Bestätigen Sie nur, wenn Sie beim Anbieter geprüft haben, dass kein Beitrag erstellt wurde. FanThynks erfasst nur Ihr Ergebnis; es wird nichts gesendet, bis Sie separat Wiederholen wählen.',
    'incidents.reconcilePublishedSaved': 'Ergebnis als veröffentlicht erfasst. Es wurde keine Anbieteranfrage gesendet.',
    'incidents.reconcileNotPublishedSaved': 'Ergebnis erfasst. Es wurde nichts gesendet; Wiederholen bleibt eine separate Aktion.',
    'incidents.reconcileFailed': 'Das Anbieterergebnis konnte nicht erfasst werden.',
    'incidents.reconcileNotConfirmed': 'Das Ergebnis konnte nicht bestätigt werden. Aktualisieren Sie die Vorfälle, bevor Sie es erneut versuchen.',
  },
};
