import type { Catalog, SupportedLocale } from './locale.js';

const en: Catalog = {
  'linkbio.providerSelect': 'Link-in-bio provider',
  'linkbio.profileUrl': 'Provider profile URL',
  'linkbio.accentColor': 'Page accent color',
  'linkbio.trackedLinks': 'Tracked destination links',
  'linkbio.status': 'Status do provedor',
  'linkbio.statusConfigured': 'Configured',
  'linkbio.statusConnected': 'Sync verified',
  'linkbio.statusSyncError': 'Sync failed',
  'linkbio.statusDisabled': 'Disabled',
  'linkbio.enableProvider': 'Enable provider',
  'linkbio.saveProvider': 'Save provider settings',
  'linkbio.copyPublicPage': 'Copy public page URL',
  'linkbio.copyTrackedLink': 'Copy tracked redirect',
  'linkbio.copied': 'Link copied.',
  'linkbio.externalSetup': 'Linktree and Beacons pages are managed on their own sites. Paste these AXIOM tracked redirects there, and add your GA4 measurement ID in that provider’s analytics settings.',
  'linkbio.externalProfileRequired': 'Enter the HTTPS profile URL for the selected service before saving.',
  'linkbio.error.profileUrl': 'Enter an HTTPS URL on the selected provider domain.',
  'linkbio.error.copyFailed': 'The link could not be copied. Check browser clipboard access.',
  'linkbio.ga4.title': 'Google Analytics 4 import',
  'linkbio.ga4.accessInstructions': 'Create a Google service account, grant it Viewer access to the GA4 property, and provide its JSON private key. AXIOM stores the key encrypted and uses it only for read-only reports through model egress.',
  'linkbio.ga4.measurementId': 'GA4 measurement ID',
  'linkbio.ga4.propertyId': 'GA4 property ID',
  'linkbio.ga4.clientEmail': 'Service account email',
  'linkbio.ga4.privateKey': 'Service account private key',
  'linkbio.ga4.connect': 'Save GA4 connection',
  'linkbio.ga4.disconnect': 'Remove saved credentials',
  'linkbio.ga4.disconnected': 'Saved GA4 credentials removed.',
  'linkbio.ga4.savedUnverified': 'Credentials saved. Property access is unverified until a sync succeeds.',
  'linkbio.ga4.syncSucceeded': 'GA4 sync imported {count} daily records.',
  'linkbio.ga4.startDate': 'Start date',
  'linkbio.ga4.endDate': 'End date',
  'linkbio.ga4.sync': 'Sync analytics',
  'linkbio.ga4.syncError': 'The last sync failed. Saved credentials remain available for another attempt.',
  'linkbio.ga4.neverSynced': 'not synced yet',
  'linkbio.ga4.lastSynced': 'Last successful sync: {date}',
  'linkbio.ga4.ownerRequired': 'Only an owner or manager can save or remove analytics credentials.',
  'linkbio.analytics.trackedClicks': '{count} tracked redirect clicks',
  'linkbio.analytics.visits': '{count} GA4 sessions',
  'linkbio.analytics.activeUsers': '{count} daily active users summed',
  'linkbio.analytics.importedClicks': '{count} GA4 click events',
  'linkbio.analytics.conversions': '{count} configured GA4 events',
  'linkbio.analytics.trackedClicksLabel': 'AXIOM tracked clicks',
  'linkbio.analytics.visitsLabel': 'GA4 sessions',
  'linkbio.analytics.activeUsersLabel': 'GA4 daily active users',
  'linkbio.analytics.importedClicksLabel': 'GA4 click events',
  'linkbio.analytics.conversionsLabel': 'GA4 configured events',
  'linkbio.analytics.date': 'Date',
  'linkbio.analytics.note': 'AXIOM redirect clicks and GA4 events are shown separately. Daily active users are summed across days and are not deduplicated for the full period.',
  'linkbio.analytics.noData': 'No click or GA4 records have been collected in the last 90 days.',
  'linkbio.analytics.unavailable': 'Link-in-bio analytics could not be loaded. Refresh the page to try again.',
  'linkbio.ga4.connectionUnavailable': 'GA4 connection status could not be loaded. Refresh before changing credentials.',
};

const es: Catalog = {
  'linkbio.providerSelect': 'Proveedor de enlaces de perfil',
  'linkbio.profileUrl': 'URL del perfil del proveedor',
  'linkbio.accentColor': 'Color de acento de la página',
  'linkbio.trackedLinks': 'Enlaces de destino medidos',
  'linkbio.status': 'Estado',
  'linkbio.statusConfigured': 'Configurado',
  'linkbio.statusConnected': 'Sincronización verificada',
  'linkbio.statusSyncError': 'Falló la sincronización',
  'linkbio.statusDisabled': 'Desactivado',
  'linkbio.enableProvider': 'Activar proveedor',
  'linkbio.saveProvider': 'Guardar ajustes del proveedor',
  'linkbio.copyPublicPage': 'Copiar URL de la página pública',
  'linkbio.copyTrackedLink': 'Copiar redirección medida',
  'linkbio.copied': 'Enlace copiado.',
  'linkbio.externalSetup': 'Las páginas de Linktree y Beacons se administran en sus propios sitios. Pega allí estas redirecciones de AXIOM y añade tu ID de medición de GA4 en los ajustes de análisis del proveedor.',
  'linkbio.externalProfileRequired': 'Introduce la URL HTTPS del perfil del servicio antes de guardar.',
  'linkbio.error.profileUrl': 'Introduce una URL HTTPS del dominio del proveedor seleccionado.',
  'linkbio.error.copyFailed': 'No se pudo copiar el enlace. Comprueba el acceso al portapapeles del navegador.',
  'linkbio.ga4.title': 'Importación de Google Analytics 4',
  'linkbio.ga4.accessInstructions': 'Crea una cuenta de servicio de Google, concédele acceso de lector a la propiedad de GA4 y proporciona su clave privada JSON. AXIOM cifra la clave y la usa solo para informes de solo lectura mediante la salida del modelo.',
  'linkbio.ga4.measurementId': 'ID de medición de GA4',
  'linkbio.ga4.propertyId': 'ID de propiedad de GA4',
  'linkbio.ga4.clientEmail': 'Correo de la cuenta de servicio',
  'linkbio.ga4.privateKey': 'Clave privada de la cuenta de servicio',
  'linkbio.ga4.connect': 'Guardar conexión de GA4',
  'linkbio.ga4.disconnect': 'Quitar credenciales guardadas',
  'linkbio.ga4.disconnected': 'Se quitaron las credenciales de GA4 guardadas.',
  'linkbio.ga4.savedUnverified': 'Credenciales guardadas. El acceso a la propiedad no se confirma hasta que termine una sincronización.',
  'linkbio.ga4.syncSucceeded': 'La sincronización de GA4 importó {count} registros diarios.',
  'linkbio.ga4.startDate': 'Fecha inicial',
  'linkbio.ga4.endDate': 'Fecha final',
  'linkbio.ga4.sync': 'Sincronizar análisis',
  'linkbio.ga4.syncError': 'Falló la última sincronización. Las credenciales guardadas están disponibles para otro intento.',
  'linkbio.ga4.neverSynced': 'aún sin sincronizar',
  'linkbio.ga4.lastSynced': 'Última sincronización correcta: {date}',
  'linkbio.ga4.ownerRequired': 'Solo un propietario o gerente puede guardar o quitar credenciales de análisis.',
  'linkbio.analytics.trackedClicks': '{count} clics en redirecciones medidas',
  'linkbio.analytics.visits': '{count} sesiones de GA4',
  'linkbio.analytics.activeUsers': '{count} usuarios activos diarios sumados',
  'linkbio.analytics.importedClicks': '{count} eventos de clic de GA4',
  'linkbio.analytics.conversions': '{count} eventos configurados de GA4',
  'linkbio.analytics.trackedClicksLabel': 'Clics medidos por AXIOM',
  'linkbio.analytics.visitsLabel': 'Sesiones de GA4',
  'linkbio.analytics.activeUsersLabel': 'Usuarios activos diarios de GA4',
  'linkbio.analytics.importedClicksLabel': 'Eventos de clic de GA4',
  'linkbio.analytics.conversionsLabel': 'Eventos configurados de GA4',
  'linkbio.analytics.date': 'Fecha',
  'linkbio.analytics.note': 'Los clics de redirecciones de AXIOM y los eventos de GA4 se muestran por separado. Los usuarios activos diarios se suman entre días y no se deduplican para todo el periodo.',
  'linkbio.analytics.noData': 'No se recopilaron clics ni registros de GA4 en los últimos 90 días.',
  'linkbio.analytics.unavailable': 'No se pudieron cargar los análisis de enlaces. Actualiza la página para intentarlo de nuevo.',
  'linkbio.ga4.connectionUnavailable': 'No se pudo cargar el estado de la conexión de GA4. Actualiza la página antes de cambiar las credenciales.',
};

const ja: Catalog = {
  'linkbio.providerSelect': 'リンクプロフィールのプロバイダー',
  'linkbio.profileUrl': 'プロバイダープロフィールURL',
  'linkbio.accentColor': 'ページのアクセントカラー',
  'linkbio.trackedLinks': '追跡するリンク先',
  'linkbio.status': '状態',
  'linkbio.statusConfigured': '設定済み',
  'linkbio.statusConnected': '同期を確認済み',
  'linkbio.statusSyncError': '同期に失敗',
  'linkbio.statusDisabled': '無効',
  'linkbio.enableProvider': 'プロバイダーを有効化',
  'linkbio.saveProvider': 'プロバイダー設定を保存',
  'linkbio.copyPublicPage': '公開ページURLをコピー',
  'linkbio.copyTrackedLink': '追跡リダイレクトをコピー',
  'linkbio.copied': 'リンクをコピーしました。',
  'linkbio.externalSetup': 'Linktree と Beacons のページは各サービス上で管理します。ここで作成した AXIOM の追跡リダイレクトを貼り付け、各サービスの分析設定に GA4 測定IDを追加してください。',
  'linkbio.externalProfileRequired': '保存する前に、サービスのHTTPSプロフィールURLを入力してください。',
  'linkbio.error.profileUrl': '選択したプロバイダードメイン上のHTTPS URLを入力してください。',
  'linkbio.error.copyFailed': 'リンクをコピーできませんでした。ブラウザーのクリップボードアクセスを確認してください。',
  'linkbio.ga4.title': 'Google Analytics 4 の取り込み',
  'linkbio.ga4.accessInstructions': 'Googleサービスアカウントを作成し、GA4プロパティへの閲覧者アクセスを付与して、JSON秘密鍵を入力してください。AXIOMは鍵を暗号化し、モデルのエグレス経由で読み取り専用レポートにのみ使用します。',
  'linkbio.ga4.measurementId': 'GA4測定ID',
  'linkbio.ga4.propertyId': 'GA4プロパティID',
  'linkbio.ga4.clientEmail': 'サービスアカウントのメール',
  'linkbio.ga4.privateKey': 'サービスアカウントの秘密鍵',
  'linkbio.ga4.connect': 'GA4接続を保存',
  'linkbio.ga4.disconnect': '保存済み認証情報を削除',
  'linkbio.ga4.disconnected': '保存済みのGA4認証情報を削除しました。',
  'linkbio.ga4.savedUnverified': '認証情報を保存しました。同期が成功するまでプロパティへのアクセスは未確認です。',
  'linkbio.ga4.syncSucceeded': 'GA4同期で日次レコードを {count} 件取り込みました。',
  'linkbio.ga4.startDate': '開始日',
  'linkbio.ga4.endDate': '終了日',
  'linkbio.ga4.sync': '分析を同期',
  'linkbio.ga4.syncError': '前回の同期に失敗しました。保存済み認証情報を使って再試行できます。',
  'linkbio.ga4.neverSynced': '未同期',
  'linkbio.ga4.lastSynced': '最終成功同期: {date}',
  'linkbio.ga4.ownerRequired': '分析認証情報を保存または削除できるのはオーナーかマネージャーのみです。',
  'linkbio.analytics.trackedClicks': '追跡リダイレクトのクリック {count} 件',
  'linkbio.analytics.visits': 'GA4セッション {count} 件',
  'linkbio.analytics.activeUsers': '日別アクティブユーザー合計 {count} 人',
  'linkbio.analytics.importedClicks': 'GA4クリックイベント {count} 件',
  'linkbio.analytics.conversions': '設定済みGA4イベント {count} 件',
  'linkbio.analytics.trackedClicksLabel': 'AXIOM追跡クリック',
  'linkbio.analytics.visitsLabel': 'GA4セッション',
  'linkbio.analytics.activeUsersLabel': 'GA4日別アクティブユーザー',
  'linkbio.analytics.importedClicksLabel': 'GA4クリックイベント',
  'linkbio.analytics.conversionsLabel': '設定済みGA4イベント',
  'linkbio.analytics.date': '日付',
  'linkbio.analytics.note': 'AXIOMのリダイレクトクリックとGA4イベントは別々に表示されます。日別アクティブユーザーは日ごとの合計であり、期間全体で重複排除されません。',
  'linkbio.analytics.noData': '過去90日間にクリックまたはGA4レコードは収集されていません。',
  'linkbio.analytics.unavailable': 'リンク分析を読み込めませんでした。ページを更新して再試行してください。',
  'linkbio.ga4.connectionUnavailable': 'GA4接続状態を読み込めませんでした。認証情報を変更する前にページを更新してください。',
};

const it: Catalog = {
  'linkbio.providerSelect': 'Provider del profilo link',
  'linkbio.profileUrl': 'URL del profilo del provider',
  'linkbio.accentColor': 'Colore di accento della pagina',
  'linkbio.trackedLinks': 'Link di destinazione tracciati',
  'linkbio.status': 'Stato',
  'linkbio.statusConfigured': 'Configurato',
  'linkbio.statusConnected': 'Sincronizzazione verificata',
  'linkbio.statusSyncError': 'Sincronizzazione non riuscita',
  'linkbio.statusDisabled': 'Disattivato',
  'linkbio.enableProvider': 'Attiva provider',
  'linkbio.saveProvider': 'Salva impostazioni provider',
  'linkbio.copyPublicPage': 'Copia URL della pagina pubblica',
  'linkbio.copyTrackedLink': 'Copia reindirizzamento tracciato',
  'linkbio.copied': 'Link copiato.',
  'linkbio.externalSetup': 'Le pagine Linktree e Beacons si gestiscono sui rispettivi siti. Incolla lì i reindirizzamenti tracciati AXIOM e aggiungi l’ID di misurazione GA4 nelle impostazioni analitiche del provider.',
  'linkbio.externalProfileRequired': 'Inserisci l’URL HTTPS del profilo del servizio prima di salvare.',
  'linkbio.error.profileUrl': 'Inserisci un URL HTTPS sul dominio del provider selezionato.',
  'linkbio.error.copyFailed': 'Impossibile copiare il link. Verifica l’accesso agli appunti del browser.',
  'linkbio.ga4.title': 'Importazione Google Analytics 4',
  'linkbio.ga4.accessInstructions': 'Crea un account di servizio Google, concedigli l’accesso Visualizzatore alla proprietà GA4 e fornisci la sua chiave privata JSON. AXIOM cifra la chiave e la usa solo per report in sola lettura tramite l’egress del modello.',
  'linkbio.ga4.measurementId': 'ID di misurazione GA4',
  'linkbio.ga4.propertyId': 'ID proprietà GA4',
  'linkbio.ga4.clientEmail': 'Email dell’account di servizio',
  'linkbio.ga4.privateKey': 'Chiave privata dell’account di servizio',
  'linkbio.ga4.connect': 'Salva connessione GA4',
  'linkbio.ga4.disconnect': 'Rimuovi credenziali salvate',
  'linkbio.ga4.disconnected': 'Credenziali GA4 salvate rimosse.',
  'linkbio.ga4.savedUnverified': 'Credenziali salvate. L’accesso alla proprietà non è verificato fino al successo di una sincronizzazione.',
  'linkbio.ga4.syncSucceeded': 'La sincronizzazione GA4 ha importato {count} record giornalieri.',
  'linkbio.ga4.startDate': 'Data iniziale',
  'linkbio.ga4.endDate': 'Data finale',
  'linkbio.ga4.sync': 'Sincronizza analisi',
  'linkbio.ga4.syncError': 'L’ultima sincronizzazione non è riuscita. Le credenziali salvate restano disponibili per riprovare.',
  'linkbio.ga4.neverSynced': 'mai sincronizzato',
  'linkbio.ga4.lastSynced': 'Ultima sincronizzazione riuscita: {date}',
  'linkbio.ga4.ownerRequired': 'Solo un proprietario o un manager può salvare o rimuovere credenziali analitiche.',
  'linkbio.analytics.trackedClicks': '{count} clic sui reindirizzamenti tracciati',
  'linkbio.analytics.visits': '{count} sessioni GA4',
  'linkbio.analytics.activeUsers': '{count} utenti attivi giornalieri sommati',
  'linkbio.analytics.importedClicks': '{count} eventi di clic GA4',
  'linkbio.analytics.conversions': '{count} eventi GA4 configurati',
  'linkbio.analytics.trackedClicksLabel': 'Clic tracciati AXIOM',
  'linkbio.analytics.visitsLabel': 'Sessioni GA4',
  'linkbio.analytics.activeUsersLabel': 'Utenti attivi giornalieri GA4',
  'linkbio.analytics.importedClicksLabel': 'Eventi di clic GA4',
  'linkbio.analytics.conversionsLabel': 'Eventi GA4 configurati',
  'linkbio.analytics.date': 'Data',
  'linkbio.analytics.note': 'I clic dei reindirizzamenti AXIOM e gli eventi GA4 sono mostrati separatamente. Gli utenti attivi giornalieri vengono sommati tra i giorni e non deduplicati per l’intero periodo.',
  'linkbio.analytics.noData': 'Negli ultimi 90 giorni non sono stati raccolti clic né record GA4.',
  'linkbio.analytics.unavailable': 'Impossibile caricare le analisi dei link. Aggiorna la pagina per riprovare.',
  'linkbio.ga4.connectionUnavailable': 'Impossibile caricare lo stato della connessione GA4. Aggiorna la pagina prima di cambiare le credenziali.',
};

const ptBR: Catalog = {
  'linkbio.providerSelect': 'Provedor do perfil de links',
  'linkbio.profileUrl': 'URL do perfil do provedor',
  'linkbio.accentColor': 'Cor de destaque da página',
  'linkbio.trackedLinks': 'Links de destino rastreados',
  'linkbio.status': 'Anbieterstatus',
  'linkbio.statusConfigured': 'Configurado',
  'linkbio.statusConnected': 'Sincronização verificada',
  'linkbio.statusSyncError': 'Falha na sincronização',
  'linkbio.statusDisabled': 'Desativado',
  'linkbio.enableProvider': 'Ativar provedor',
  'linkbio.saveProvider': 'Salvar configurações do provedor',
  'linkbio.copyPublicPage': 'Copiar URL da página pública',
  'linkbio.copyTrackedLink': 'Copiar redirecionamento rastreado',
  'linkbio.copied': 'Link copiado.',
  'linkbio.externalSetup': 'As páginas do Linktree e do Beacons são gerenciadas nos próprios sites. Cole lá os redirecionamentos rastreados do AXIOM e adicione seu ID de medição do GA4 nas configurações de análise do provedor.',
  'linkbio.externalProfileRequired': 'Informe a URL HTTPS do perfil do serviço antes de salvar.',
  'linkbio.error.profileUrl': 'Informe uma URL HTTPS do domínio do provedor selecionado.',
  'linkbio.error.copyFailed': 'Não foi possível copiar o link. Verifique o acesso à área de transferência do navegador.',
  'linkbio.ga4.title': 'Importação do Google Analytics 4',
  'linkbio.ga4.accessInstructions': 'Crie uma conta de serviço do Google, conceda acesso de leitor à propriedade do GA4 e informe a chave privada JSON. O AXIOM armazena a chave criptografada e a usa apenas para relatórios somente leitura pela saída de rede do modelo.',
  'linkbio.ga4.measurementId': 'ID de medição do GA4',
  'linkbio.ga4.propertyId': 'ID da propriedade do GA4',
  'linkbio.ga4.clientEmail': 'E-mail da conta de serviço',
  'linkbio.ga4.privateKey': 'Chave privada da conta de serviço',
  'linkbio.ga4.connect': 'Salvar conexão do GA4',
  'linkbio.ga4.disconnect': 'Remover credenciais salvas',
  'linkbio.ga4.disconnected': 'Credenciais salvas do GA4 removidas.',
  'linkbio.ga4.savedUnverified': 'Credenciais salvas. O acesso à propriedade não foi verificado até uma sincronização ser concluída.',
  'linkbio.ga4.syncSucceeded': 'A sincronização do GA4 importou {count} registros diários.',
  'linkbio.ga4.startDate': 'Data inicial',
  'linkbio.ga4.endDate': 'Data final',
  'linkbio.ga4.sync': 'Sincronizar análises',
  'linkbio.ga4.syncError': 'A última sincronização falhou. As credenciais salvas continuam disponíveis para outra tentativa.',
  'linkbio.ga4.neverSynced': 'ainda não sincronizado',
  'linkbio.ga4.lastSynced': 'Última sincronização bem-sucedida: {date}',
  'linkbio.ga4.ownerRequired': 'Somente proprietário ou gerente pode salvar ou remover credenciais de análise.',
  'linkbio.analytics.trackedClicks': '{count} cliques em redirecionamentos rastreados',
  'linkbio.analytics.visits': '{count} sessões do GA4',
  'linkbio.analytics.activeUsers': '{count} usuários ativos diários somados',
  'linkbio.analytics.importedClicks': '{count} eventos de clique do GA4',
  'linkbio.analytics.conversions': '{count} eventos configurados do GA4',
  'linkbio.analytics.trackedClicksLabel': 'Cliques rastreados pelo AXIOM',
  'linkbio.analytics.visitsLabel': 'Sessões do GA4',
  'linkbio.analytics.activeUsersLabel': 'Usuários ativos diários do GA4',
  'linkbio.analytics.importedClicksLabel': 'Eventos de clique do GA4',
  'linkbio.analytics.conversionsLabel': 'Eventos configurados do GA4',
  'linkbio.analytics.date': 'Data',
  'linkbio.analytics.note': 'Os cliques em redirecionamentos do AXIOM e os eventos do GA4 aparecem separadamente. Usuários ativos diários são somados entre os dias e não deduplicados no período inteiro.',
  'linkbio.analytics.noData': 'Nenhum clique ou registro do GA4 foi coletado nos últimos 90 dias.',
  'linkbio.analytics.unavailable': 'Não foi possível carregar as análises dos links. Atualize a página para tentar novamente.',
  'linkbio.ga4.connectionUnavailable': 'Não foi possível carregar o status da conexão do GA4. Atualize a página antes de alterar as credenciais.',
};

const de: Catalog = {
  'linkbio.providerSelect': 'Link-in-Bio-Anbieter',
  'linkbio.profileUrl': 'Profil-URL des Anbieters',
  'linkbio.accentColor': 'Akzentfarbe der Seite',
  'linkbio.trackedLinks': 'Nachverfolgte Ziellinks',
  'linkbio.status': 'Status',
  'linkbio.statusConfigured': 'Konfiguriert',
  'linkbio.statusConnected': 'Synchronisierung bestätigt',
  'linkbio.statusSyncError': 'Synchronisierung fehlgeschlagen',
  'linkbio.statusDisabled': 'Deaktiviert',
  'linkbio.enableProvider': 'Anbieter aktivieren',
  'linkbio.saveProvider': 'Anbietereinstellungen speichern',
  'linkbio.copyPublicPage': 'URL der öffentlichen Seite kopieren',
  'linkbio.copyTrackedLink': 'Nachverfolgte Weiterleitung kopieren',
  'linkbio.copied': 'Link kopiert.',
  'linkbio.externalSetup': 'Linktree- und Beacons-Seiten werden auf den jeweiligen Websites verwaltet. Füge dort diese AXIOM-Weiterleitungen ein und trage die GA4-Mess-ID in den Analyse-Einstellungen des Anbieters ein.',
  'linkbio.externalProfileRequired': 'Gib vor dem Speichern die HTTPS-Profil-URL des Dienstes ein.',
  'linkbio.error.profileUrl': 'Gib eine HTTPS-URL auf der Domain des ausgewählten Anbieters ein.',
  'linkbio.error.copyFailed': 'Der Link konnte nicht kopiert werden. Prüfe den Zwischenablagezugriff des Browsers.',
  'linkbio.ga4.title': 'Google-Analytics-4-Import',
  'linkbio.ga4.accessInstructions': 'Erstelle ein Google-Dienstkonto, gewähre ihm Betrachterzugriff auf die GA4-Property und gib seinen JSON-Privatschlüssel ein. AXIOM speichert den Schlüssel verschlüsselt und verwendet ihn nur für schreibgeschützte Berichte über den Modell-Egress.',
  'linkbio.ga4.measurementId': 'GA4-Mess-ID',
  'linkbio.ga4.propertyId': 'GA4-Property-ID',
  'linkbio.ga4.clientEmail': 'E-Mail des Dienstkontos',
  'linkbio.ga4.privateKey': 'Privatschlüssel des Dienstkontos',
  'linkbio.ga4.connect': 'GA4-Verbindung speichern',
  'linkbio.ga4.disconnect': 'Gespeicherte Zugangsdaten entfernen',
  'linkbio.ga4.disconnected': 'Gespeicherte GA4-Zugangsdaten entfernt.',
  'linkbio.ga4.savedUnverified': 'Zugangsdaten gespeichert. Der Zugriff auf die Property ist erst nach erfolgreicher Synchronisierung bestätigt.',
  'linkbio.ga4.syncSucceeded': 'Der GA4-Abgleich hat {count} Tagesdatensätze importiert.',
  'linkbio.ga4.startDate': 'Startdatum',
  'linkbio.ga4.endDate': 'Enddatum',
  'linkbio.ga4.sync': 'Analysen synchronisieren',
  'linkbio.ga4.syncError': 'Die letzte Synchronisierung ist fehlgeschlagen. Die gespeicherten Zugangsdaten bleiben für einen neuen Versuch erhalten.',
  'linkbio.ga4.neverSynced': 'noch nicht synchronisiert',
  'linkbio.ga4.lastSynced': 'Letzte erfolgreiche Synchronisierung: {date}',
  'linkbio.ga4.ownerRequired': 'Nur Eigentümer oder Manager dürfen Analyse-Zugangsdaten speichern oder entfernen.',
  'linkbio.analytics.trackedClicks': '{count} Klicks auf nachverfolgte Weiterleitungen',
  'linkbio.analytics.visits': '{count} GA4-Sitzungen',
  'linkbio.analytics.activeUsers': '{count} tägliche aktive Nutzer summiert',
  'linkbio.analytics.importedClicks': '{count} GA4-Klickereignisse',
  'linkbio.analytics.conversions': '{count} konfigurierte GA4-Ereignisse',
  'linkbio.analytics.trackedClicksLabel': 'Von AXIOM nachverfolgte Klicks',
  'linkbio.analytics.visitsLabel': 'GA4-Sitzungen',
  'linkbio.analytics.activeUsersLabel': 'Tägliche GA4-Nutzer',
  'linkbio.analytics.importedClicksLabel': 'GA4-Klickereignisse',
  'linkbio.analytics.conversionsLabel': 'Konfigurierte GA4-Ereignisse',
  'linkbio.analytics.date': 'Datum',
  'linkbio.analytics.note': 'AXIOM-Weiterleitungsklicks und GA4-Ereignisse werden getrennt angezeigt. Tägliche aktive Nutzer werden über die Tage summiert und für den gesamten Zeitraum nicht dedupliziert.',
  'linkbio.analytics.noData': 'In den letzten 90 Tagen wurden keine Klicks oder GA4-Datensätze erfasst.',
  'linkbio.analytics.unavailable': 'Link-Analysen konnten nicht geladen werden. Aktualisiere die Seite, um es erneut zu versuchen.',
  'linkbio.ga4.connectionUnavailable': 'Der Status der GA4-Verbindung konnte nicht geladen werden. Aktualisiere die Seite, bevor du Zugangsdaten änderst.',
};

export const LINKBIO_PROVIDER_ANALYTICS_CATALOGS: Record<SupportedLocale, Catalog> = {
  en, es, ja, it, 'pt-BR': ptBR, de,
};
export const LINKBIO_PROVIDER_ANALYTICS_MESSAGE_KEYS = Object.keys(en) as Array<keyof typeof en>;
