import type { Catalog, SupportedLocale } from './locale.js';

/** Feature-owned copy for the remaining mounted model workspace surfaces. */
export const MODEL_SURFACE_MESSAGE_KEYS = [
  'modelSurface.linkbioTitle',
  'modelSurface.providers',
  'modelSurface.noProvider',
  'modelSurface.activeProviders',
  'modelSurface.primaryProvider',
  'modelSurface.publicPage',
  'modelSurface.externalAdaptersUnavailable',
  'modelSurface.clickAnalytics',
  'modelSurface.totalClicks',
  'modelSurface.target',
  'modelSurface.clicks',
  'modelSurface.fanvueAttribution',
  'modelSurface.revenueFacts',
  'modelSurface.trackedClicks',
  'modelSurface.attributedConversions',
  'modelSurface.unattributedConversions',
  'modelSurface.attributedRevenue',
  'modelSurface.clickToConversion',
  'modelSurface.shortLink',
  'modelSurface.conversions',
  'modelSurface.revenue',
  'modelSurface.campaignCosts',
  'modelSurface.selectShortLink',
  'modelSurface.costAmount',
  'modelSurface.costCurrency',
  'modelSurface.recordSpend',
  'modelSurface.spendRecorded',
  'modelSurface.spendSaveFailed',
  'modelSurface.roi',
  'modelSurface.netRoiByCurrency',
  'modelSurface.spend',
  'modelSurface.churnTitle',
  'modelSurface.churnDescription',
  'modelSurface.churnLoadFailed',
  'modelSurface.churnEmpty',
  'modelSurface.churnReady',
  'modelSurface.churnSending',
  'modelSurface.churnSent',
  'modelSurface.churnUnknown',
  'modelSurface.churnMessage',
  'modelSurface.churnOffer',
  'modelSurface.churnSend',
  'modelSurface.churnSentNotice',
  'modelSurface.churnUnknownNotice',
  'modelSurface.moderationTitle',
  'modelSurface.moderationDescription',
  'modelSurface.moderationName',
  'modelSurface.moderationPlatform',
  'modelSurface.moderationKeywords',
  'modelSurface.moderationAction',
  'modelSurface.moderationHide',
  'modelSurface.moderationHideBlock',
  'modelSurface.moderationCreateRule',
  'modelSurface.moderationPostId',
  'modelSurface.moderationScan',
  'modelSurface.moderationNextPage',
  'modelSurface.moderationMorePages',
  'modelSurface.moderationHistory',
  'modelSurface.moderationEmpty',
  'modelSurface.moderationLoadFailed',
  'modelSurface.moderationSaveFailed',
  'modelSurface.moderationScanResult',
  'modelSurface.moderationUnsupportedRules',
  'modelSurface.moderationNoConnections',
  'modelSurface.moderationEnabled',
  'modelSurface.moderationEnable',
  'modelSurface.moderationDisable',
  'modelSurface.moderationDelete',
  'modelSurface.moderationPending',
  'modelSurface.moderationApplied',
  'modelSurface.moderationPartial',
  'modelSurface.moderationUnknown',
  'modelSurface.moderationUnsupported',
  'modelSurface.fanvueWebhookUrl',
  'modelSurface.fanvueWebhookMissing',
  'modelSurface.generationAccessUnavailable',
  'modelSurface.generationRoleDenied',
  'modelSurface.backToWorkspace',
  'modelSurface.loadingEarnings',
  'modelSurface.loadingEarningsDescription',
  'modelSurface.loadingInbox',
  'modelSurface.loadingInboxDescription',
  'modelSurface.talentPortfolio',
  'modelSurface.talentWorkspace',
  'modelSurface.active',
  'modelSurface.inactive',
] as const;

export type ModelSurfaceMessageKey = (typeof MODEL_SURFACE_MESSAGE_KEYS)[number];

const en: Record<ModelSurfaceMessageKey, string> = {
  'modelSurface.linkbioTitle': 'Link in bio',
  'modelSurface.providers': 'Providers',
  'modelSurface.noProvider': 'No provider enabled. The native page requires nothing external — enable it to serve a first-party link page.',
  'modelSurface.activeProviders': '{count} active provider(s)',
  'modelSurface.primaryProvider': ' — primary: {kind}',
  'modelSurface.publicPage': 'Public page:',
  'modelSurface.externalAdaptersUnavailable': 'External Linktree, Beacons, and Fanlynks adapters are not available in this release.',
  'modelSurface.clickAnalytics': 'Click analytics',
  'modelSurface.totalClicks': 'Total clicks: {count}',
  'modelSurface.target': 'Target',
  'modelSurface.clicks': 'Clicks',
  'modelSurface.fanvueAttribution': 'Fanvue attribution',
  'modelSurface.revenueFacts': 'Revenue facts come from Fanvue events. ROI is calculated only where revenue and recorded spend use the same currency.',
  'modelSurface.trackedClicks': '{count} tracked clicks',
  'modelSurface.attributedConversions': '{count} attributed conversions',
  'modelSurface.unattributedConversions': '{count} unattributed conversions',
  'modelSurface.attributedRevenue': '{amount} attributed revenue',
  'modelSurface.clickToConversion': '{rate} click-to-conversion',
  'modelSurface.shortLink': 'Short link',
  'modelSurface.conversions': 'Conversions',
  'modelSurface.revenue': 'Revenue',
  'modelSurface.campaignCosts': 'Campaign costs',
  'modelSurface.selectShortLink': 'Short link',
  'modelSurface.costAmount': 'Amount in minor currency units',
  'modelSurface.costCurrency': 'Currency',
  'modelSurface.recordSpend': 'Record spend',
  'modelSurface.spendRecorded': 'Campaign spend recorded.',
  'modelSurface.spendSaveFailed': 'Campaign spend could not be confirmed. Retry to reconcile the same event.',
  'modelSurface.roi': 'Net ROI',
  'modelSurface.netRoiByCurrency': 'Net ROI by currency: {amount}',
  'modelSurface.spend': 'Spend',
  'modelSurface.churnTitle': 'Subscription recovery',
  'modelSurface.churnDescription': 'Signed Fanvue expiration events create reviewable candidates. Write the message and offer, then send once. Uncertain outcomes cannot be retried automatically.',
  'modelSurface.churnLoadFailed': 'Subscription recovery history could not be loaded.',
  'modelSurface.churnEmpty': 'No deactivated subscriptions have arrived.',
  'modelSurface.churnReady': 'Ready for review',
  'modelSurface.churnSending': 'Send in progress — check Fanvue before taking action.',
  'modelSurface.churnSent': 'Message accepted by Fanvue',
  'modelSurface.churnUnknown': 'Outcome uncertain — reconcile in Fanvue; do not resend.',
  'modelSurface.churnMessage': 'Message',
  'modelSurface.churnOffer': 'Offer or discount details',
  'modelSurface.churnSend': 'Send recovery message',
  'modelSurface.churnSentNotice': 'Fanvue accepted the recovery message.',
  'modelSurface.churnUnknownNotice': 'Fanvue may have received this message. Reconcile it in Fanvue; the system will not resend it.',
  'modelSurface.moderationTitle': 'Keyword comment moderation',
  'modelSurface.moderationDescription': 'Create literal keyword rules, then scan a provider post. Only providers and actions granted to the connected account are available. Comment text is never retained.',
  'modelSurface.moderationName': 'Rule name',
  'modelSurface.moderationPlatform': 'Provider',
  'modelSurface.moderationKeywords': 'Keywords (one per line)',
  'modelSurface.moderationAction': 'Action',
  'modelSurface.moderationHide': 'Hide matching comments',
  'modelSurface.moderationHideBlock': 'Hide and block commenter (when supported)',
  'modelSurface.moderationCreateRule': 'Create rule',
  'modelSurface.moderationPostId': 'Provider post ID',
  'modelSurface.moderationScan': 'Scan post comments',
  'modelSurface.moderationNextPage': 'Scan next page',
  'modelSurface.moderationMorePages': 'More comments are available. Continue with the next page.',
  'modelSurface.moderationHistory': 'Recent moderation actions',
  'modelSurface.moderationEmpty': 'No moderation rules or actions yet.',
  'modelSurface.moderationLoadFailed': 'Moderation settings could not be loaded.',
  'modelSurface.moderationSaveFailed': 'The moderation change could not be confirmed.',
  'modelSurface.moderationScanResult': 'Scanned {scanned}; matched {matched}; applied {moderated}; partial {partial}; uncertain {unknown}; already recorded {alreadyRecorded}.',
  'modelSurface.moderationUnsupportedRules': 'Some rules were skipped because this connection does not support their actions.',
  'modelSurface.moderationNoConnections': 'Connect an account with comment read and moderation permissions to use scanning.',
  'modelSurface.moderationEnabled': 'Enabled',
  'modelSurface.moderationEnable': 'Enable rule',
  'modelSurface.moderationDisable': 'Disable rule',
  'modelSurface.moderationDelete': 'Delete rule',
  'modelSurface.moderationPending': 'Pending or interrupted',
  'modelSurface.moderationApplied': 'Applied',
  'modelSurface.moderationPartial': 'Hide applied; block was not confirmed',
  'modelSurface.moderationUnknown': 'Outcome uncertain; check the provider',
  'modelSurface.moderationUnsupported': 'Unsupported',
  'modelSurface.fanvueWebhookUrl': 'Webhook endpoint',
  'modelSurface.fanvueWebhookMissing': 'FANVUE_WEBHOOK_SECRET is not configured, so incoming events are disabled.',
  'modelSurface.generationAccessUnavailable': 'Generation access unavailable',
  'modelSurface.generationRoleDenied': 'Your role does not allow creating or uploading media.',
  'modelSurface.backToWorkspace': 'Back to workspace',
  'modelSurface.loadingEarnings': 'Loading earnings',
  'modelSurface.loadingEarningsDescription': 'Checking account access and the requested financial records. Nothing is being published or withdrawn.',
  'modelSurface.loadingInbox': 'Loading inbox',
  'modelSurface.loadingInboxDescription': 'Checking access and retrieving the requested page. No messages are being sent or marked read.',
  'modelSurface.talentPortfolio': 'Talent portfolio',
  'modelSurface.talentWorkspace': 'Talent workspace',
  'modelSurface.active': 'Active',
  'modelSurface.inactive': 'Inactive',
};

const es: Record<ModelSurfaceMessageKey, string> = {
  'modelSurface.linkbioTitle': 'Enlace en la biografía',
  'modelSurface.providers': 'Proveedores',
  'modelSurface.noProvider': 'No hay ningún proveedor activado. La página nativa no requiere nada externo; actívala para servir una página de enlaces propia.',
  'modelSurface.activeProviders': '{count} proveedor(es) activo(s)',
  'modelSurface.primaryProvider': ' — principal: {kind}',
  'modelSurface.publicPage': 'Página pública:',
  'modelSurface.externalAdaptersUnavailable': 'Los adaptadores externos de Linktree, Beacons y Fanlynks no están disponibles en esta versión.',
  'modelSurface.clickAnalytics': 'Analítica de clics',
  'modelSurface.totalClicks': 'Clics totales: {count}',
  'modelSurface.target': 'Destino',
  'modelSurface.clicks': 'Clics',
  'modelSurface.fanvueAttribution': 'Atribución de Fanvue',
  'modelSurface.revenueFacts': 'Los ingresos provienen de eventos de Fanvue. El ROI solo se calcula cuando ingresos y gastos usan la misma moneda.',
  'modelSurface.trackedClicks': '{count} clics registrados',
  'modelSurface.attributedConversions': '{count} conversiones atribuidas',
  'modelSurface.unattributedConversions': '{count} conversiones no atribuidas',
  'modelSurface.attributedRevenue': '{amount} de ingresos atribuidos',
  'modelSurface.clickToConversion': '{rate} de clics a conversiones',
  'modelSurface.shortLink': 'Enlace corto',
  'modelSurface.conversions': 'Conversiones',
  'modelSurface.revenue': 'Ingresos',
  'modelSurface.campaignCosts': 'Costes de campaña',
  'modelSurface.selectShortLink': 'Enlace corto',
  'modelSurface.costAmount': 'Importe en unidades monetarias menores',
  'modelSurface.costCurrency': 'Moneda',
  'modelSurface.recordSpend': 'Registrar gasto',
  'modelSurface.spendRecorded': 'Gasto de campaña registrado.',
  'modelSurface.spendSaveFailed': 'No se pudo confirmar el gasto. Reintenta para reconciliar el mismo evento.',
  'modelSurface.roi': 'ROI neto',
  'modelSurface.netRoiByCurrency': 'ROI neto por moneda: {amount}',
  'modelSurface.spend': 'Gasto',
  'modelSurface.churnTitle': 'Recuperación de suscripciones',
  'modelSurface.churnDescription': 'Los eventos de expiración firmados de Fanvue crean casos revisables. Escribe el mensaje y la oferta, y envíalo una vez. Los resultados inciertos no se reintentan automáticamente.',
  'modelSurface.churnLoadFailed': 'No se pudo cargar el historial de recuperación.',
  'modelSurface.churnEmpty': 'No han llegado suscripciones desactivadas.',
  'modelSurface.churnReady': 'Listo para revisar',
  'modelSurface.churnSending': 'Envío en curso; comprueba Fanvue antes de actuar.',
  'modelSurface.churnSent': 'Fanvue aceptó el mensaje',
  'modelSurface.churnUnknown': 'Resultado incierto; reconcilia en Fanvue y no lo reenvíes.',
  'modelSurface.churnMessage': 'Mensaje',
  'modelSurface.churnOffer': 'Detalles de oferta o descuento',
  'modelSurface.churnSend': 'Enviar mensaje de recuperación',
  'modelSurface.churnSentNotice': 'Fanvue aceptó el mensaje de recuperación.',
  'modelSurface.churnUnknownNotice': 'Fanvue podría haber recibido el mensaje. Reconcilia en Fanvue; el sistema no lo reenviará.',
  'modelSurface.moderationTitle': 'Moderación de comentarios por palabras clave',
  'modelSurface.moderationDescription': 'Crea reglas literales por palabra clave y analiza una publicación del proveedor. Solo están disponibles los proveedores y acciones permitidos por la cuenta conectada. No se conserva el texto de los comentarios.',
  'modelSurface.moderationName': 'Nombre de la regla',
  'modelSurface.moderationPlatform': 'Proveedor',
  'modelSurface.moderationKeywords': 'Palabras clave (una por línea)',
  'modelSurface.moderationAction': 'Acción',
  'modelSurface.moderationHide': 'Ocultar comentarios coincidentes',
  'modelSurface.moderationHideBlock': 'Ocultar y bloquear al comentarista (si se admite)',
  'modelSurface.moderationCreateRule': 'Crear regla',
  'modelSurface.moderationPostId': 'ID de publicación del proveedor',
  'modelSurface.moderationScan': 'Analizar comentarios',
  'modelSurface.moderationNextPage': 'Analizar página siguiente',
  'modelSurface.moderationMorePages': 'Hay más comentarios. Continúa con la página siguiente.',
  'modelSurface.moderationHistory': 'Acciones de moderación recientes',
  'modelSurface.moderationEmpty': 'Aún no hay reglas ni acciones de moderación.',
  'modelSurface.moderationLoadFailed': 'No se pudieron cargar los ajustes de moderación.',
  'modelSurface.moderationSaveFailed': 'No se pudo confirmar el cambio de moderación.',
  'modelSurface.moderationScanResult': 'Analizados {scanned}; coincidencias {matched}; aplicados {moderated}; parciales {partial}; inciertos {unknown}; ya registrados {alreadyRecorded}.',
  'modelSurface.moderationUnsupportedRules': 'Se omitieron algunas reglas porque esta conexión no admite sus acciones.',
  'modelSurface.moderationNoConnections': 'Conecta una cuenta con permisos para leer y moderar comentarios.',
  'modelSurface.moderationEnabled': 'Activada',
  'modelSurface.moderationEnable': 'Activar regla',
  'modelSurface.moderationDisable': 'Desactivar regla',
  'modelSurface.moderationDelete': 'Eliminar regla',
  'modelSurface.moderationPending': 'Pendiente o interrumpida',
  'modelSurface.moderationApplied': 'Aplicada',
  'modelSurface.moderationPartial': 'Se confirmó ocultar, pero no bloquear',
  'modelSurface.moderationUnknown': 'Resultado incierto; compruébalo en el proveedor',
  'modelSurface.moderationUnsupported': 'No compatible',
  'modelSurface.fanvueWebhookUrl': 'Endpoint del webhook',
  'modelSurface.fanvueWebhookMissing': 'FANVUE_WEBHOOK_SECRET no está configurado; los eventos entrantes están desactivados.',
  'modelSurface.generationAccessUnavailable': 'El acceso a la generación no está disponible',
  'modelSurface.generationRoleDenied': 'Tu rol no permite crear ni subir medios.',
  'modelSurface.backToWorkspace': 'Volver al espacio de trabajo',
  'modelSurface.loadingEarnings': 'Cargando ingresos',
  'modelSurface.loadingEarningsDescription': 'Comprobando el acceso a la cuenta y los registros financieros solicitados. No se publica ni retira nada.',
  'modelSurface.loadingInbox': 'Cargando bandeja de entrada',
  'modelSurface.loadingInboxDescription': 'Comprobando el acceso y recuperando la página solicitada. No se envían mensajes ni se marcan como leídos.',
  'modelSurface.talentPortfolio': 'Portafolio del talento',
  'modelSurface.talentWorkspace': 'Espacio de trabajo del talento',
  'modelSurface.active': 'Activo',
  'modelSurface.inactive': 'Inactivo',
};

const ja: Record<ModelSurfaceMessageKey, string> = {
  'modelSurface.linkbioTitle': 'プロフィールリンク',
  'modelSurface.providers': 'プロバイダー',
  'modelSurface.noProvider': '有効なプロバイダーはありません。ネイティブページに外部サービスは不要です。有効にすると自前のリンクページを提供できます。',
  'modelSurface.activeProviders': '有効なプロバイダー {count} 件',
  'modelSurface.primaryProvider': ' — 主要: {kind}',
  'modelSurface.publicPage': '公開ページ:',
  'modelSurface.externalAdaptersUnavailable': 'このリリースでは外部のLinktree、Beacons、Fanlynksアダプターを利用できません。',
  'modelSurface.clickAnalytics': 'クリック分析',
  'modelSurface.totalClicks': '合計クリック数: {count}',
  'modelSurface.target': 'リンク先',
  'modelSurface.clicks': 'クリック数',
  'modelSurface.fanvueAttribution': 'Fanvueのアトリビューション',
  'modelSurface.revenueFacts': '収益はFanvueイベントから取得します。収益と記録済み支出の通貨が一致する場合にROIを計算します。',
  'modelSurface.trackedClicks': '記録済みクリック {count} 件',
  'modelSurface.attributedConversions': '帰属コンバージョン {count} 件',
  'modelSurface.unattributedConversions': '未帰属コンバージョン {count} 件',
  'modelSurface.attributedRevenue': '帰属収益 {amount}',
  'modelSurface.clickToConversion': 'クリックからコンバージョン: {rate}',
  'modelSurface.shortLink': '短縮リンク',
  'modelSurface.conversions': 'コンバージョン',
  'modelSurface.revenue': '収益',
  'modelSurface.campaignCosts': 'キャンペーン費用',
  'modelSurface.selectShortLink': '短縮リンク',
  'modelSurface.costAmount': '最小通貨単位の金額',
  'modelSurface.costCurrency': '通貨',
  'modelSurface.recordSpend': '支出を記録',
  'modelSurface.spendRecorded': 'キャンペーン支出を記録しました。',
  'modelSurface.spendSaveFailed': '支出を確認できませんでした。同じイベントを再試行して照合してください。',
  'modelSurface.roi': '純ROI',
  'modelSurface.netRoiByCurrency': '通貨別の純ROI：{amount}',
  'modelSurface.spend': '支出',
  'modelSurface.churnTitle': 'サブスクリプションの再獲得',
  'modelSurface.churnDescription': 'Fanvueの署名付き解約イベントから確認用候補を作成します。メッセージとオファーを作成して一度だけ送信します。不明な結果は自動再送しません。',
  'modelSurface.churnLoadFailed': '再獲得履歴を読み込めませんでした。',
  'modelSurface.churnEmpty': '無効化されたサブスクリプションはありません。',
  'modelSurface.churnReady': '確認待ち',
  'modelSurface.churnSending': '送信中です。次の操作の前にFanvueを確認してください。',
  'modelSurface.churnSent': 'Fanvueがメッセージを受け付けました',
  'modelSurface.churnUnknown': '結果不明です。Fanvueで照合し、再送しないでください。',
  'modelSurface.churnMessage': 'メッセージ',
  'modelSurface.churnOffer': 'オファーまたは割引の詳細',
  'modelSurface.churnSend': '再獲得メッセージを送信',
  'modelSurface.churnSentNotice': 'Fanvueが再獲得メッセージを受け付けました。',
  'modelSurface.churnUnknownNotice': 'Fanvueがメッセージを受け付けた可能性があります。Fanvueで照合してください。再送しません。',
  'modelSurface.moderationTitle': 'キーワードコメントモデレーション',
  'modelSurface.moderationDescription': 'キーワードの完全一致ルールを作成し、プロバイダーの投稿をスキャンします。接続アカウントで許可されたプロバイダーと操作だけを利用できます。コメント本文は保存しません。',
  'modelSurface.moderationName': 'ルール名',
  'modelSurface.moderationPlatform': 'プロバイダー',
  'modelSurface.moderationKeywords': 'キーワード（1行に1つ）',
  'modelSurface.moderationAction': '操作',
  'modelSurface.moderationHide': '一致するコメントを非表示',
  'modelSurface.moderationHideBlock': '投稿者を非表示にしてブロック（対応時）',
  'modelSurface.moderationCreateRule': 'ルールを作成',
  'modelSurface.moderationPostId': 'プロバイダー投稿ID',
  'modelSurface.moderationScan': '投稿コメントをスキャン',
  'modelSurface.moderationNextPage': '次のページをスキャン',
  'modelSurface.moderationMorePages': 'さらにコメントがあります。次のページを続けてください。',
  'modelSurface.moderationHistory': '最近のモデレーション操作',
  'modelSurface.moderationEmpty': 'モデレーションルールや操作はまだありません。',
  'modelSurface.moderationLoadFailed': 'モデレーション設定を読み込めませんでした。',
  'modelSurface.moderationSaveFailed': 'モデレーションの変更を確認できませんでした。',
  'modelSurface.moderationScanResult': 'スキャン {scanned} 件、一致 {matched} 件、適用 {moderated} 件、一部適用 {partial} 件、不明 {unknown} 件、記録済み {alreadyRecorded} 件。',
  'modelSurface.moderationUnsupportedRules': 'この接続で操作がサポートされないルールはスキップしました。',
  'modelSurface.moderationNoConnections': 'コメントの読み取りとモデレーション権限を持つアカウントを接続してください。',
  'modelSurface.moderationEnabled': '有効',
  'modelSurface.moderationEnable': 'ルールを有効化',
  'modelSurface.moderationDisable': 'ルールを無効化',
  'modelSurface.moderationDelete': 'ルールを削除',
  'modelSurface.moderationPending': '保留中または中断',
  'modelSurface.moderationApplied': '適用済み',
  'modelSurface.moderationPartial': '非表示は適用済み、ブロックは未確認',
  'modelSurface.moderationUnknown': '結果不明。プロバイダーを確認してください',
  'modelSurface.moderationUnsupported': '非対応',
  'modelSurface.fanvueWebhookUrl': 'Webhookエンドポイント',
  'modelSurface.fanvueWebhookMissing': 'FANVUE_WEBHOOK_SECRETが未設定のため、受信イベントは無効です。',
  'modelSurface.generationAccessUnavailable': '生成機能を利用できません',
  'modelSurface.generationRoleDenied': '現在のロールではメディアの作成やアップロードはできません。',
  'modelSurface.backToWorkspace': 'ワークスペースに戻る',
  'modelSurface.loadingEarnings': '収益を読み込み中',
  'modelSurface.loadingEarningsDescription': 'アカウントアクセスと要求された財務記録を確認しています。公開や出金は行われません。',
  'modelSurface.loadingInbox': '受信トレイを読み込み中',
  'modelSurface.loadingInboxDescription': 'アクセスを確認し、要求されたページを取得しています。メッセージの送信や既読化は行われません。',
  'modelSurface.talentPortfolio': 'タレントポートフォリオ',
  'modelSurface.talentWorkspace': 'タレントワークスペース',
  'modelSurface.active': '有効',
  'modelSurface.inactive': '無効',
};

const it: Record<ModelSurfaceMessageKey, string> = {
  'modelSurface.linkbioTitle': 'Link nella bio',
  'modelSurface.providers': 'Provider',
  'modelSurface.noProvider': 'Nessun provider è attivo. La pagina nativa non richiede servizi esterni: attivala per offrire una pagina di link proprietaria.',
  'modelSurface.activeProviders': '{count} provider attivi',
  'modelSurface.primaryProvider': ' — principale: {kind}',
  'modelSurface.publicPage': 'Pagina pubblica:',
  'modelSurface.externalAdaptersUnavailable': 'Gli adattatori esterni Linktree, Beacons e Fanlynks non sono disponibili in questa versione.',
  'modelSurface.clickAnalytics': 'Analisi dei clic',
  'modelSurface.totalClicks': 'Clic totali: {count}',
  'modelSurface.target': 'Destinazione',
  'modelSurface.clicks': 'Clic',
  'modelSurface.fanvueAttribution': 'Attribuzione Fanvue',
  'modelSurface.revenueFacts': 'I ricavi provengono dagli eventi Fanvue. Il ROI viene calcolato solo quando ricavi e spese registrate usano la stessa valuta.',
  'modelSurface.trackedClicks': '{count} clic tracciati',
  'modelSurface.attributedConversions': '{count} conversioni attribuite',
  'modelSurface.unattributedConversions': '{count} conversioni non attribuite',
  'modelSurface.attributedRevenue': '{amount} di ricavi attribuiti',
  'modelSurface.clickToConversion': '{rate} da clic a conversione',
  'modelSurface.shortLink': 'Link breve',
  'modelSurface.conversions': 'Conversioni',
  'modelSurface.revenue': 'Ricavi',
  'modelSurface.campaignCosts': 'Costi della campagna',
  'modelSurface.selectShortLink': 'Link breve',
  'modelSurface.costAmount': 'Importo in unità monetarie minori',
  'modelSurface.costCurrency': 'Valuta',
  'modelSurface.recordSpend': 'Registra spesa',
  'modelSurface.spendRecorded': 'Spesa della campagna registrata.',
  'modelSurface.spendSaveFailed': 'Impossibile confermare la spesa. Riprova per riconciliare lo stesso evento.',
  'modelSurface.roi': 'ROI netto',
  'modelSurface.netRoiByCurrency': 'ROI netto per valuta: {amount}',
  'modelSurface.spend': 'Spesa',
  'modelSurface.churnTitle': 'Recupero degli abbonamenti',
  'modelSurface.churnDescription': 'Gli eventi firmati di scadenza Fanvue creano casi da rivedere. Scrivi il messaggio e l’offerta, quindi invialo una volta. Gli esiti incerti non vengono ritentati automaticamente.',
  'modelSurface.churnLoadFailed': 'Impossibile caricare la cronologia di recupero.',
  'modelSurface.churnEmpty': 'Non sono arrivati abbonamenti disattivati.',
  'modelSurface.churnReady': 'Pronto per la revisione',
  'modelSurface.churnSending': 'Invio in corso: controlla Fanvue prima di agire.',
  'modelSurface.churnSent': 'Messaggio accettato da Fanvue',
  'modelSurface.churnUnknown': 'Esito incerto: riconcilia in Fanvue e non inviare di nuovo.',
  'modelSurface.churnMessage': 'Messaggio',
  'modelSurface.churnOffer': 'Dettagli dell’offerta o dello sconto',
  'modelSurface.churnSend': 'Invia messaggio di recupero',
  'modelSurface.churnSentNotice': 'Fanvue ha accettato il messaggio di recupero.',
  'modelSurface.churnUnknownNotice': 'Fanvue potrebbe aver ricevuto il messaggio. Riconcilia in Fanvue; il sistema non lo invierà di nuovo.',
  'modelSurface.moderationTitle': 'Moderazione commenti per parole chiave',
  'modelSurface.moderationDescription': 'Crea regole letterali per parole chiave e scansiona un post del provider. Sono disponibili solo provider e azioni consentiti dall’account collegato. Il testo dei commenti non viene conservato.',
  'modelSurface.moderationName': 'Nome regola',
  'modelSurface.moderationPlatform': 'Piattaforma',
  'modelSurface.moderationKeywords': 'Parole chiave (una per riga)',
  'modelSurface.moderationAction': 'Azione',
  'modelSurface.moderationHide': 'Nascondi i commenti corrispondenti',
  'modelSurface.moderationHideBlock': 'Nascondi e blocca il commentatore (se supportato)',
  'modelSurface.moderationCreateRule': 'Crea regola',
  'modelSurface.moderationPostId': 'ID post del provider',
  'modelSurface.moderationScan': 'Scansiona i commenti del post',
  'modelSurface.moderationNextPage': 'Scansiona la pagina successiva',
  'modelSurface.moderationMorePages': 'Sono disponibili altri commenti. Continua con la pagina successiva.',
  'modelSurface.moderationHistory': 'Azioni di moderazione recenti',
  'modelSurface.moderationEmpty': 'Non ci sono ancora regole o azioni di moderazione.',
  'modelSurface.moderationLoadFailed': 'Impossibile caricare le impostazioni di moderazione.',
  'modelSurface.moderationSaveFailed': 'Impossibile confermare la modifica della moderazione.',
  'modelSurface.moderationScanResult': 'Scansionati {scanned}; corrispondenze {matched}; applicati {moderated}; parziali {partial}; incerti {unknown}; già registrati {alreadyRecorded}.',
  'modelSurface.moderationUnsupportedRules': 'Alcune regole sono state ignorate perché questa connessione non supporta le relative azioni.',
  'modelSurface.moderationNoConnections': 'Collega un account con permessi di lettura e moderazione dei commenti.',
  'modelSurface.moderationEnabled': 'Attiva',
  'modelSurface.moderationEnable': 'Attiva regola',
  'modelSurface.moderationDisable': 'Disattiva regola',
  'modelSurface.moderationDelete': 'Elimina regola',
  'modelSurface.moderationPending': 'In attesa o interrotta',
  'modelSurface.moderationApplied': 'Applicata',
  'modelSurface.moderationPartial': 'Nascondi applicato; blocco non confermato',
  'modelSurface.moderationUnknown': 'Esito incerto; controlla il provider',
  'modelSurface.moderationUnsupported': 'Non supportato',
  'modelSurface.fanvueWebhookUrl': 'Endpoint webhook',
  'modelSurface.fanvueWebhookMissing': 'FANVUE_WEBHOOK_SECRET non è configurato, quindi gli eventi in ingresso sono disattivati.',
  'modelSurface.generationAccessUnavailable': 'Accesso alla generazione non disponibile',
  'modelSurface.generationRoleDenied': 'Il tuo ruolo non consente di creare o caricare contenuti multimediali.',
  'modelSurface.backToWorkspace': 'Torna allo spazio di lavoro',
  'modelSurface.loadingEarnings': 'Caricamento dei ricavi',
  'modelSurface.loadingEarningsDescription': 'Verifica dell’accesso all’account e dei dati finanziari richiesti. Non viene pubblicato né ritirato nulla.',
  'modelSurface.loadingInbox': 'Caricamento della posta in arrivo',
  'modelSurface.loadingInboxDescription': 'Verifica dell’accesso e recupero della pagina richiesta. Non vengono inviati messaggi né modificati come letti.',
  'modelSurface.talentPortfolio': 'Portfolio del talento',
  'modelSurface.talentWorkspace': 'Spazio di lavoro del talento',
  'modelSurface.active': 'Attivo',
  'modelSurface.inactive': 'Inattivo',
};

const ptBR: Record<ModelSurfaceMessageKey, string> = {
  'modelSurface.linkbioTitle': 'Link na bio',
  'modelSurface.providers': 'Provedores',
  'modelSurface.noProvider': 'Nenhum provedor está ativado. A página nativa não exige nada externo; ative-a para servir uma página de links própria.',
  'modelSurface.activeProviders': '{count} provedor(es) ativo(s)',
  'modelSurface.primaryProvider': ' — principal: {kind}',
  'modelSurface.publicPage': 'Página pública:',
  'modelSurface.externalAdaptersUnavailable': 'Os adaptadores externos Linktree, Beacons e Fanlynks não estão disponíveis nesta versão.',
  'modelSurface.clickAnalytics': 'Análise de cliques',
  'modelSurface.totalClicks': 'Total de cliques: {count}',
  'modelSurface.target': 'Destino',
  'modelSurface.clicks': 'Cliques',
  'modelSurface.fanvueAttribution': 'Atribuição do Fanvue',
  'modelSurface.revenueFacts': 'A receita vem de eventos do Fanvue. O ROI é calculado apenas quando receita e gastos registrados usam a mesma moeda.',
  'modelSurface.trackedClicks': '{count} cliques rastreados',
  'modelSurface.attributedConversions': '{count} conversões atribuídas',
  'modelSurface.unattributedConversions': '{count} conversões não atribuídas',
  'modelSurface.attributedRevenue': '{amount} de receita atribuída',
  'modelSurface.clickToConversion': '{rate} de cliques para conversão',
  'modelSurface.shortLink': 'Link curto',
  'modelSurface.conversions': 'Conversões',
  'modelSurface.revenue': 'Receita',
  'modelSurface.campaignCosts': 'Custos da campanha',
  'modelSurface.selectShortLink': 'Link curto',
  'modelSurface.costAmount': 'Valor em unidades monetárias menores',
  'modelSurface.costCurrency': 'Moeda',
  'modelSurface.recordSpend': 'Registrar gasto',
  'modelSurface.spendRecorded': 'Gasto da campanha registrado.',
  'modelSurface.spendSaveFailed': 'Não foi possível confirmar o gasto. Tente novamente para reconciliar o mesmo evento.',
  'modelSurface.roi': 'ROI líquido',
  'modelSurface.netRoiByCurrency': 'ROI líquido por moeda: {amount}',
  'modelSurface.spend': 'Gasto',
  'modelSurface.churnTitle': 'Recuperação de assinaturas',
  'modelSurface.churnDescription': 'Eventos de expiração assinados do Fanvue criam candidatos para revisão. Escreva a mensagem e a oferta e envie uma vez. Resultados incertos não são reenviados automaticamente.',
  'modelSurface.churnLoadFailed': 'Não foi possível carregar o histórico de recuperação.',
  'modelSurface.churnEmpty': 'Nenhuma assinatura desativada foi recebida.',
  'modelSurface.churnReady': 'Pronto para revisão',
  'modelSurface.churnSending': 'Envio em andamento; confira o Fanvue antes de agir.',
  'modelSurface.churnSent': 'Mensagem aceita pelo Fanvue',
  'modelSurface.churnUnknown': 'Resultado incerto; reconcilie no Fanvue e não reenvie.',
  'modelSurface.churnMessage': 'Mensagem',
  'modelSurface.churnOffer': 'Detalhes da oferta ou desconto',
  'modelSurface.churnSend': 'Enviar mensagem de recuperação',
  'modelSurface.churnSentNotice': 'O Fanvue aceitou a mensagem de recuperação.',
  'modelSurface.churnUnknownNotice': 'O Fanvue pode ter recebido a mensagem. Reconcilie no Fanvue; o sistema não a reenviará.',
  'modelSurface.moderationTitle': 'Moderação de comentários por palavras-chave',
  'modelSurface.moderationDescription': 'Crie regras literais de palavras-chave e analise uma publicação do provedor. Só ficam disponíveis provedores e ações permitidos pela conta conectada. O texto dos comentários não é armazenado.',
  'modelSurface.moderationName': 'Nome da regra',
  'modelSurface.moderationPlatform': 'Provedor',
  'modelSurface.moderationKeywords': 'Palavras-chave (uma por linha)',
  'modelSurface.moderationAction': 'Ação',
  'modelSurface.moderationHide': 'Ocultar comentários correspondentes',
  'modelSurface.moderationHideBlock': 'Ocultar e bloquear comentarista (quando compatível)',
  'modelSurface.moderationCreateRule': 'Criar regra',
  'modelSurface.moderationPostId': 'ID da publicação no provedor',
  'modelSurface.moderationScan': 'Analisar comentários da publicação',
  'modelSurface.moderationNextPage': 'Analisar próxima página',
  'modelSurface.moderationMorePages': 'Há mais comentários. Continue com a próxima página.',
  'modelSurface.moderationHistory': 'Ações recentes de moderação',
  'modelSurface.moderationEmpty': 'Ainda não há regras ou ações de moderação.',
  'modelSurface.moderationLoadFailed': 'Não foi possível carregar as configurações de moderação.',
  'modelSurface.moderationSaveFailed': 'Não foi possível confirmar a alteração de moderação.',
  'modelSurface.moderationScanResult': 'Analisados {scanned}; correspondências {matched}; aplicados {moderated}; parciais {partial}; incertos {unknown}; já registrados {alreadyRecorded}.',
  'modelSurface.moderationUnsupportedRules': 'Algumas regras foram ignoradas porque esta conexão não oferece suporte às ações.',
  'modelSurface.moderationNoConnections': 'Conecte uma conta com permissões de leitura e moderação de comentários.',
  'modelSurface.moderationEnabled': 'Ativada',
  'modelSurface.moderationEnable': 'Ativar regra',
  'modelSurface.moderationDisable': 'Desativar regra',
  'modelSurface.moderationDelete': 'Excluir regra',
  'modelSurface.moderationPending': 'Pendente ou interrompida',
  'modelSurface.moderationApplied': 'Aplicada',
  'modelSurface.moderationPartial': 'Ocultação aplicada; bloqueio não confirmado',
  'modelSurface.moderationUnknown': 'Resultado incerto; confira no provedor',
  'modelSurface.moderationUnsupported': 'Não compatível',
  'modelSurface.fanvueWebhookUrl': 'Endpoint do webhook',
  'modelSurface.fanvueWebhookMissing': 'FANVUE_WEBHOOK_SECRET não está configurado; eventos recebidos estão desativados.',
  'modelSurface.generationAccessUnavailable': 'Acesso à geração indisponível',
  'modelSurface.generationRoleDenied': 'Sua função não permite criar ou enviar mídia.',
  'modelSurface.backToWorkspace': 'Voltar ao espaço de trabalho',
  'modelSurface.loadingEarnings': 'Carregando receitas',
  'modelSurface.loadingEarningsDescription': 'Verificando o acesso à conta e os registros financeiros solicitados. Nada está sendo publicado ou retirado.',
  'modelSurface.loadingInbox': 'Carregando a caixa de entrada',
  'modelSurface.loadingInboxDescription': 'Verificando o acesso e recuperando a página solicitada. Nenhuma mensagem é enviada ou marcada como lida.',
  'modelSurface.talentPortfolio': 'Portfólio do talento',
  'modelSurface.talentWorkspace': 'Espaço de trabalho do talento',
  'modelSurface.active': 'Ativo',
  'modelSurface.inactive': 'Inativo',
};

const de: Record<ModelSurfaceMessageKey, string> = {
  'modelSurface.linkbioTitle': 'Link in der Bio',
  'modelSurface.providers': 'Anbieter',
  'modelSurface.noProvider': 'Kein Anbieter aktiviert. Die native Seite benötigt nichts Externes; aktivieren Sie sie, um eine eigene Linkseite bereitzustellen.',
  'modelSurface.activeProviders': '{count} aktive Anbieter',
  'modelSurface.primaryProvider': ' — primär: {kind}',
  'modelSurface.publicPage': 'Öffentliche Seite:',
  'modelSurface.externalAdaptersUnavailable': 'Externe Linktree-, Beacons- und Fanlynks-Adapter sind in dieser Version nicht verfügbar.',
  'modelSurface.clickAnalytics': 'Klickanalyse',
  'modelSurface.totalClicks': 'Klicks insgesamt: {count}',
  'modelSurface.target': 'Ziel',
  'modelSurface.clicks': 'Klicks',
  'modelSurface.fanvueAttribution': 'Fanvue-Zuordnung',
  'modelSurface.revenueFacts': 'Umsatz stammt aus Fanvue-Ereignissen. Der ROI wird nur berechnet, wenn Umsatz und erfasste Ausgaben dieselbe Währung verwenden.',
  'modelSurface.trackedClicks': '{count} erfasste Klicks',
  'modelSurface.attributedConversions': '{count} zugeordnete Konversionen',
  'modelSurface.unattributedConversions': '{count} nicht zugeordnete Konversionen',
  'modelSurface.attributedRevenue': '{amount} zugeordneter Umsatz',
  'modelSurface.clickToConversion': '{rate} Klick-zu-Konversion',
  'modelSurface.shortLink': 'Kurzlink',
  'modelSurface.conversions': 'Konversionen',
  'modelSurface.revenue': 'Umsatz',
  'modelSurface.campaignCosts': 'Kampagnenkosten',
  'modelSurface.selectShortLink': 'Kurzlink',
  'modelSurface.costAmount': 'Betrag in Untereinheiten der Währung',
  'modelSurface.costCurrency': 'Währung',
  'modelSurface.recordSpend': 'Ausgabe erfassen',
  'modelSurface.spendRecorded': 'Kampagnenausgabe erfasst.',
  'modelSurface.spendSaveFailed': 'Die Ausgabe konnte nicht bestätigt werden. Wiederholen Sie den Versuch, um dasselbe Ereignis abzugleichen.',
  'modelSurface.roi': 'Netto-ROI',
  'modelSurface.netRoiByCurrency': 'Netto-ROI nach Währung: {amount}',
  'modelSurface.spend': 'Ausgabe',
  'modelSurface.churnTitle': 'Abonnement-Rückgewinnung',
  'modelSurface.churnDescription': 'Signierte Ablaufereignisse von Fanvue erzeugen prüfbare Vorgänge. Schreiben Sie Nachricht und Angebot und senden Sie einmal. Unklare Ergebnisse werden nicht automatisch erneut gesendet.',
  'modelSurface.churnLoadFailed': 'Der Rückgewinnungsverlauf konnte nicht geladen werden.',
  'modelSurface.churnEmpty': 'Es sind keine deaktivierten Abonnements eingegangen.',
  'modelSurface.churnReady': 'Zur Prüfung bereit',
  'modelSurface.churnSending': 'Versand läuft — prüfen Sie Fanvue, bevor Sie weitere Schritte ausführen.',
  'modelSurface.churnSent': 'Nachricht von Fanvue angenommen',
  'modelSurface.churnUnknown': 'Ergebnis unklar — gleichen Sie es in Fanvue ab und senden Sie nicht erneut.',
  'modelSurface.churnMessage': 'Nachricht',
  'modelSurface.churnOffer': 'Angebots- oder Rabattdetails',
  'modelSurface.churnSend': 'Rückgewinnungsnachricht senden',
  'modelSurface.churnSentNotice': 'Fanvue hat die Rückgewinnungsnachricht angenommen.',
  'modelSurface.churnUnknownNotice': 'Fanvue hat die Nachricht möglicherweise erhalten. Gleichen Sie sie in Fanvue ab; das System sendet sie nicht erneut.',
  'modelSurface.moderationTitle': 'Kommentarfilter nach Schlüsselwörtern',
  'modelSurface.moderationDescription': 'Erstellen Sie Regeln für wörtliche Schlüsselwörter und prüfen Sie einen Anbieterbeitrag. Verfügbar sind nur Anbieter und Aktionen, die das verbundene Konto erlaubt. Kommentartexte werden nicht gespeichert.',
  'modelSurface.moderationName': 'Regelname',
  'modelSurface.moderationPlatform': 'Anbieter',
  'modelSurface.moderationKeywords': 'Schlüsselwörter (eines pro Zeile)',
  'modelSurface.moderationAction': 'Aktion',
  'modelSurface.moderationHide': 'Passende Kommentare ausblenden',
  'modelSurface.moderationHideBlock': 'Kommentator ausblenden und blockieren (falls unterstützt)',
  'modelSurface.moderationCreateRule': 'Regel erstellen',
  'modelSurface.moderationPostId': 'Beitrags-ID des Anbieters',
  'modelSurface.moderationScan': 'Beitragskommentare prüfen',
  'modelSurface.moderationNextPage': 'Nächste Seite prüfen',
  'modelSurface.moderationMorePages': 'Weitere Kommentare sind verfügbar. Fahren Sie mit der nächsten Seite fort.',
  'modelSurface.moderationHistory': 'Letzte Moderationsaktionen',
  'modelSurface.moderationEmpty': 'Es gibt noch keine Moderationsregeln oder Aktionen.',
  'modelSurface.moderationLoadFailed': 'Moderationseinstellungen konnten nicht geladen werden.',
  'modelSurface.moderationSaveFailed': 'Die Moderationsänderung konnte nicht bestätigt werden.',
  'modelSurface.moderationScanResult': 'Geprüft {scanned}; Treffer {matched}; angewandt {moderated}; teilweise {partial}; unklar {unknown}; bereits erfasst {alreadyRecorded}.',
  'modelSurface.moderationUnsupportedRules': 'Einige Regeln wurden übersprungen, weil diese Verbindung die Aktionen nicht unterstützt.',
  'modelSurface.moderationNoConnections': 'Verbinden Sie ein Konto mit Berechtigungen zum Lesen und Moderieren von Kommentaren.',
  'modelSurface.moderationEnabled': 'Aktiviert',
  'modelSurface.moderationEnable': 'Regel aktivieren',
  'modelSurface.moderationDisable': 'Regel deaktivieren',
  'modelSurface.moderationDelete': 'Regel löschen',
  'modelSurface.moderationPending': 'Ausstehend oder unterbrochen',
  'modelSurface.moderationApplied': 'Angewandt',
  'modelSurface.moderationPartial': 'Ausblenden angewandt; Blockieren nicht bestätigt',
  'modelSurface.moderationUnknown': 'Ergebnis unklar; prüfen Sie den Anbieter',
  'modelSurface.moderationUnsupported': 'Nicht unterstützt',
  'modelSurface.fanvueWebhookUrl': 'Webhook-Endpunkt',
  'modelSurface.fanvueWebhookMissing': 'FANVUE_WEBHOOK_SECRET ist nicht konfiguriert; eingehende Ereignisse sind deaktiviert.',
  'modelSurface.generationAccessUnavailable': 'Generierungszugriff nicht verfügbar',
  'modelSurface.generationRoleDenied': 'Ihre Rolle erlaubt das Erstellen oder Hochladen von Medien nicht.',
  'modelSurface.backToWorkspace': 'Zurück zum Workspace',
  'modelSurface.loadingEarnings': 'Umsatz wird geladen',
  'modelSurface.loadingEarningsDescription': 'Kontozugriff und die angeforderten Finanzdaten werden geprüft. Es wird nichts veröffentlicht oder ausgezahlt.',
  'modelSurface.loadingInbox': 'Posteingang wird geladen',
  'modelSurface.loadingInboxDescription': 'Zugriff wird geprüft und die angeforderte Seite wird geladen. Es werden keine Nachrichten gesendet oder als gelesen markiert.',
  'modelSurface.talentPortfolio': 'Talent-Portfolio',
  'modelSurface.talentWorkspace': 'Talent-Workspace',
  'modelSurface.active': 'Aktiv',
  'modelSurface.inactive': 'Inaktiv',
};

export const MODEL_SURFACE_CATALOGS: Record<SupportedLocale, Catalog> = {
  en,
  es,
  ja,
  it,
  'pt-BR': ptBR,
  de,
};
