import type { Catalog, SupportedLocale } from './locale.js';

/** Feature-owned copy for the remaining mounted model workspace surfaces. */
export const MODEL_SURFACE_MESSAGE_KEYS = [
  'modelSurface.linkbioTitle',
  'modelSurface.providers',
  'modelSurface.noProvider',
  'modelSurface.activeProviders',
  'modelSurface.primaryProvider',
  'modelSurface.publicPage',
  'modelSurface.externalAdaptersUnavailable',
  'modelSurface.clickAnalytics',
  'modelSurface.totalClicks',
  'modelSurface.target',
  'modelSurface.clicks',
  'modelSurface.fanvueAttribution',
  'modelSurface.revenueFacts',
  'modelSurface.trackedClicks',
  'modelSurface.attributedConversions',
  'modelSurface.unattributedConversions',
  'modelSurface.attributedRevenue',
  'modelSurface.clickToConversion',
  'modelSurface.shortLink',
  'modelSurface.conversions',
  'modelSurface.revenue',
  'modelSurface.generationAccessUnavailable',
  'modelSurface.generationRoleDenied',
  'modelSurface.backToWorkspace',
  'modelSurface.loadingEarnings',
  'modelSurface.loadingEarningsDescription',
  'modelSurface.loadingInbox',
  'modelSurface.loadingInboxDescription',
  'modelSurface.talentPortfolio',
  'modelSurface.talentWorkspace',
  'modelSurface.active',
  'modelSurface.inactive',
] as const;

export type ModelSurfaceMessageKey = (typeof MODEL_SURFACE_MESSAGE_KEYS)[number];

const en: Record<ModelSurfaceMessageKey, string> = {
  'modelSurface.linkbioTitle': 'Link in bio',
  'modelSurface.providers': 'Providers',
  'modelSurface.noProvider': 'No provider enabled. The native page requires nothing external — enable it to serve a first-party link page.',
  'modelSurface.activeProviders': '{count} active provider(s)',
  'modelSurface.primaryProvider': ' — primary: {kind}',
  'modelSurface.publicPage': 'Public page:',
  'modelSurface.externalAdaptersUnavailable': 'External Linktree, Beacons, and Fanlynks adapters are not available in this release.',
  'modelSurface.clickAnalytics': 'Click analytics',
  'modelSurface.totalClicks': 'Total clicks: {count}',
  'modelSurface.target': 'Target',
  'modelSurface.clicks': 'Clicks',
  'modelSurface.fanvueAttribution': 'Fanvue attribution',
  'modelSurface.revenueFacts': 'Revenue facts joined from authoritative Fanvue events. ROI stays unavailable until campaign cost data is configured.',
  'modelSurface.trackedClicks': '{count} tracked clicks',
  'modelSurface.attributedConversions': '{count} attributed conversions',
  'modelSurface.unattributedConversions': '{count} unattributed conversions',
  'modelSurface.attributedRevenue': '{amount} attributed revenue',
  'modelSurface.clickToConversion': '{rate} click-to-conversion',
  'modelSurface.shortLink': 'Short link',
  'modelSurface.conversions': 'Conversions',
  'modelSurface.revenue': 'Revenue',
  'modelSurface.generationAccessUnavailable': 'Generation access unavailable',
  'modelSurface.generationRoleDenied': 'Your role does not allow creating or uploading media.',
  'modelSurface.backToWorkspace': 'Back to workspace',
  'modelSurface.loadingEarnings': 'Loading earnings',
  'modelSurface.loadingEarningsDescription': 'Checking account access and the requested financial records. Nothing is being published or withdrawn.',
  'modelSurface.loadingInbox': 'Loading inbox',
  'modelSurface.loadingInboxDescription': 'Checking access and retrieving the requested page. No messages are being sent or marked read.',
  'modelSurface.talentPortfolio': 'Talent portfolio',
  'modelSurface.talentWorkspace': 'Talent workspace',
  'modelSurface.active': 'Active',
  'modelSurface.inactive': 'Inactive',
};

const es: Record<ModelSurfaceMessageKey, string> = {
  'modelSurface.linkbioTitle': 'Enlace en la biografía',
  'modelSurface.providers': 'Proveedores',
  'modelSurface.noProvider': 'No hay ningún proveedor activado. La página nativa no requiere nada externo; actívala para servir una página de enlaces propia.',
  'modelSurface.activeProviders': '{count} proveedor(es) activo(s)',
  'modelSurface.primaryProvider': ' — principal: {kind}',
  'modelSurface.publicPage': 'Página pública:',
  'modelSurface.externalAdaptersUnavailable': 'Los adaptadores externos de Linktree, Beacons y Fanlynks no están disponibles en esta versión.',
  'modelSurface.clickAnalytics': 'Analítica de clics',
  'modelSurface.totalClicks': 'Clics totales: {count}',
  'modelSurface.target': 'Destino',
  'modelSurface.clicks': 'Clics',
  'modelSurface.fanvueAttribution': 'Atribución de Fanvue',
  'modelSurface.revenueFacts': 'Ingresos relacionados con eventos autorizados de Fanvue. El ROI no está disponible hasta configurar los costes de campaña.',
  'modelSurface.trackedClicks': '{count} clics registrados',
  'modelSurface.attributedConversions': '{count} conversiones atribuidas',
  'modelSurface.unattributedConversions': '{count} conversiones no atribuidas',
  'modelSurface.attributedRevenue': '{amount} de ingresos atribuidos',
  'modelSurface.clickToConversion': '{rate} de clics a conversiones',
  'modelSurface.shortLink': 'Enlace corto',
  'modelSurface.conversions': 'Conversiones',
  'modelSurface.revenue': 'Ingresos',
  'modelSurface.generationAccessUnavailable': 'El acceso a la generación no está disponible',
  'modelSurface.generationRoleDenied': 'Tu rol no permite crear ni subir medios.',
  'modelSurface.backToWorkspace': 'Volver al espacio de trabajo',
  'modelSurface.loadingEarnings': 'Cargando ingresos',
  'modelSurface.loadingEarningsDescription': 'Comprobando el acceso a la cuenta y los registros financieros solicitados. No se publica ni retira nada.',
  'modelSurface.loadingInbox': 'Cargando bandeja de entrada',
  'modelSurface.loadingInboxDescription': 'Comprobando el acceso y recuperando la página solicitada. No se envían mensajes ni se marcan como leídos.',
  'modelSurface.talentPortfolio': 'Portafolio del talento',
  'modelSurface.talentWorkspace': 'Espacio de trabajo del talento',
  'modelSurface.active': 'Activo',
  'modelSurface.inactive': 'Inactivo',
};

const ja: Record<ModelSurfaceMessageKey, string> = {
  'modelSurface.linkbioTitle': 'プロフィールリンク',
  'modelSurface.providers': 'プロバイダー',
  'modelSurface.noProvider': '有効なプロバイダーはありません。ネイティブページに外部サービスは不要です。有効にすると自前のリンクページを提供できます。',
  'modelSurface.activeProviders': '有効なプロバイダー {count} 件',
  'modelSurface.primaryProvider': ' — 主要: {kind}',
  'modelSurface.publicPage': '公開ページ:',
  'modelSurface.externalAdaptersUnavailable': 'このリリースでは外部のLinktree、Beacons、Fanlynksアダプターを利用できません。',
  'modelSurface.clickAnalytics': 'クリック分析',
  'modelSurface.totalClicks': '合計クリック数: {count}',
  'modelSurface.target': 'リンク先',
  'modelSurface.clicks': 'クリック数',
  'modelSurface.fanvueAttribution': 'Fanvueのアトリビューション',
  'modelSurface.revenueFacts': '信頼できるFanvueイベントから収益情報を結合しています。キャンペーン費用を設定するまでROIは利用できません。',
  'modelSurface.trackedClicks': '記録済みクリック {count} 件',
  'modelSurface.attributedConversions': '帰属コンバージョン {count} 件',
  'modelSurface.unattributedConversions': '未帰属コンバージョン {count} 件',
  'modelSurface.attributedRevenue': '帰属収益 {amount}',
  'modelSurface.clickToConversion': 'クリックからコンバージョン: {rate}',
  'modelSurface.shortLink': '短縮リンク',
  'modelSurface.conversions': 'コンバージョン',
  'modelSurface.revenue': '収益',
  'modelSurface.generationAccessUnavailable': '生成機能を利用できません',
  'modelSurface.generationRoleDenied': '現在のロールではメディアの作成やアップロードはできません。',
  'modelSurface.backToWorkspace': 'ワークスペースに戻る',
  'modelSurface.loadingEarnings': '収益を読み込み中',
  'modelSurface.loadingEarningsDescription': 'アカウントアクセスと要求された財務記録を確認しています。公開や出金は行われません。',
  'modelSurface.loadingInbox': '受信トレイを読み込み中',
  'modelSurface.loadingInboxDescription': 'アクセスを確認し、要求されたページを取得しています。メッセージの送信や既読化は行われません。',
  'modelSurface.talentPortfolio': 'タレントポートフォリオ',
  'modelSurface.talentWorkspace': 'タレントワークスペース',
  'modelSurface.active': '有効',
  'modelSurface.inactive': '無効',
};

const it: Record<ModelSurfaceMessageKey, string> = {
  'modelSurface.linkbioTitle': 'Link nella bio',
  'modelSurface.providers': 'Provider',
  'modelSurface.noProvider': 'Nessun provider è attivo. La pagina nativa non richiede servizi esterni: attivala per offrire una pagina di link proprietaria.',
  'modelSurface.activeProviders': '{count} provider attivi',
  'modelSurface.primaryProvider': ' — principale: {kind}',
  'modelSurface.publicPage': 'Pagina pubblica:',
  'modelSurface.externalAdaptersUnavailable': 'Gli adattatori esterni Linktree, Beacons e Fanlynks non sono disponibili in questa versione.',
  'modelSurface.clickAnalytics': 'Analisi dei clic',
  'modelSurface.totalClicks': 'Clic totali: {count}',
  'modelSurface.target': 'Destinazione',
  'modelSurface.clicks': 'Clic',
  'modelSurface.fanvueAttribution': 'Attribuzione Fanvue',
  'modelSurface.revenueFacts': 'Dati sui ricavi uniti dagli eventi Fanvue autorevoli. Il ROI resta non disponibile finché non vengono configurati i costi della campagna.',
  'modelSurface.trackedClicks': '{count} clic tracciati',
  'modelSurface.attributedConversions': '{count} conversioni attribuite',
  'modelSurface.unattributedConversions': '{count} conversioni non attribuite',
  'modelSurface.attributedRevenue': '{amount} di ricavi attribuiti',
  'modelSurface.clickToConversion': '{rate} da clic a conversione',
  'modelSurface.shortLink': 'Link breve',
  'modelSurface.conversions': 'Conversioni',
  'modelSurface.revenue': 'Ricavi',
  'modelSurface.generationAccessUnavailable': 'Accesso alla generazione non disponibile',
  'modelSurface.generationRoleDenied': 'Il tuo ruolo non consente di creare o caricare contenuti multimediali.',
  'modelSurface.backToWorkspace': 'Torna allo spazio di lavoro',
  'modelSurface.loadingEarnings': 'Caricamento dei ricavi',
  'modelSurface.loadingEarningsDescription': 'Verifica dell’accesso all’account e dei dati finanziari richiesti. Non viene pubblicato né ritirato nulla.',
  'modelSurface.loadingInbox': 'Caricamento della posta in arrivo',
  'modelSurface.loadingInboxDescription': 'Verifica dell’accesso e recupero della pagina richiesta. Non vengono inviati messaggi né modificati come letti.',
  'modelSurface.talentPortfolio': 'Portfolio del talento',
  'modelSurface.talentWorkspace': 'Spazio di lavoro del talento',
  'modelSurface.active': 'Attivo',
  'modelSurface.inactive': 'Inattivo',
};

const ptBR: Record<ModelSurfaceMessageKey, string> = {
  'modelSurface.linkbioTitle': 'Link na bio',
  'modelSurface.providers': 'Provedores',
  'modelSurface.noProvider': 'Nenhum provedor está ativado. A página nativa não exige nada externo; ative-a para servir uma página de links própria.',
  'modelSurface.activeProviders': '{count} provedor(es) ativo(s)',
  'modelSurface.primaryProvider': ' — principal: {kind}',
  'modelSurface.publicPage': 'Página pública:',
  'modelSurface.externalAdaptersUnavailable': 'Os adaptadores externos Linktree, Beacons e Fanlynks não estão disponíveis nesta versão.',
  'modelSurface.clickAnalytics': 'Análise de cliques',
  'modelSurface.totalClicks': 'Total de cliques: {count}',
  'modelSurface.target': 'Destino',
  'modelSurface.clicks': 'Cliques',
  'modelSurface.fanvueAttribution': 'Atribuição do Fanvue',
  'modelSurface.revenueFacts': 'Dados de receita unidos a partir de eventos confiáveis do Fanvue. O ROI fica indisponível até que os custos da campanha sejam configurados.',
  'modelSurface.trackedClicks': '{count} cliques rastreados',
  'modelSurface.attributedConversions': '{count} conversões atribuídas',
  'modelSurface.unattributedConversions': '{count} conversões não atribuídas',
  'modelSurface.attributedRevenue': '{amount} de receita atribuída',
  'modelSurface.clickToConversion': '{rate} de cliques para conversão',
  'modelSurface.shortLink': 'Link curto',
  'modelSurface.conversions': 'Conversões',
  'modelSurface.revenue': 'Receita',
  'modelSurface.generationAccessUnavailable': 'Acesso à geração indisponível',
  'modelSurface.generationRoleDenied': 'Sua função não permite criar ou enviar mídia.',
  'modelSurface.backToWorkspace': 'Voltar ao espaço de trabalho',
  'modelSurface.loadingEarnings': 'Carregando receitas',
  'modelSurface.loadingEarningsDescription': 'Verificando o acesso à conta e os registros financeiros solicitados. Nada está sendo publicado ou retirado.',
  'modelSurface.loadingInbox': 'Carregando a caixa de entrada',
  'modelSurface.loadingInboxDescription': 'Verificando o acesso e recuperando a página solicitada. Nenhuma mensagem é enviada ou marcada como lida.',
  'modelSurface.talentPortfolio': 'Portfólio do talento',
  'modelSurface.talentWorkspace': 'Espaço de trabalho do talento',
  'modelSurface.active': 'Ativo',
  'modelSurface.inactive': 'Inativo',
};

const de: Record<ModelSurfaceMessageKey, string> = {
  'modelSurface.linkbioTitle': 'Link in der Bio',
  'modelSurface.providers': 'Anbieter',
  'modelSurface.noProvider': 'Kein Anbieter aktiviert. Die native Seite benötigt nichts Externes; aktivieren Sie sie, um eine eigene Linkseite bereitzustellen.',
  'modelSurface.activeProviders': '{count} aktive Anbieter',
  'modelSurface.primaryProvider': ' — primär: {kind}',
  'modelSurface.publicPage': 'Öffentliche Seite:',
  'modelSurface.externalAdaptersUnavailable': 'Externe Linktree-, Beacons- und Fanlynks-Adapter sind in dieser Version nicht verfügbar.',
  'modelSurface.clickAnalytics': 'Klickanalyse',
  'modelSurface.totalClicks': 'Klicks insgesamt: {count}',
  'modelSurface.target': 'Ziel',
  'modelSurface.clicks': 'Klicks',
  'modelSurface.fanvueAttribution': 'Fanvue-Zuordnung',
  'modelSurface.revenueFacts': 'Umsatzdaten aus maßgeblichen Fanvue-Ereignissen. Der ROI bleibt nicht verfügbar, bis Kampagnenkosten konfiguriert sind.',
  'modelSurface.trackedClicks': '{count} erfasste Klicks',
  'modelSurface.attributedConversions': '{count} zugeordnete Konversionen',
  'modelSurface.unattributedConversions': '{count} nicht zugeordnete Konversionen',
  'modelSurface.attributedRevenue': '{amount} zugeordneter Umsatz',
  'modelSurface.clickToConversion': '{rate} Klick-zu-Konversion',
  'modelSurface.shortLink': 'Kurzlink',
  'modelSurface.conversions': 'Konversionen',
  'modelSurface.revenue': 'Umsatz',
  'modelSurface.generationAccessUnavailable': 'Generierungszugriff nicht verfügbar',
  'modelSurface.generationRoleDenied': 'Ihre Rolle erlaubt das Erstellen oder Hochladen von Medien nicht.',
  'modelSurface.backToWorkspace': 'Zurück zum Workspace',
  'modelSurface.loadingEarnings': 'Umsatz wird geladen',
  'modelSurface.loadingEarningsDescription': 'Kontozugriff und die angeforderten Finanzdaten werden geprüft. Es wird nichts veröffentlicht oder ausgezahlt.',
  'modelSurface.loadingInbox': 'Posteingang wird geladen',
  'modelSurface.loadingInboxDescription': 'Zugriff wird geprüft und die angeforderte Seite wird geladen. Es werden keine Nachrichten gesendet oder als gelesen markiert.',
  'modelSurface.talentPortfolio': 'Talent-Portfolio',
  'modelSurface.talentWorkspace': 'Talent-Workspace',
  'modelSurface.active': 'Aktiv',
  'modelSurface.inactive': 'Inaktiv',
};

export const MODEL_SURFACE_CATALOGS: Record<SupportedLocale, Catalog> = {
  en,
  es,
  ja,
  it,
  'pt-BR': ptBR,
  de,
};
