import type { Catalog, SupportedLocale } from './locale.js';

/**
 * Copy used by the authenticated monthly analytics PDF.
 *
 * The report is generated by the API rather than rendered by the dashboard,
 * so it owns a small catalog instead of reaching into dashboard components.
 * The runtime catalog mounts this set alongside the shared UI catalog.
 */
export const MONTHLY_REPORT_KEYS = [
  'monthlyReport.title',
  'monthlyReport.scheduledPosts',
  'monthlyReport.publishedPosts',
  'monthlyReport.views',
  'monthlyReport.likes',
  'monthlyReport.shares',
  'monthlyReport.comments',
  'monthlyReport.adherenceScore',
  'monthlyReport.viralExemplars',
  'monthlyReport.source',
  'monthlyReport.latestSnapshot',
  'monthlyReport.cumulative',
  'monthlyReport.savedObservations',
] as const;

export type MonthlyReportMessageKey = (typeof MONTHLY_REPORT_KEYS)[number];

const en: Catalog = {
  'monthlyReport.title': 'FanThynks - Monthly performance report',
  'monthlyReport.scheduledPosts': 'Scheduled posts: {count}',
  'monthlyReport.publishedPosts': 'Published posts: {count}',
  'monthlyReport.views': 'Views: {count}',
  'monthlyReport.likes': 'Likes: {count}',
  'monthlyReport.shares': 'Shares: {count}',
  'monthlyReport.comments': 'Comments: {count}',
  'monthlyReport.adherenceScore': 'Course adherence score: {count} / 100',
  'monthlyReport.viralExemplars': 'Viral exemplars captured: {count}',
  'monthlyReport.source': 'Metrics are generated from the authenticated workspace analytics store.',
  'monthlyReport.latestSnapshot': 'Totals use one latest saved snapshot per post within the selected month.',
  'monthlyReport.cumulative': 'These are cumulative counters, not engagement earned during the month.',
  'monthlyReport.savedObservations': 'Saved observations may include manual or legacy metric sources.',
};

const es: Catalog = {
  'monthlyReport.title': 'FanThynks - Informe mensual de rendimiento',
  'monthlyReport.scheduledPosts': 'Publicaciones programadas: {count}',
  'monthlyReport.publishedPosts': 'Publicaciones publicadas: {count}',
  'monthlyReport.views': 'Visualizaciones: {count}',
  'monthlyReport.likes': 'Me gusta: {count}',
  'monthlyReport.shares': 'Compartidos: {count}',
  'monthlyReport.comments': 'Comentarios: {count}',
  'monthlyReport.adherenceScore': 'Puntuación de cumplimiento del curso: {count} / 100',
  'monthlyReport.viralExemplars': 'Ejemplos virales capturados: {count}',
  'monthlyReport.source': 'Las métricas se generan desde el almacén de analítica autenticado del espacio de trabajo.',
  'monthlyReport.latestSnapshot': 'Los totales usan la última instantánea guardada de cada publicación del mes seleccionado.',
  'monthlyReport.cumulative': 'Son contadores acumulados, no la interacción obtenida durante el mes.',
  'monthlyReport.savedObservations': 'Las observaciones guardadas pueden incluir fuentes manuales o heredadas.',
};

const ja: Catalog = {
  'monthlyReport.title': 'FanThynks - 月間パフォーマンスレポート',
  'monthlyReport.scheduledPosts': '予定投稿: {count}',
  'monthlyReport.publishedPosts': '公開済み投稿: {count}',
  'monthlyReport.views': '閲覧数: {count}',
  'monthlyReport.likes': 'いいね: {count}',
  'monthlyReport.shares': 'シェア: {count}',
  'monthlyReport.comments': 'コメント: {count}',
  'monthlyReport.adherenceScore': 'コース遵守スコア: {count} / 100',
  'monthlyReport.viralExemplars': '取得したバイラル事例: {count}',
  'monthlyReport.source': '指標は認証済みワークスペースの分析ストアから生成されています。',
  'monthlyReport.latestSnapshot': '合計は選択した月の投稿ごとに保存された最新スナップショットを使用します。',
  'monthlyReport.cumulative': 'これは累積カウンターであり、月中に得たエンゲージメントではありません。',
  'monthlyReport.savedObservations': '保存された観測には手動またはレガシーな指標ソースが含まれる場合があります。',
};

const it: Catalog = {
  'monthlyReport.title': 'FanThynks - Report mensile delle prestazioni',
  'monthlyReport.scheduledPosts': 'Post programmati: {count}',
  'monthlyReport.publishedPosts': 'Post pubblicati: {count}',
  'monthlyReport.views': 'Visualizzazioni: {count}',
  'monthlyReport.likes': 'Mi piace: {count}',
  'monthlyReport.shares': 'Condivisioni: {count}',
  'monthlyReport.comments': 'Commenti: {count}',
  'monthlyReport.adherenceScore': 'Punteggio di aderenza al corso: {count} / 100',
  'monthlyReport.viralExemplars': 'Esempi virali acquisiti: {count}',
  'monthlyReport.source': 'Le metriche sono generate dal registro analitico autenticato dello spazio di lavoro.',
  'monthlyReport.latestSnapshot': 'I totali usano l’ultima istantanea salvata per ogni post del mese selezionato.',
  'monthlyReport.cumulative': 'Sono contatori cumulativi, non l’engagement ottenuto durante il mese.',
  'monthlyReport.savedObservations': 'Le osservazioni salvate possono includere fonti manuali o legacy.',
};

const ptBR: Catalog = {
  'monthlyReport.title': 'FanThynks - Relatório mensal de desempenho',
  'monthlyReport.scheduledPosts': 'Publicações programadas: {count}',
  'monthlyReport.publishedPosts': 'Publicações publicadas: {count}',
  'monthlyReport.views': 'Visualizações: {count}',
  'monthlyReport.likes': 'Curtidas: {count}',
  'monthlyReport.shares': 'Compartilhamentos: {count}',
  'monthlyReport.comments': 'Comentários: {count}',
  'monthlyReport.adherenceScore': 'Pontuação de aderência ao curso: {count} / 100',
  'monthlyReport.viralExemplars': 'Exemplos virais capturados: {count}',
  'monthlyReport.source': 'As métricas são geradas pelo armazenamento de análises autenticado do workspace.',
  'monthlyReport.latestSnapshot': 'Os totais usam o instantâneo salvo mais recente de cada publicação no mês selecionado.',
  'monthlyReport.cumulative': 'São contadores cumulativos, não o engajamento obtido durante o mês.',
  'monthlyReport.savedObservations': 'As observações salvas podem incluir fontes manuais ou legadas.',
};

const de: Catalog = {
  'monthlyReport.title': 'FanThynks - Monatlicher Leistungsbericht',
  'monthlyReport.scheduledPosts': 'Geplante Beiträge: {count}',
  'monthlyReport.publishedPosts': 'Veröffentlichte Beiträge: {count}',
  'monthlyReport.views': 'Aufrufe: {count}',
  'monthlyReport.likes': 'Gefällt mir: {count}',
  'monthlyReport.shares': 'Geteilt: {count}',
  'monthlyReport.comments': 'Kommentare: {count}',
  'monthlyReport.adherenceScore': 'Kursbefolgung: {count} / 100',
  'monthlyReport.viralExemplars': 'Erfasste virale Beispiele: {count}',
  'monthlyReport.source': 'Die Metriken werden aus dem authentifizierten Analyse-Speicher des Arbeitsbereichs erzeugt.',
  'monthlyReport.latestSnapshot': 'Die Summen verwenden den neuesten gespeicherten Snapshot je Beitrag im ausgewählten Monat.',
  'monthlyReport.cumulative': 'Dies sind kumulative Zähler, nicht das im Monat erzielte Engagement.',
  'monthlyReport.savedObservations': 'Gespeicherte Beobachtungen können manuelle oder ältere Metrikquellen enthalten.',
};

export const MONTHLY_REPORT_CATALOGS: Record<SupportedLocale, Catalog> = {
  en,
  es,
  ja,
  it,
  'pt-BR': ptBR,
  de,
};

export function monthlyReportCatalogIsComplete(locale: SupportedLocale): boolean {
  return MONTHLY_REPORT_KEYS.every((key) => typeof MONTHLY_REPORT_CATALOGS[locale][key] === 'string');
}
