import type { Catalog, SupportedLocale } from './locale.js';

/** Feature-owned copy for the mounted model profile, lifecycle and network controls. */
export const PROFILE_NETWORK_LIFECYCLE_MESSAGE_KEYS = [
  'profile.editSummary',
  'profile.description',
  'profile.aria',
  'profile.creatorName',
  'profile.handle',
  'profile.brandNote',
  'profile.avatarUrlOptional',
  'profile.avatarPlaceholder',
  'profile.saving',
  'profile.retry',
  'profile.save',
  'profile.saved',
  'profile.checkFields',
  'profile.saveUnconfirmed',
  'profile.responseUnconfirmed',
  'profile.validation.creatorName',
  'profile.validation.handle',
  'profile.validation.brandNote',
  'profile.validation.avatarUrl',
  'lifecycle.summary',
  'lifecycle.description',
  'lifecycle.confirmDeactivate',
  'lifecycle.deactivating',
  'lifecycle.reactivating',
  'lifecycle.retry',
  'lifecycle.deactivate',
  'lifecycle.reactivate',
  'lifecycle.reactivated',
  'lifecycle.deactivated',
  'lifecycle.statusUnconfirmed',
  'lifecycle.responseUnconfirmed',
  'network.modeLabel',
  'network.chooseMode',
  'network.mode.direct',
  'network.mode.socks5',
  'network.mode.http',
  'network.mode.https',
  'network.mode.wireguard',
  'network.mode.vpn',
  'network.directWarning',
  'network.proxyAddressLabel',
  'network.proxyPlaceholder',
  'network.expectedIpLabel',
  'network.expectedIpPlaceholder',
  'network.chooseConnection',
  'network.saveFailed',
  'network.connectionError',
  'network.saved',
  'network.saving',
  'network.save',
] as const;

export type ProfileNetworkLifecycleMessageKey =
  (typeof PROFILE_NETWORK_LIFECYCLE_MESSAGE_KEYS)[number];

const en: Record<ProfileNetworkLifecycleMessageKey, string> = {
  'profile.editSummary': 'Edit profile details',
  'profile.description':
    'These fields describe this workspace profile; they do not rename connected social accounts.',
  'profile.aria': 'Edit talent profile',
  'profile.creatorName': 'Creator name',
  'profile.handle': 'Handle',
  'profile.brandNote': 'Brand note',
  'profile.avatarUrlOptional': 'Avatar URL (optional)',
  'profile.avatarPlaceholder': 'https://…',
  'profile.saving': 'Saving…',
  'profile.retry': 'Retry same profile changes',
  'profile.save': 'Save profile details',
  'profile.saved': 'Profile saved. Character lock and connected accounts were not changed.',
  'profile.checkFields': 'Check profile fields.',
  'profile.saveUnconfirmed': 'Profile save not confirmed. Retry the same changes.',
  'profile.responseUnconfirmed':
    'Profile save not confirmed. Retry the same changes before editing again.',
  'profile.validation.creatorName': 'Enter a creator name of 1–100 characters.',
  'profile.validation.handle': 'Enter a handle of 1–50 characters.',
  'profile.validation.brandNote': 'The brand note must be at most 500 characters.',
  'profile.validation.avatarUrl':
    'Avatar URL must be a valid http(s) URL of at most 2048 characters.',
  'lifecycle.summary': 'Profile lifecycle',
  'lifecycle.description':
    'Deactivation pauses this profile without deleting its content or audit history.',
  'lifecycle.confirmDeactivate':
    'Deactivate {name}? Existing media, approvals, and records will be retained.',
  'lifecycle.deactivating': 'Deactivating…',
  'lifecycle.reactivating': 'Reactivating…',
  'lifecycle.retry': 'Retry same action',
  'lifecycle.deactivate': 'Deactivate profile',
  'lifecycle.reactivate': 'Reactivate profile',
  'lifecycle.reactivated': 'Profile reactivated.',
  'lifecycle.deactivated': 'Profile deactivated. Existing records were retained.',
  'lifecycle.statusUnconfirmed': 'Profile status could not be confirmed.',
  'lifecycle.responseUnconfirmed':
    'Profile status was not confirmed. Retry the same action before changing anything else.',
  'network.modeLabel': 'Egress mode',
  'network.chooseMode': 'Choose an outbound connection',
  'network.mode.direct': 'Direct',
  'network.mode.socks5': 'SOCKS5 proxy',
  'network.mode.http': 'HTTP proxy',
  'network.mode.https': 'HTTPS proxy',
  'network.mode.wireguard': 'WireGuard',
  'network.mode.vpn': 'VPN (WireGuard)',
  'network.directWarning':
    'Direct uses the server’s outbound IP without a VPN or proxy. Choose this only if you intend to use an unprotected connection.',
  'network.proxyAddressLabel': 'Proxy address (host:port)',
  'network.proxyPlaceholder': '127.0.0.1:1080',
  'network.expectedIpLabel': 'Expected egress IP (drift policy)',
  'network.expectedIpPlaceholder': '203.0.113.7',
  'network.chooseConnection': 'Choose an outbound connection before saving.',
  'network.saveFailed': 'Save failed',
  'network.connectionError': 'Network error',
  'network.saved': 'Saved.',
  'network.saving': 'Saving…',
  'network.save': 'Save network config',
};

const es: Record<ProfileNetworkLifecycleMessageKey, string> = {
  'profile.editSummary': 'Editar datos del perfil',
  'profile.description':
    'Estos campos describen el perfil del espacio de trabajo; no cambian el nombre de las cuentas sociales conectadas.',
  'profile.aria': 'Editar perfil del talento',
  'profile.creatorName': 'Nombre del creador',
  'profile.handle': 'Identificador',
  'profile.brandNote': 'Nota de marca',
  'profile.avatarUrlOptional': 'URL del avatar (opcional)',
  'profile.avatarPlaceholder': 'https://…',
  'profile.saving': 'Guardando…',
  'profile.retry': 'Reintentar los mismos cambios del perfil',
  'profile.save': 'Guardar datos del perfil',
  'profile.saved':
    'Perfil guardado. No se modificaron el bloqueo de personaje ni las cuentas conectadas.',
  'profile.checkFields': 'Revisa los campos del perfil.',
  'profile.saveUnconfirmed': 'No se confirmó el guardado del perfil. Repite los mismos cambios.',
  'profile.responseUnconfirmed':
    'No se confirmó el guardado del perfil. Repite los mismos cambios antes de editar de nuevo.',
  'profile.validation.creatorName': 'Introduce un nombre de creador de 1 a 100 caracteres.',
  'profile.validation.handle': 'Introduce un identificador de 1 a 50 caracteres.',
  'profile.validation.brandNote': 'La nota de marca debe tener como máximo 500 caracteres.',
  'profile.validation.avatarUrl':
    'La URL del avatar debe ser una URL http(s) válida de como máximo 2048 caracteres.',
  'lifecycle.summary': 'Ciclo de vida del perfil',
  'lifecycle.description':
    'La desactivación pausa este perfil sin eliminar su contenido ni su historial de auditoría.',
  'lifecycle.confirmDeactivate':
    '¿Desactivar {name}? Se conservarán los medios, las aprobaciones y los registros existentes.',
  'lifecycle.deactivating': 'Desactivando…',
  'lifecycle.reactivating': 'Reactivando…',
  'lifecycle.retry': 'Repetir la misma acción',
  'lifecycle.deactivate': 'Desactivar perfil',
  'lifecycle.reactivate': 'Reactivar perfil',
  'lifecycle.reactivated': 'Perfil reactivado.',
  'lifecycle.deactivated': 'Perfil desactivado. Se conservaron los registros existentes.',
  'lifecycle.statusUnconfirmed': 'No se pudo confirmar el estado del perfil.',
  'lifecycle.responseUnconfirmed':
    'No se confirmó el estado del perfil. Repite la misma acción antes de cambiar otra cosa.',
  'network.modeLabel': 'Modo de salida',
  'network.chooseMode': 'Elige una conexión saliente',
  'network.mode.direct': 'Directa',
  'network.mode.socks5': 'Proxy SOCKS5',
  'network.mode.http': 'Proxy HTTP',
  'network.mode.https': 'Proxy HTTPS',
  'network.mode.wireguard': 'WireGuard',
  'network.mode.vpn': 'VPN (WireGuard)',
  'network.directWarning':
    'El modo directo usa la IP saliente del servidor sin VPN ni proxy. Elígelo solo si quieres usar una conexión sin protección.',
  'network.proxyAddressLabel': 'Dirección del proxy (host:puerto)',
  'network.proxyPlaceholder': '127.0.0.1:1080',
  'network.expectedIpLabel': 'IP de salida esperada (política de cambios)',
  'network.expectedIpPlaceholder': '203.0.113.7',
  'network.chooseConnection': 'Elige una conexión saliente antes de guardar.',
  'network.saveFailed': 'No se pudo guardar',
  'network.connectionError': 'Error de red',
  'network.saved': 'Guardado.',
  'network.saving': 'Guardando…',
  'network.save': 'Guardar configuración de red',
};

const ja: Record<ProfileNetworkLifecycleMessageKey, string> = {
  'profile.editSummary': 'プロフィール詳細を編集',
  'profile.description':
    'これらの項目はワークスペースのプロフィールを説明します。接続済みソーシャルアカウントの名前は変更しません。',
  'profile.aria': 'タレントプロフィールを編集',
  'profile.creatorName': 'クリエイター名',
  'profile.handle': 'ハンドル',
  'profile.brandNote': 'ブランドメモ',
  'profile.avatarUrlOptional': 'アバターURL（任意）',
  'profile.avatarPlaceholder': 'https://…',
  'profile.saving': '保存中…',
  'profile.retry': '同じプロフィール変更を再試行',
  'profile.save': 'プロフィール詳細を保存',
  'profile.saved':
    'プロフィールを保存しました。キャラクターロックと接続済みアカウントは変更していません。',
  'profile.checkFields': 'プロフィール項目を確認してください。',
  'profile.saveUnconfirmed':
    'プロフィールの保存を確認できませんでした。同じ変更を再試行してください。',
  'profile.responseUnconfirmed':
    'プロフィールの保存を確認できませんでした。再編集する前に同じ変更を再試行してください。',
  'profile.validation.creatorName': 'クリエイター名は1～100文字で入力してください。',
  'profile.validation.handle': 'ハンドルは1～50文字で入力してください。',
  'profile.validation.brandNote': 'ブランドメモは500文字以内で入力してください。',
  'profile.validation.avatarUrl':
    'アバターURLは2048文字以内の有効なhttp(s) URLで入力してください。',
  'lifecycle.summary': 'プロフィールのライフサイクル',
  'lifecycle.description':
    '無効化すると、コンテンツや監査履歴を削除せずにプロフィールを一時停止します。',
  'lifecycle.confirmDeactivate':
    '{name}を無効化しますか？既存のメディア、承認、記録は保持されます。',
  'lifecycle.deactivating': '無効化中…',
  'lifecycle.reactivating': '再有効化中…',
  'lifecycle.retry': '同じ操作を再試行',
  'lifecycle.deactivate': 'プロフィールを無効化',
  'lifecycle.reactivate': 'プロフィールを再有効化',
  'lifecycle.reactivated': 'プロフィールを再有効化しました。',
  'lifecycle.deactivated': 'プロフィールを無効化しました。既存の記録は保持されます。',
  'lifecycle.statusUnconfirmed': 'プロフィールの状態を確認できませんでした。',
  'lifecycle.responseUnconfirmed':
    'プロフィールの状態を確認できませんでした。他の変更をする前に同じ操作を再試行してください。',
  'network.modeLabel': '送信モード',
  'network.chooseMode': '送信接続を選択',
  'network.mode.direct': '直接接続',
  'network.mode.socks5': 'SOCKS5プロキシ',
  'network.mode.http': 'HTTPプロキシ',
  'network.mode.https': 'HTTPSプロキシ',
  'network.mode.wireguard': 'WireGuard',
  'network.mode.vpn': 'VPN（WireGuard）',
  'network.directWarning':
    '直接接続はVPNやプロキシを使わず、サーバーの送信IPを使用します。保護されない接続を意図する場合のみ選択してください。',
  'network.proxyAddressLabel': 'プロキシアドレス（ホスト:ポート）',
  'network.proxyPlaceholder': '127.0.0.1:1080',
  'network.expectedIpLabel': '想定送信IP（変更ポリシー）',
  'network.expectedIpPlaceholder': '203.0.113.7',
  'network.chooseConnection': '保存する前に送信接続を選択してください。',
  'network.saveFailed': '保存に失敗しました',
  'network.connectionError': 'ネットワークエラー',
  'network.saved': '保存しました。',
  'network.saving': '保存中…',
  'network.save': 'ネットワーク設定を保存',
};

const it: Record<ProfileNetworkLifecycleMessageKey, string> = {
  'profile.editSummary': 'Modifica dettagli del profilo',
  'profile.description':
    'Questi campi descrivono il profilo dello spazio di lavoro; non rinominano gli account social collegati.',
  'profile.aria': 'Modifica profilo del talento',
  'profile.creatorName': 'Nome del creator',
  'profile.handle': 'Handle',
  'profile.brandNote': 'Nota del brand',
  'profile.avatarUrlOptional': 'URL avatar (facoltativo)',
  'profile.avatarPlaceholder': 'https://…',
  'profile.saving': 'Salvataggio…',
  'profile.retry': 'Riprova le stesse modifiche al profilo',
  'profile.save': 'Salva dettagli profilo',
  'profile.saved':
    'Profilo salvato. Il blocco del personaggio e gli account collegati non sono stati modificati.',
  'profile.checkFields': 'Controlla i campi del profilo.',
  'profile.saveUnconfirmed': 'Salvataggio del profilo non confermato. Riprova le stesse modifiche.',
  'profile.responseUnconfirmed':
    'Salvataggio del profilo non confermato. Riprova le stesse modifiche prima di modificare ancora.',
  'profile.validation.creatorName': 'Inserisci un nome creator da 1 a 100 caratteri.',
  'profile.validation.handle': 'Inserisci un handle da 1 a 50 caratteri.',
  'profile.validation.brandNote': 'La nota del brand deve contenere al massimo 500 caratteri.',
  'profile.validation.avatarUrl':
    'L’URL avatar deve essere un URL http(s) valido di massimo 2048 caratteri.',
  'lifecycle.summary': 'Ciclo di vita del profilo',
  'lifecycle.description':
    'La disattivazione sospende il profilo senza eliminare contenuti o cronologia di audit.',
  'lifecycle.confirmDeactivate':
    'Disattivare {name}? I media, le approvazioni e i record esistenti saranno conservati.',
  'lifecycle.deactivating': 'Disattivazione…',
  'lifecycle.reactivating': 'Riattivazione…',
  'lifecycle.retry': 'Riprova la stessa azione',
  'lifecycle.deactivate': 'Disattiva profilo',
  'lifecycle.reactivate': 'Riattiva profilo',
  'lifecycle.reactivated': 'Profilo riattivato.',
  'lifecycle.deactivated': 'Profilo disattivato. I record esistenti sono stati conservati.',
  'lifecycle.statusUnconfirmed': 'Impossibile confermare lo stato del profilo.',
  'lifecycle.responseUnconfirmed':
    'Lo stato del profilo non è stato confermato. Riprova la stessa azione prima di cambiare altro.',
  'network.modeLabel': 'Modalità di uscita',
  'network.chooseMode': 'Scegli una connessione in uscita',
  'network.mode.direct': 'Diretta',
  'network.mode.socks5': 'Proxy SOCKS5',
  'network.mode.http': 'Proxy HTTP',
  'network.mode.https': 'Proxy HTTPS',
  'network.mode.wireguard': 'WireGuard',
  'network.mode.vpn': 'VPN (WireGuard)',
  'network.directWarning':
    'La modalità diretta usa l’IP in uscita del server senza VPN o proxy. Sceglila solo se intendi usare una connessione non protetta.',
  'network.proxyAddressLabel': 'Indirizzo proxy (host:porta)',
  'network.proxyPlaceholder': '127.0.0.1:1080',
  'network.expectedIpLabel': 'IP in uscita previsto (criterio di variazione)',
  'network.expectedIpPlaceholder': '203.0.113.7',
  'network.chooseConnection': 'Scegli una connessione in uscita prima di salvare.',
  'network.saveFailed': 'Salvataggio non riuscito',
  'network.connectionError': 'Errore di rete',
  'network.saved': 'Salvato.',
  'network.saving': 'Salvataggio…',
  'network.save': 'Salva configurazione di rete',
};

const ptBR: Record<ProfileNetworkLifecycleMessageKey, string> = {
  'profile.editSummary': 'Editar detalhes do perfil',
  'profile.description':
    'Estes campos descrevem o perfil do espaço de trabalho; eles não renomeiam contas sociais conectadas.',
  'profile.aria': 'Editar perfil do talento',
  'profile.creatorName': 'Nome do criador',
  'profile.handle': 'Identificador',
  'profile.brandNote': 'Nota da marca',
  'profile.avatarUrlOptional': 'URL do avatar (opcional)',
  'profile.avatarPlaceholder': 'https://…',
  'profile.saving': 'Salvando…',
  'profile.retry': 'Tentar novamente as mesmas alterações do perfil',
  'profile.save': 'Salvar detalhes do perfil',
  'profile.saved':
    'Perfil salvo. O bloqueio de personagem e as contas conectadas não foram alterados.',
  'profile.checkFields': 'Verifique os campos do perfil.',
  'profile.saveUnconfirmed':
    'O salvamento do perfil não foi confirmado. Tente novamente as mesmas alterações.',
  'profile.responseUnconfirmed':
    'O salvamento do perfil não foi confirmado. Tente novamente as mesmas alterações antes de editar outra vez.',
  'profile.validation.creatorName': 'Digite um nome de criador com 1 a 100 caracteres.',
  'profile.validation.handle': 'Digite um identificador com 1 a 50 caracteres.',
  'profile.validation.brandNote': 'A nota da marca deve ter no máximo 500 caracteres.',
  'profile.validation.avatarUrl':
    'A URL do avatar deve ser uma URL http(s) válida com no máximo 2048 caracteres.',
  'lifecycle.summary': 'Ciclo de vida do perfil',
  'lifecycle.description':
    'A desativação pausa este perfil sem excluir seu conteúdo ou histórico de auditoria.',
  'lifecycle.confirmDeactivate':
    'Desativar {name}? A mídia, as aprovações e os registros existentes serão mantidos.',
  'lifecycle.deactivating': 'Desativando…',
  'lifecycle.reactivating': 'Reativando…',
  'lifecycle.retry': 'Tentar novamente a mesma ação',
  'lifecycle.deactivate': 'Desativar perfil',
  'lifecycle.reactivate': 'Reativar perfil',
  'lifecycle.reactivated': 'Perfil reativado.',
  'lifecycle.deactivated': 'Perfil desativado. Os registros existentes foram mantidos.',
  'lifecycle.statusUnconfirmed': 'Não foi possível confirmar o estado do perfil.',
  'lifecycle.responseUnconfirmed':
    'O estado do perfil não foi confirmado. Tente novamente a mesma ação antes de alterar qualquer outra coisa.',
  'network.modeLabel': 'Modo de saída',
  'network.chooseMode': 'Escolha uma conexão de saída',
  'network.mode.direct': 'Direta',
  'network.mode.socks5': 'Proxy SOCKS5',
  'network.mode.http': 'Proxy HTTP',
  'network.mode.https': 'Proxy HTTPS',
  'network.mode.wireguard': 'WireGuard',
  'network.mode.vpn': 'VPN (WireGuard)',
  'network.directWarning':
    'O modo direto usa o IP de saída do servidor sem VPN ou proxy. Escolha-o apenas se você pretende usar uma conexão desprotegida.',
  'network.proxyAddressLabel': 'Endereço do proxy (host:porta)',
  'network.proxyPlaceholder': '127.0.0.1:1080',
  'network.expectedIpLabel': 'IP de saída esperado (política de alteração)',
  'network.expectedIpPlaceholder': '203.0.113.7',
  'network.chooseConnection': 'Escolha uma conexão de saída antes de salvar.',
  'network.saveFailed': 'Falha ao salvar',
  'network.connectionError': 'Erro de rede',
  'network.saved': 'Salvo.',
  'network.saving': 'Salvando…',
  'network.save': 'Salvar configuração de rede',
};

const de: Record<ProfileNetworkLifecycleMessageKey, string> = {
  'profile.editSummary': 'Profildetails bearbeiten',
  'profile.description':
    'Diese Felder beschreiben das Workspace-Profil; verbundene soziale Konten werden dadurch nicht umbenannt.',
  'profile.aria': 'Talentprofil bearbeiten',
  'profile.creatorName': 'Name des Creators',
  'profile.handle': 'Handle',
  'profile.brandNote': 'Markennotiz',
  'profile.avatarUrlOptional': 'Avatar-URL (optional)',
  'profile.avatarPlaceholder': 'https://…',
  'profile.saving': 'Wird gespeichert…',
  'profile.retry': 'Dieselben Profiländerungen erneut versuchen',
  'profile.save': 'Profildetails speichern',
  'profile.saved':
    'Profil gespeichert. Charaktersperre und verbundene Konten wurden nicht geändert.',
  'profile.checkFields': 'Profilfelder prüfen.',
  'profile.saveUnconfirmed':
    'Das Speichern des Profils wurde nicht bestätigt. Versuchen Sie dieselben Änderungen erneut.',
  'profile.responseUnconfirmed':
    'Das Speichern des Profils wurde nicht bestätigt. Versuchen Sie dieselben Änderungen vor einer weiteren Bearbeitung erneut.',
  'profile.validation.creatorName': 'Geben Sie einen Creator-Namen mit 1–100 Zeichen ein.',
  'profile.validation.handle': 'Geben Sie einen Handle mit 1–50 Zeichen ein.',
  'profile.validation.brandNote': 'Die Markennotiz darf höchstens 500 Zeichen enthalten.',
  'profile.validation.avatarUrl':
    'Die Avatar-URL muss eine gültige http(s)-URL mit höchstens 2048 Zeichen sein.',
  'lifecycle.summary': 'Profil-Lebenszyklus',
  'lifecycle.description':
    'Die Deaktivierung pausiert dieses Profil, ohne Inhalte oder Auditverlauf zu löschen.',
  'lifecycle.confirmDeactivate':
    '{name} deaktivieren? Vorhandene Medien, Freigaben und Datensätze bleiben erhalten.',
  'lifecycle.deactivating': 'Wird deaktiviert…',
  'lifecycle.reactivating': 'Wird reaktiviert…',
  'lifecycle.retry': 'Dieselbe Aktion erneut versuchen',
  'lifecycle.deactivate': 'Profil deaktivieren',
  'lifecycle.reactivate': 'Profil reaktivieren',
  'lifecycle.reactivated': 'Profil reaktiviert.',
  'lifecycle.deactivated': 'Profil deaktiviert. Vorhandene Datensätze wurden beibehalten.',
  'lifecycle.statusUnconfirmed': 'Der Profilstatus konnte nicht bestätigt werden.',
  'lifecycle.responseUnconfirmed':
    'Der Profilstatus wurde nicht bestätigt. Versuchen Sie dieselbe Aktion vor weiteren Änderungen erneut.',
  'network.modeLabel': 'Ausgangsmodus',
  'network.chooseMode': 'Ausgehende Verbindung auswählen',
  'network.mode.direct': 'Direkt',
  'network.mode.socks5': 'SOCKS5-Proxy',
  'network.mode.http': 'HTTP-Proxy',
  'network.mode.https': 'HTTPS-Proxy',
  'network.mode.wireguard': 'WireGuard',
  'network.mode.vpn': 'VPN (WireGuard)',
  'network.directWarning':
    'Der Direktmodus verwendet die Ausgangs-IP des Servers ohne VPN oder Proxy. Wählen Sie ihn nur für eine ungeschützte Verbindung.',
  'network.proxyAddressLabel': 'Proxy-Adresse (Host:Port)',
  'network.proxyPlaceholder': '127.0.0.1:1080',
  'network.expectedIpLabel': 'Erwartete Ausgangs-IP (Änderungsrichtlinie)',
  'network.expectedIpPlaceholder': '203.0.113.7',
  'network.chooseConnection': 'Wählen Sie vor dem Speichern eine ausgehende Verbindung.',
  'network.saveFailed': 'Speichern fehlgeschlagen',
  'network.connectionError': 'Netzwerkfehler',
  'network.saved': 'Gespeichert.',
  'network.saving': 'Wird gespeichert…',
  'network.save': 'Netzwerkkonfiguration speichern',
};

export const PROFILE_NETWORK_LIFECYCLE_CATALOGS: Record<SupportedLocale, Catalog> = {
  en,
  es,
  ja,
  it,
  'pt-BR': ptBR,
  de,
};

export function profileNetworkLifecycleCatalogIsComplete(locale: SupportedLocale): boolean {
  return PROFILE_NETWORK_LIFECYCLE_MESSAGE_KEYS.every(
    (key) => typeof PROFILE_NETWORK_LIFECYCLE_CATALOGS[locale][key] === 'string',
  );
}
