import type { Catalog, SupportedLocale } from './locale.js';

/**
 * Labels for the model-scoped provider cache controls. The controls describe
 * request-shape support only; they do not promise a provider cache hit or
 * savings rate.
 */
export const PROVIDER_CACHE_CONTROL_CATALOGS: Record<SupportedLocale, Catalog> = {
  en: {
    'dashboard.cacheControls.title': 'Prompt cache controls',
    'dashboard.cacheControls.intro': 'Choose which bounded cache settings this model may use. Unsupported transports fail closed before a provider call.',
    'dashboard.cacheControls.provider': 'Provider',
    'dashboard.cacheControls.enabled': 'Enabled',
    'dashboard.cacheControls.prefixAlignment': 'Align and stabilise prefix',
    'dashboard.cacheControls.promptCacheKey': 'Routing key (optional)',
    'dashboard.cacheControls.keyHint': 'Letters, numbers, dot, underscore, colon or hyphen; up to 64 characters.',
    'dashboard.cacheControls.save': 'Save cache controls',
    'dashboard.cacheControls.saving': 'Saving…',
    'dashboard.cacheControls.saved': 'Cache controls saved.',
    'dashboard.cacheControls.notConfirmed': 'The change could not be confirmed. Reload before retrying.',
    'dashboard.cacheControls.unavailable': 'Cache controls are unavailable for this account.',
    'dashboard.cacheControls.readOnly': 'You can view these controls but cannot change them.',
    'dashboard.cacheControls.invalidKey': 'The routing key contains a character that is not allowed.',
    'dashboard.cacheControls.disabledNote': 'Disabled means no cache directive is emitted.',
    'dashboard.cacheControls.telemetryTitle': 'Measured provider cache usage',
    'dashboard.cacheControls.telemetryIntro': 'Shows cache counters reported by providers. Local application-cache hits are excluded; unknown counters stay visible and prevent a complete rate.',
    'dashboard.cacheControls.telemetryRefresh': 'Refresh usage',
    'dashboard.cacheControls.telemetryRefreshing': 'Refreshing…',
    'dashboard.cacheControls.telemetryRequestFailed': 'Measured usage could not be loaded.',
    'dashboard.cacheControls.telemetryEmpty': 'No successful provider responses have been recorded for this model yet.',
    'dashboard.cacheControls.telemetryRate': 'Cache read rate',
    'dashboard.cacheControls.telemetryUnavailable': 'Unavailable until every successful response has usable counters',
    'dashboard.cacheControls.telemetryMeasuredResponses': 'Responses with usable counters',
    'dashboard.cacheControls.telemetryUnknownResponses': 'Responses missing counters',
    'dashboard.cacheControls.telemetryCachedTokens': 'Cached input tokens / prompt tokens',
    'dashboard.cacheControls.telemetryWindow': 'Observed dates',
    'dashboard.cacheControls.telemetryStatus.available': 'Available',
    'dashboard.cacheControls.telemetryStatus.partial': 'Partial',
    'dashboard.cacheControls.telemetryStatus.unavailable': 'Unavailable',
  },
  es: {
    'dashboard.cacheControls.title': 'Controles de caché del prompt',
    'dashboard.cacheControls.intro': 'Elige qué ajustes de caché acotados puede usar este modelo. Los transportes no compatibles fallan de forma segura antes de contactar al proveedor.',
    'dashboard.cacheControls.provider': 'Proveedor',
    'dashboard.cacheControls.enabled': 'Activado',
    'dashboard.cacheControls.prefixAlignment': 'Alinear y estabilizar el prefijo',
    'dashboard.cacheControls.promptCacheKey': 'Clave de enrutamiento (opcional)',
    'dashboard.cacheControls.keyHint': 'Letras, números, punto, guion bajo, dos puntos o guion; hasta 64 caracteres.',
    'dashboard.cacheControls.save': 'Guardar controles de caché',
    'dashboard.cacheControls.saving': 'Guardando…',
    'dashboard.cacheControls.saved': 'Controles de caché guardados.',
    'dashboard.cacheControls.notConfirmed': 'No se pudo confirmar el cambio. Recarga antes de volver a intentarlo.',
    'dashboard.cacheControls.unavailable': 'Los controles de caché no están disponibles para esta cuenta.',
    'dashboard.cacheControls.readOnly': 'Puedes ver estos controles, pero no modificarlos.',
    'dashboard.cacheControls.invalidKey': 'La clave de enrutamiento contiene un carácter no permitido.',
    'dashboard.cacheControls.disabledNote': 'Desactivado significa que no se emite ninguna directiva de caché.',
    'dashboard.cacheControls.telemetryTitle': 'Uso medido de caché del proveedor',
    'dashboard.cacheControls.telemetryIntro': 'Muestra los contadores de caché informados por los proveedores. Excluye la caché local de la aplicación; los contadores desconocidos impiden calcular una tasa completa.',
    'dashboard.cacheControls.telemetryRefresh': 'Actualizar uso',
    'dashboard.cacheControls.telemetryRefreshing': 'Actualizando…',
    'dashboard.cacheControls.telemetryRequestFailed': 'No se pudo cargar el uso medido.',
    'dashboard.cacheControls.telemetryEmpty': 'Aún no hay respuestas correctas del proveedor registradas para este modelo.',
    'dashboard.cacheControls.telemetryRate': 'Tasa de lectura de caché',
    'dashboard.cacheControls.telemetryUnavailable': 'No disponible hasta que todas las respuestas correctas tengan contadores válidos',
    'dashboard.cacheControls.telemetryMeasuredResponses': 'Respuestas con contadores válidos',
    'dashboard.cacheControls.telemetryUnknownResponses': 'Respuestas sin contadores',
    'dashboard.cacheControls.telemetryCachedTokens': 'Tokens de entrada en caché / tokens de prompt',
    'dashboard.cacheControls.telemetryWindow': 'Fechas observadas',
    'dashboard.cacheControls.telemetryStatus.available': 'Disponible',
    'dashboard.cacheControls.telemetryStatus.partial': 'Parcial',
    'dashboard.cacheControls.telemetryStatus.unavailable': 'No disponible',
  },
  ja: {
    'dashboard.cacheControls.title': 'プロンプトキャッシュ設定',
    'dashboard.cacheControls.intro': 'このモデルで使用できる限定的なキャッシュ設定を選択します。未対応の転送方式はプロバイダー呼び出し前に安全に停止します。',
    'dashboard.cacheControls.provider': 'プロバイダー',
    'dashboard.cacheControls.enabled': '有効',
    'dashboard.cacheControls.prefixAlignment': 'プレフィックスを整列・安定化',
    'dashboard.cacheControls.promptCacheKey': 'ルーティングキー（任意）',
    'dashboard.cacheControls.keyHint': '英数字、ドット、アンダースコア、コロン、ハイフン。64文字以内。',
    'dashboard.cacheControls.save': 'キャッシュ設定を保存',
    'dashboard.cacheControls.saving': '保存中…',
    'dashboard.cacheControls.saved': 'キャッシュ設定を保存しました。',
    'dashboard.cacheControls.notConfirmed': '変更を確認できませんでした。再読み込みしてから再試行してください。',
    'dashboard.cacheControls.unavailable': 'このアカウントではキャッシュ設定を利用できません。',
    'dashboard.cacheControls.readOnly': '設定は表示できますが変更できません。',
    'dashboard.cacheControls.invalidKey': 'ルーティングキーに使用できない文字が含まれています。',
    'dashboard.cacheControls.disabledNote': '無効の場合、キャッシュ指示は送信されません。',
    'dashboard.cacheControls.telemetryTitle': 'プロバイダーの実測キャッシュ使用量',
    'dashboard.cacheControls.telemetryIntro': 'プロバイダーが報告したキャッシュカウンターのみを表示します。アプリ内キャッシュのヒットは含まず、不明なカウンターがある場合は完全な率を表示しません。',
    'dashboard.cacheControls.telemetryRefresh': '使用量を更新',
    'dashboard.cacheControls.telemetryRefreshing': '更新中…',
    'dashboard.cacheControls.telemetryRequestFailed': '実測使用量を読み込めませんでした。',
    'dashboard.cacheControls.telemetryEmpty': 'このモデルのプロバイダー応答はまだ記録されていません。',
    'dashboard.cacheControls.telemetryRate': 'キャッシュ読み取り率',
    'dashboard.cacheControls.telemetryUnavailable': 'すべての成功応答に利用可能なカウンターが揃うまで表示できません',
    'dashboard.cacheControls.telemetryMeasuredResponses': '有効なカウンターがある応答',
    'dashboard.cacheControls.telemetryUnknownResponses': 'カウンターのない応答',
    'dashboard.cacheControls.telemetryCachedTokens': 'キャッシュされた入力トークン / プロンプトトークン',
    'dashboard.cacheControls.telemetryWindow': '観測日',
    'dashboard.cacheControls.telemetryStatus.available': '利用可能',
    'dashboard.cacheControls.telemetryStatus.partial': '一部のみ',
    'dashboard.cacheControls.telemetryStatus.unavailable': '利用不可',
  },
  it: {
    'dashboard.cacheControls.title': 'Controlli cache del prompt',
    'dashboard.cacheControls.intro': 'Scegli quali impostazioni cache vincolate può usare questo modello. I trasporti non supportati si bloccano in sicurezza prima della chiamata al provider.',
    'dashboard.cacheControls.provider': 'Provider',
    'dashboard.cacheControls.enabled': 'Abilitato',
    'dashboard.cacheControls.prefixAlignment': 'Allinea e stabilizza il prefisso',
    'dashboard.cacheControls.promptCacheKey': 'Chiave di instradamento (opzionale)',
    'dashboard.cacheControls.keyHint': 'Lettere, numeri, punto, trattino basso, due punti o trattino; massimo 64 caratteri.',
    'dashboard.cacheControls.save': 'Salva controlli cache',
    'dashboard.cacheControls.saving': 'Salvataggio…',
    'dashboard.cacheControls.saved': 'Controlli cache salvati.',
    'dashboard.cacheControls.notConfirmed': 'Non è stato possibile confermare la modifica. Ricarica prima di riprovare.',
    'dashboard.cacheControls.unavailable': 'I controlli cache non sono disponibili per questo account.',
    'dashboard.cacheControls.readOnly': 'Puoi visualizzare questi controlli ma non modificarli.',
    'dashboard.cacheControls.invalidKey': 'La chiave di instradamento contiene un carattere non consentito.',
    'dashboard.cacheControls.disabledNote': 'Disabilitato significa che non viene emessa alcuna direttiva cache.',
    'dashboard.cacheControls.telemetryTitle': 'Utilizzo cache misurato del provider',
    'dashboard.cacheControls.telemetryIntro': 'Mostra i contatori cache comunicati dai provider. Esclude la cache locale dell’applicazione; i contatori sconosciuti impediscono di calcolare un tasso completo.',
    'dashboard.cacheControls.telemetryRefresh': 'Aggiorna utilizzo',
    'dashboard.cacheControls.telemetryRefreshing': 'Aggiornamento…',
    'dashboard.cacheControls.telemetryRequestFailed': 'Impossibile caricare l’utilizzo misurato.',
    'dashboard.cacheControls.telemetryEmpty': 'Non sono ancora state registrate risposte del provider per questo modello.',
    'dashboard.cacheControls.telemetryRate': 'Tasso di lettura dalla cache',
    'dashboard.cacheControls.telemetryUnavailable': 'Non disponibile finché ogni risposta riuscita non dispone di contatori utilizzabili',
    'dashboard.cacheControls.telemetryMeasuredResponses': 'Risposte con contatori utilizzabili',
    'dashboard.cacheControls.telemetryUnknownResponses': 'Risposte senza contatori',
    'dashboard.cacheControls.telemetryCachedTokens': 'Token di input memorizzati / token del prompt',
    'dashboard.cacheControls.telemetryWindow': 'Date osservate',
    'dashboard.cacheControls.telemetryStatus.available': 'Disponibile',
    'dashboard.cacheControls.telemetryStatus.partial': 'Parziale',
    'dashboard.cacheControls.telemetryStatus.unavailable': 'Non disponibile',
  },
  'pt-BR': {
    'dashboard.cacheControls.title': 'Controles de cache do prompt',
    'dashboard.cacheControls.intro': 'Escolha quais configurações de cache limitadas este modelo pode usar. Transportes incompatíveis falham com segurança antes da chamada ao provedor.',
    'dashboard.cacheControls.provider': 'Provedor',
    'dashboard.cacheControls.enabled': 'Ativado',
    'dashboard.cacheControls.prefixAlignment': 'Alinhar e estabilizar o prefixo',
    'dashboard.cacheControls.promptCacheKey': 'Chave de roteamento (opcional)',
    'dashboard.cacheControls.keyHint': 'Letras, números, ponto, sublinhado, dois-pontos ou hífen; até 64 caracteres.',
    'dashboard.cacheControls.save': 'Salvar controles de cache',
    'dashboard.cacheControls.saving': 'Salvando…',
    'dashboard.cacheControls.saved': 'Controles de cache salvos.',
    'dashboard.cacheControls.notConfirmed': 'Não foi possível confirmar a alteração. Recarregue antes de tentar novamente.',
    'dashboard.cacheControls.unavailable': 'Os controles de cache não estão disponíveis para esta conta.',
    'dashboard.cacheControls.readOnly': 'Você pode visualizar estes controles, mas não alterá-los.',
    'dashboard.cacheControls.invalidKey': 'A chave de roteamento contém um caractere não permitido.',
    'dashboard.cacheControls.disabledNote': 'Desativado significa que nenhuma diretiva de cache é emitida.',
    'dashboard.cacheControls.telemetryTitle': 'Uso medido de cache do provedor',
    'dashboard.cacheControls.telemetryIntro': 'Mostra os contadores de cache informados pelos provedores. Exclui acertos do cache local; contadores desconhecidos impedem uma taxa completa.',
    'dashboard.cacheControls.telemetryRefresh': 'Atualizar uso',
    'dashboard.cacheControls.telemetryRefreshing': 'Atualizando…',
    'dashboard.cacheControls.telemetryRequestFailed': 'Não foi possível carregar o uso medido.',
    'dashboard.cacheControls.telemetryEmpty': 'Ainda não há respostas do provedor registradas para este modelo.',
    'dashboard.cacheControls.telemetryRate': 'Taxa de leitura do cache',
    'dashboard.cacheControls.telemetryUnavailable': 'Indisponível até que todas as respostas bem-sucedidas tenham contadores válidos',
    'dashboard.cacheControls.telemetryMeasuredResponses': 'Respostas com contadores válidos',
    'dashboard.cacheControls.telemetryUnknownResponses': 'Respostas sem contadores',
    'dashboard.cacheControls.telemetryCachedTokens': 'Tokens de entrada em cache / tokens do prompt',
    'dashboard.cacheControls.telemetryWindow': 'Datas observadas',
    'dashboard.cacheControls.telemetryStatus.available': 'Disponível',
    'dashboard.cacheControls.telemetryStatus.partial': 'Parcial',
    'dashboard.cacheControls.telemetryStatus.unavailable': 'Indisponível',
  },
  de: {
    'dashboard.cacheControls.title': 'Prompt-Cache-Steuerung',
    'dashboard.cacheControls.intro': 'Wähle die begrenzten Cache-Einstellungen für dieses Modell. Nicht unterstützte Transporte werden vor dem Provider-Aufruf sicher abgebrochen.',
    'dashboard.cacheControls.provider': 'Provider',
    'dashboard.cacheControls.enabled': 'Aktiviert',
    'dashboard.cacheControls.prefixAlignment': 'Präfix ausrichten und stabilisieren',
    'dashboard.cacheControls.promptCacheKey': 'Routing-Schlüssel (optional)',
    'dashboard.cacheControls.keyHint': 'Buchstaben, Zahlen, Punkt, Unterstrich, Doppelpunkt oder Bindestrich; maximal 64 Zeichen.',
    'dashboard.cacheControls.save': 'Cache-Steuerung speichern',
    'dashboard.cacheControls.saving': 'Speichern…',
    'dashboard.cacheControls.saved': 'Cache-Steuerung gespeichert.',
    'dashboard.cacheControls.notConfirmed': 'Die Änderung konnte nicht bestätigt werden. Vor einem erneuten Versuch neu laden.',
    'dashboard.cacheControls.unavailable': 'Die Cache-Steuerung ist für dieses Konto nicht verfügbar.',
    'dashboard.cacheControls.readOnly': 'Du kannst diese Steuerung ansehen, aber nicht ändern.',
    'dashboard.cacheControls.invalidKey': 'Der Routing-Schlüssel enthält ein nicht erlaubtes Zeichen.',
    'dashboard.cacheControls.disabledNote': 'Deaktiviert bedeutet, dass keine Cache-Direktive ausgegeben wird.',
    'dashboard.cacheControls.telemetryTitle': 'Gemessene Provider-Cache-Nutzung',
    'dashboard.cacheControls.telemetryIntro': 'Zeigt nur von Providern gemeldete Cache-Zähler. Lokale Anwendungscache-Treffer sind ausgeschlossen; unbekannte Zähler verhindern eine vollständige Quote.',
    'dashboard.cacheControls.telemetryRefresh': 'Nutzung aktualisieren',
    'dashboard.cacheControls.telemetryRefreshing': 'Wird aktualisiert…',
    'dashboard.cacheControls.telemetryRequestFailed': 'Gemessene Nutzung konnte nicht geladen werden.',
    'dashboard.cacheControls.telemetryEmpty': 'Für dieses Modell wurden noch keine Provider-Antworten erfasst.',
    'dashboard.cacheControls.telemetryRate': 'Cache-Leserate',
    'dashboard.cacheControls.telemetryUnavailable': 'Nicht verfügbar, bis jede erfolgreiche Antwort brauchbare Zähler enthält',
    'dashboard.cacheControls.telemetryMeasuredResponses': 'Antworten mit brauchbaren Zählern',
    'dashboard.cacheControls.telemetryUnknownResponses': 'Antworten ohne Zähler',
    'dashboard.cacheControls.telemetryCachedTokens': 'Gecachte Eingabetokens / Prompt-Tokens',
    'dashboard.cacheControls.telemetryWindow': 'Beobachtete Zeitspanne',
    'dashboard.cacheControls.telemetryStatus.available': 'Verfügbar',
    'dashboard.cacheControls.telemetryStatus.partial': 'Teilweise',
    'dashboard.cacheControls.telemetryStatus.unavailable': 'Nicht verfügbar',
  },
};
