import type { Catalog, SupportedLocale } from './locale.js';

/**
 * Labels for the model-scoped provider cache controls. The controls describe
 * request-shape support only; they do not promise a provider cache hit or
 * savings rate.
 */
export const PROVIDER_CACHE_CONTROL_CATALOGS: Record<SupportedLocale, Catalog> = {
  en: {
    'dashboard.cacheControls.title': 'Prompt cache controls',
    'dashboard.cacheControls.intro': 'Choose which bounded cache settings this model may use. Unsupported transports fail closed before a provider call.',
    'dashboard.cacheControls.provider': 'Provider',
    'dashboard.cacheControls.enabled': 'Enabled',
    'dashboard.cacheControls.prefixAlignment': 'Align and stabilise prefix',
    'dashboard.cacheControls.promptCacheKey': 'Routing key (optional)',
    'dashboard.cacheControls.keyHint': 'Letters, numbers, dot, underscore, colon or hyphen; up to 64 characters.',
    'dashboard.cacheControls.save': 'Save cache controls',
    'dashboard.cacheControls.saving': 'Saving…',
    'dashboard.cacheControls.saved': 'Cache controls saved.',
    'dashboard.cacheControls.notConfirmed': 'The change could not be confirmed. Reload before retrying.',
    'dashboard.cacheControls.unavailable': 'Cache controls are unavailable for this account.',
    'dashboard.cacheControls.readOnly': 'You can view these controls but cannot change them.',
    'dashboard.cacheControls.invalidKey': 'The routing key contains a character that is not allowed.',
    'dashboard.cacheControls.disabledNote': 'Disabled means no cache directive is emitted.',
  },
  es: {
    'dashboard.cacheControls.title': 'Controles de caché del prompt',
    'dashboard.cacheControls.intro': 'Elige qué ajustes de caché acotados puede usar este modelo. Los transportes no compatibles fallan de forma segura antes de contactar al proveedor.',
    'dashboard.cacheControls.provider': 'Proveedor',
    'dashboard.cacheControls.enabled': 'Activado',
    'dashboard.cacheControls.prefixAlignment': 'Alinear y estabilizar el prefijo',
    'dashboard.cacheControls.promptCacheKey': 'Clave de enrutamiento (opcional)',
    'dashboard.cacheControls.keyHint': 'Letras, números, punto, guion bajo, dos puntos o guion; hasta 64 caracteres.',
    'dashboard.cacheControls.save': 'Guardar controles de caché',
    'dashboard.cacheControls.saving': 'Guardando…',
    'dashboard.cacheControls.saved': 'Controles de caché guardados.',
    'dashboard.cacheControls.notConfirmed': 'No se pudo confirmar el cambio. Recarga antes de volver a intentarlo.',
    'dashboard.cacheControls.unavailable': 'Los controles de caché no están disponibles para esta cuenta.',
    'dashboard.cacheControls.readOnly': 'Puedes ver estos controles, pero no modificarlos.',
    'dashboard.cacheControls.invalidKey': 'La clave de enrutamiento contiene un carácter no permitido.',
    'dashboard.cacheControls.disabledNote': 'Desactivado significa que no se emite ninguna directiva de caché.',
  },
  ja: {
    'dashboard.cacheControls.title': 'プロンプトキャッシュ設定',
    'dashboard.cacheControls.intro': 'このモデルで使用できる限定的なキャッシュ設定を選択します。未対応の転送方式はプロバイダー呼び出し前に安全に停止します。',
    'dashboard.cacheControls.provider': 'プロバイダー',
    'dashboard.cacheControls.enabled': '有効',
    'dashboard.cacheControls.prefixAlignment': 'プレフィックスを整列・安定化',
    'dashboard.cacheControls.promptCacheKey': 'ルーティングキー（任意）',
    'dashboard.cacheControls.keyHint': '英数字、ドット、アンダースコア、コロン、ハイフン。64文字以内。',
    'dashboard.cacheControls.save': 'キャッシュ設定を保存',
    'dashboard.cacheControls.saving': '保存中…',
    'dashboard.cacheControls.saved': 'キャッシュ設定を保存しました。',
    'dashboard.cacheControls.notConfirmed': '変更を確認できませんでした。再読み込みしてから再試行してください。',
    'dashboard.cacheControls.unavailable': 'このアカウントではキャッシュ設定を利用できません。',
    'dashboard.cacheControls.readOnly': '設定は表示できますが変更できません。',
    'dashboard.cacheControls.invalidKey': 'ルーティングキーに使用できない文字が含まれています。',
    'dashboard.cacheControls.disabledNote': '無効の場合、キャッシュ指示は送信されません。',
  },
  it: {
    'dashboard.cacheControls.title': 'Controlli cache del prompt',
    'dashboard.cacheControls.intro': 'Scegli quali impostazioni cache vincolate può usare questo modello. I trasporti non supportati si bloccano in sicurezza prima della chiamata al provider.',
    'dashboard.cacheControls.provider': 'Provider',
    'dashboard.cacheControls.enabled': 'Abilitato',
    'dashboard.cacheControls.prefixAlignment': 'Allinea e stabilizza il prefisso',
    'dashboard.cacheControls.promptCacheKey': 'Chiave di instradamento (opzionale)',
    'dashboard.cacheControls.keyHint': 'Lettere, numeri, punto, trattino basso, due punti o trattino; massimo 64 caratteri.',
    'dashboard.cacheControls.save': 'Salva controlli cache',
    'dashboard.cacheControls.saving': 'Salvataggio…',
    'dashboard.cacheControls.saved': 'Controlli cache salvati.',
    'dashboard.cacheControls.notConfirmed': 'Non è stato possibile confermare la modifica. Ricarica prima di riprovare.',
    'dashboard.cacheControls.unavailable': 'I controlli cache non sono disponibili per questo account.',
    'dashboard.cacheControls.readOnly': 'Puoi visualizzare questi controlli ma non modificarli.',
    'dashboard.cacheControls.invalidKey': 'La chiave di instradamento contiene un carattere non consentito.',
    'dashboard.cacheControls.disabledNote': 'Disabilitato significa che non viene emessa alcuna direttiva cache.',
  },
  'pt-BR': {
    'dashboard.cacheControls.title': 'Controles de cache do prompt',
    'dashboard.cacheControls.intro': 'Escolha quais configurações de cache limitadas este modelo pode usar. Transportes incompatíveis falham com segurança antes da chamada ao provedor.',
    'dashboard.cacheControls.provider': 'Provedor',
    'dashboard.cacheControls.enabled': 'Ativado',
    'dashboard.cacheControls.prefixAlignment': 'Alinhar e estabilizar o prefixo',
    'dashboard.cacheControls.promptCacheKey': 'Chave de roteamento (opcional)',
    'dashboard.cacheControls.keyHint': 'Letras, números, ponto, sublinhado, dois-pontos ou hífen; até 64 caracteres.',
    'dashboard.cacheControls.save': 'Salvar controles de cache',
    'dashboard.cacheControls.saving': 'Salvando…',
    'dashboard.cacheControls.saved': 'Controles de cache salvos.',
    'dashboard.cacheControls.notConfirmed': 'Não foi possível confirmar a alteração. Recarregue antes de tentar novamente.',
    'dashboard.cacheControls.unavailable': 'Os controles de cache não estão disponíveis para esta conta.',
    'dashboard.cacheControls.readOnly': 'Você pode visualizar estes controles, mas não alterá-los.',
    'dashboard.cacheControls.invalidKey': 'A chave de roteamento contém um caractere não permitido.',
    'dashboard.cacheControls.disabledNote': 'Desativado significa que nenhuma diretiva de cache é emitida.',
  },
  de: {
    'dashboard.cacheControls.title': 'Prompt-Cache-Steuerung',
    'dashboard.cacheControls.intro': 'Wähle die begrenzten Cache-Einstellungen für dieses Modell. Nicht unterstützte Transporte werden vor dem Provider-Aufruf sicher abgebrochen.',
    'dashboard.cacheControls.provider': 'Provider',
    'dashboard.cacheControls.enabled': 'Aktiviert',
    'dashboard.cacheControls.prefixAlignment': 'Präfix ausrichten und stabilisieren',
    'dashboard.cacheControls.promptCacheKey': 'Routing-Schlüssel (optional)',
    'dashboard.cacheControls.keyHint': 'Buchstaben, Zahlen, Punkt, Unterstrich, Doppelpunkt oder Bindestrich; maximal 64 Zeichen.',
    'dashboard.cacheControls.save': 'Cache-Steuerung speichern',
    'dashboard.cacheControls.saving': 'Speichern…',
    'dashboard.cacheControls.saved': 'Cache-Steuerung gespeichert.',
    'dashboard.cacheControls.notConfirmed': 'Die Änderung konnte nicht bestätigt werden. Vor einem erneuten Versuch neu laden.',
    'dashboard.cacheControls.unavailable': 'Die Cache-Steuerung ist für dieses Konto nicht verfügbar.',
    'dashboard.cacheControls.readOnly': 'Du kannst diese Steuerung ansehen, aber nicht ändern.',
    'dashboard.cacheControls.invalidKey': 'Der Routing-Schlüssel enthält ein nicht erlaubtes Zeichen.',
    'dashboard.cacheControls.disabledNote': 'Deaktiviert bedeutet, dass keine Cache-Direktive ausgegeben wird.',
  },
};
