import type { SupportedLocale, Catalog } from './locale.js';

/** Localized controls for the model-scoped F-85 Relay insight action. */
export const VIRAL_INSIGHT_CATALOGS: Record<SupportedLocale, Catalog> = {
  en: {
    'dashboard.viralInsight.generate': 'Create Relay insight',
    'dashboard.viralInsight.generating': 'Building insight…',
    'dashboard.viralInsight.queued': 'Insight queued ({jobId})',
    'dashboard.viralInsight.notConfirmed': 'Insight enqueue could not be confirmed.',
    'dashboard.viralInsight.retry': 'Insight request could not be confirmed. Check again before retrying.',
    'dashboard.viralInsight.scheduleTitle': 'Automatic weekly insight',
    'dashboard.viralInsight.scheduleDescription': 'Create a Relay insight after each completed week. Delivery uses this model’s enabled Relay destinations.',
    'dashboard.viralInsight.scheduleEnabled': 'Weekly insights are enabled',
    'dashboard.viralInsight.scheduleDisabled': 'Weekly insights are disabled',
    'dashboard.viralInsight.scheduleSave': 'Save schedule',
    'dashboard.viralInsight.scheduleSaving': 'Saving schedule…',
    'dashboard.viralInsight.scheduleSaved': 'Schedule saved.',
    'dashboard.viralInsight.scheduleNotConfirmed': 'The schedule change could not be confirmed.',
    'dashboard.viralInsight.scheduleRetry': 'The schedule change is unconfirmed. Check its state before retrying.',
    'dashboard.viralInsight.scheduleLoadError': 'Schedule status is unavailable; no change can be made.',
  },
  es: {
    'dashboard.viralInsight.generate': 'Crear insight de Relay',
    'dashboard.viralInsight.generating': 'Creando insight…',
    'dashboard.viralInsight.queued': 'Insight en cola ({jobId})',
    'dashboard.viralInsight.notConfirmed': 'No se pudo confirmar la cola del insight.',
    'dashboard.viralInsight.retry': 'No se pudo confirmar la solicitud. Comprueba el estado antes de reintentar.',
    'dashboard.viralInsight.scheduleTitle': 'Insight semanal automático',
    'dashboard.viralInsight.scheduleDescription': 'Crea un insight de Relay después de cada semana completa. La entrega usa los destinos de Relay habilitados para este modelo.',
    'dashboard.viralInsight.scheduleEnabled': 'Los insights semanales están activados',
    'dashboard.viralInsight.scheduleDisabled': 'Los insights semanales están desactivados',
    'dashboard.viralInsight.scheduleSave': 'Guardar programación',
    'dashboard.viralInsight.scheduleSaving': 'Guardando programación…',
    'dashboard.viralInsight.scheduleSaved': 'Programación guardada.',
    'dashboard.viralInsight.scheduleNotConfirmed': 'No se pudo confirmar el cambio de programación.',
    'dashboard.viralInsight.scheduleRetry': 'El cambio no está confirmado. Comprueba el estado antes de volver a intentarlo.',
    'dashboard.viralInsight.scheduleLoadError': 'El estado no está disponible; no se puede cambiar la programación.',
  },
  ja: {
    'dashboard.viralInsight.generate': 'Relayインサイトを作成',
    'dashboard.viralInsight.generating': 'インサイトを作成中…',
    'dashboard.viralInsight.queued': 'インサイトをキューに追加しました（{jobId}）',
    'dashboard.viralInsight.notConfirmed': 'インサイトのキュー投入を確認できませんでした。',
    'dashboard.viralInsight.retry': 'リクエストを確認できません。再試行前に状態を確認してください。',
    'dashboard.viralInsight.scheduleTitle': '週次インサイトの自動作成',
    'dashboard.viralInsight.scheduleDescription': '完了した週ごとにRelayインサイトを作成します。このモデルで有効なRelay送信先に配信されます。',
    'dashboard.viralInsight.scheduleEnabled': '週次インサイトは有効です',
    'dashboard.viralInsight.scheduleDisabled': '週次インサイトは無効です',
    'dashboard.viralInsight.scheduleSave': 'スケジュールを保存',
    'dashboard.viralInsight.scheduleSaving': 'スケジュールを保存中…',
    'dashboard.viralInsight.scheduleSaved': 'スケジュールを保存しました。',
    'dashboard.viralInsight.scheduleNotConfirmed': 'スケジュール変更を確認できませんでした。',
    'dashboard.viralInsight.scheduleRetry': '変更は未確認です。再試行する前に状態を確認してください。',
    'dashboard.viralInsight.scheduleLoadError': '状態を取得できないため、変更はできません。',
  },
  it: {
    'dashboard.viralInsight.generate': 'Crea insight Relay',
    'dashboard.viralInsight.generating': 'Creazione insight…',
    'dashboard.viralInsight.queued': 'Insight in coda ({jobId})',
    'dashboard.viralInsight.notConfirmed': 'Non è stato possibile confermare la coda dell’insight.',
    'dashboard.viralInsight.retry': 'La richiesta non è stata confermata. Controlla lo stato prima di riprovare.',
    'dashboard.viralInsight.scheduleTitle': 'Insight settimanale automatico',
    'dashboard.viralInsight.scheduleDescription': 'Crea un insight Relay dopo ogni settimana completa. La consegna usa le destinazioni Relay abilitate per questo modello.',
    'dashboard.viralInsight.scheduleEnabled': 'Gli insight settimanali sono attivi',
    'dashboard.viralInsight.scheduleDisabled': 'Gli insight settimanali sono disattivati',
    'dashboard.viralInsight.scheduleSave': 'Salva pianificazione',
    'dashboard.viralInsight.scheduleSaving': 'Salvataggio pianificazione…',
    'dashboard.viralInsight.scheduleSaved': 'Pianificazione salvata.',
    'dashboard.viralInsight.scheduleNotConfirmed': 'Impossibile confermare la modifica della pianificazione.',
    'dashboard.viralInsight.scheduleRetry': 'La modifica non è confermata. Controlla lo stato prima di riprovare.',
    'dashboard.viralInsight.scheduleLoadError': 'Stato non disponibile; impossibile modificare la pianificazione.',
  },
  'pt-BR': {
    'dashboard.viralInsight.generate': 'Criar insight do Relay',
    'dashboard.viralInsight.generating': 'Criando insight…',
    'dashboard.viralInsight.queued': 'Insight enfileirado ({jobId})',
    'dashboard.viralInsight.notConfirmed': 'Não foi possível confirmar o enfileiramento do insight.',
    'dashboard.viralInsight.retry': 'Não foi possível confirmar a solicitação. Verifique o status antes de tentar novamente.',
    'dashboard.viralInsight.scheduleTitle': 'Insight semanal automático',
    'dashboard.viralInsight.scheduleDescription': 'Cria um insight do Relay após cada semana concluída. A entrega usa os destinos do Relay habilitados para este modelo.',
    'dashboard.viralInsight.scheduleEnabled': 'Insights semanais estão ativados',
    'dashboard.viralInsight.scheduleDisabled': 'Insights semanais estão desativados',
    'dashboard.viralInsight.scheduleSave': 'Salvar programação',
    'dashboard.viralInsight.scheduleSaving': 'Salvando programação…',
    'dashboard.viralInsight.scheduleSaved': 'Programação salva.',
    'dashboard.viralInsight.scheduleNotConfirmed': 'Não foi possível confirmar a alteração da programação.',
    'dashboard.viralInsight.scheduleRetry': 'A alteração não foi confirmada. Verifique o estado antes de tentar novamente.',
    'dashboard.viralInsight.scheduleLoadError': 'O estado não está disponível; não é possível alterar a programação.',
  },
  de: {
    'dashboard.viralInsight.generate': 'Relay-Insight erstellen',
    'dashboard.viralInsight.generating': 'Insight wird erstellt…',
    'dashboard.viralInsight.queued': 'Insight eingereiht ({jobId})',
    'dashboard.viralInsight.notConfirmed': 'Das Einreihen des Insights konnte nicht bestätigt werden.',
    'dashboard.viralInsight.retry': 'Die Anfrage konnte nicht bestätigt werden. Prüfe den Status vor einem neuen Versuch.',
    'dashboard.viralInsight.scheduleTitle': 'Automatischer wöchentlicher Insight',
    'dashboard.viralInsight.scheduleDescription': 'Erstellt nach jeder abgeschlossenen Woche einen Relay-Insight. Die Zustellung nutzt die aktivierten Relay-Ziele dieses Modells.',
    'dashboard.viralInsight.scheduleEnabled': 'Wöchentliche Insights sind aktiviert',
    'dashboard.viralInsight.scheduleDisabled': 'Wöchentliche Insights sind deaktiviert',
    'dashboard.viralInsight.scheduleSave': 'Zeitplan speichern',
    'dashboard.viralInsight.scheduleSaving': 'Zeitplan wird gespeichert…',
    'dashboard.viralInsight.scheduleSaved': 'Zeitplan gespeichert.',
    'dashboard.viralInsight.scheduleNotConfirmed': 'Die Zeitplanänderung konnte nicht bestätigt werden.',
    'dashboard.viralInsight.scheduleRetry': 'Die Änderung ist unbestätigt. Prüfe den Status vor einem erneuten Versuch.',
    'dashboard.viralInsight.scheduleLoadError': 'Der Status ist nicht verfügbar; der Zeitplan kann nicht geändert werden.',
  },
};
