import type { Catalog, SupportedLocale } from './locale.js';

/**
 * Labels for the model-scoped dynamic watermark controls. The controls
 * describe the watermark composited onto media variants in this model's own
 * workspace. They never promise a CDN or publication action.
 */
export const WATERMARK_POLICY_CATALOGS: Record<SupportedLocale, Catalog> = {
  en: {
    'dashboard.watermark.title': 'Watermark',
    'dashboard.watermark.intro': 'Choose the watermark composited onto this model’s media variants. Unsupported settings fail closed before a transform runs.',
    'dashboard.watermark.enabled': 'Apply watermark',
    'dashboard.watermark.position': 'Position',
    'dashboard.watermark.position.top-left': 'Top left',
    'dashboard.watermark.position.top-right': 'Top right',
    'dashboard.watermark.position.bottom-left': 'Bottom left',
    'dashboard.watermark.position.bottom-right': 'Bottom right',
    'dashboard.watermark.position.center': 'Centre',
    'dashboard.watermark.opacity': 'Opacity (%)',
    'dashboard.watermark.scale': 'Scale (%)',
    'dashboard.watermark.watermarkKey': 'Watermark asset key',
    'dashboard.watermark.keyHint': 'Object key of an asset already stored for this model.',
    'dashboard.watermark.save': 'Save watermark',
    'dashboard.watermark.saving': 'Saving…',
    'dashboard.watermark.saved': 'Watermark policy saved.',
    'dashboard.watermark.notConfirmed': 'The change could not be confirmed. Reload before retrying.',
    'dashboard.watermark.unavailable': 'Watermark controls are unavailable for this account.',
    'dashboard.watermark.readOnly': 'You can view these controls but cannot change them.',
    'dashboard.watermark.invalidKey': 'The watermark asset key contains a character that is not allowed.',
    'dashboard.watermark.disabledNote': 'Disabled means no watermark is composited.',
    'dashboard.watermark.empty': 'No watermark is configured for this model yet.',
    'dashboard.watermark.bounds.opacity': 'Opacity must be a whole number from 0 to 100.',
    'dashboard.watermark.bounds.scale': 'Scale must be a whole number from 5 to 100.',
  },
  es: {
    'dashboard.watermark.title': 'Marca de agua',
    'dashboard.watermark.intro': 'Elige la marca de agua que se compone en las variantes multimedia de este modelo. Los ajustes no compatibles fallan de forma segura antes de ejecutar una transformación.',
    'dashboard.watermark.enabled': 'Aplicar marca de agua',
    'dashboard.watermark.position': 'Posición',
    'dashboard.watermark.position.top-left': 'Arriba a la izquierda',
    'dashboard.watermark.position.top-right': 'Arriba a la derecha',
    'dashboard.watermark.position.bottom-left': 'Abajo a la izquierda',
    'dashboard.watermark.position.bottom-right': 'Abajo a la derecha',
    'dashboard.watermark.position.center': 'Centro',
    'dashboard.watermark.opacity': 'Opacidad (%)',
    'dashboard.watermark.scale': 'Escala (%)',
    'dashboard.watermark.watermarkKey': 'Clave del recurso de marca de agua',
    'dashboard.watermark.keyHint': 'Clave de objeto de un recurso ya almacenado para este modelo.',
    'dashboard.watermark.save': 'Guardar marca de agua',
    'dashboard.watermark.saving': 'Guardando…',
    'dashboard.watermark.saved': 'Política de marca de agua guardada.',
    'dashboard.watermark.notConfirmed': 'No se pudo confirmar el cambio. Recarga antes de volver a intentarlo.',
    'dashboard.watermark.unavailable': 'Los controles de marca de agua no están disponibles para esta cuenta.',
    'dashboard.watermark.readOnly': 'Puedes ver estos controles, pero no modificarlos.',
    'dashboard.watermark.invalidKey': 'La clave del recurso de marca de agua contiene un carácter no permitido.',
    'dashboard.watermark.disabledNote': 'Desactivado significa que no se compone ninguna marca de agua.',
    'dashboard.watermark.empty': 'Todavía no hay ninguna marca de agua configurada para este modelo.',
    'dashboard.watermark.bounds.opacity': 'La opacidad debe ser un número entero de 0 a 100.',
    'dashboard.watermark.bounds.scale': 'La escala debe ser un número entero de 5 a 100.',
  },
  ja: {
    'dashboard.watermark.title': 'ウォーターマーク',
    'dashboard.watermark.intro': 'このモデルのメディアバリアントに合成するウォーターマークを選択します。未対応の設定は変換の実行前に安全に停止します。',
    'dashboard.watermark.enabled': 'ウォーターマークを適用',
    'dashboard.watermark.position': '位置',
    'dashboard.watermark.position.top-left': '左上',
    'dashboard.watermark.position.top-right': '右上',
    'dashboard.watermark.position.bottom-left': '左下',
    'dashboard.watermark.position.bottom-right': '右下',
    'dashboard.watermark.position.center': '中央',
    'dashboard.watermark.opacity': '不透明度（%）',
    'dashboard.watermark.scale': '拡大率（%）',
    'dashboard.watermark.watermarkKey': 'ウォーターマーク素材キー',
    'dashboard.watermark.keyHint': 'このモデルに保存済みの素材のオブジェクトキー。',
    'dashboard.watermark.save': 'ウォーターマークを保存',
    'dashboard.watermark.saving': '保存中…',
    'dashboard.watermark.saved': 'ウォーターマークポリシーを保存しました。',
    'dashboard.watermark.notConfirmed': '変更を確認できませんでした。再読み込みしてから再試行してください。',
    'dashboard.watermark.unavailable': 'このアカウントではウォーターマーク設定を利用できません。',
    'dashboard.watermark.readOnly': '設定は表示できますが変更できません。',
    'dashboard.watermark.invalidKey': 'ウォーターマーク素材キーに使用できない文字が含まれています。',
    'dashboard.watermark.disabledNote': '無効の場合、ウォーターマークは合成されません。',
    'dashboard.watermark.empty': 'このモデルにはまだウォーターマークが設定されていません。',
    'dashboard.watermark.bounds.opacity': '不透明度は0から100までの整数で指定してください。',
    'dashboard.watermark.bounds.scale': '拡大率は5から100までの整数で指定してください。',
  },
  it: {
    'dashboard.watermark.title': 'Filigrana',
    'dashboard.watermark.intro': 'Scegli la filigrana composta sulle varianti multimediali di questo modello. Le impostazioni non supportate si bloccano in sicurezza prima di eseguire una trasformazione.',
    'dashboard.watermark.enabled': 'Applica filigrana',
    'dashboard.watermark.position': 'Posizione',
    'dashboard.watermark.position.top-left': 'In alto a sinistra',
    'dashboard.watermark.position.top-right': 'In alto a destra',
    'dashboard.watermark.position.bottom-left': 'In basso a sinistra',
    'dashboard.watermark.position.bottom-right': 'In basso a destra',
    'dashboard.watermark.position.center': 'Centro',
    'dashboard.watermark.opacity': 'Opacità (%)',
    'dashboard.watermark.scale': 'Scala (%)',
    'dashboard.watermark.watermarkKey': 'Chiave della risorsa filigrana',
    'dashboard.watermark.keyHint': 'Chiave oggetto di una risorsa già archiviata per questo modello.',
    'dashboard.watermark.save': 'Salva filigrana',
    'dashboard.watermark.saving': 'Salvataggio…',
    'dashboard.watermark.saved': 'Politica filigrana salvata.',
    'dashboard.watermark.notConfirmed': 'Non è stato possibile confermare la modifica. Ricarica prima di riprovare.',
    'dashboard.watermark.unavailable': 'I controlli filigrana non sono disponibili per questo account.',
    'dashboard.watermark.readOnly': 'Puoi visualizzare questi controlli ma non modificarli.',
    'dashboard.watermark.invalidKey': 'La chiave della risorsa filigrana contiene un carattere non consentito.',
    'dashboard.watermark.disabledNote': 'Disabilitato significa che nessuna filigrana viene composta.',
    'dashboard.watermark.empty': 'Nessuna filigrana è ancora configurata per questo modello.',
    'dashboard.watermark.bounds.opacity': 'L’opacità deve essere un numero intero da 0 a 100.',
    'dashboard.watermark.bounds.scale': 'La scala deve essere un numero intero da 5 a 100.',
  },
  'pt-BR': {
    'dashboard.watermark.title': 'Marca d’água',
    'dashboard.watermark.intro': 'Escolha a marca d’água composta nas variantes de mídia deste modelo. Configurações incompatíveis falham com segurança antes de executar uma transformação.',
    'dashboard.watermark.enabled': 'Aplicar marca d’água',
    'dashboard.watermark.position': 'Posição',
    'dashboard.watermark.position.top-left': 'Canto superior esquerdo',
    'dashboard.watermark.position.top-right': 'Canto superior direito',
    'dashboard.watermark.position.bottom-left': 'Canto inferior esquerdo',
    'dashboard.watermark.position.bottom-right': 'Canto inferior direito',
    'dashboard.watermark.position.center': 'Centro',
    'dashboard.watermark.opacity': 'Opacidade (%)',
    'dashboard.watermark.scale': 'Escala (%)',
    'dashboard.watermark.watermarkKey': 'Chave do recurso de marca d’água',
    'dashboard.watermark.keyHint': 'Chave de objeto de um recurso já armazenado para este modelo.',
    'dashboard.watermark.save': 'Salvar marca d’água',
    'dashboard.watermark.saving': 'Salvando…',
    'dashboard.watermark.saved': 'Política de marca d’água salva.',
    'dashboard.watermark.notConfirmed': 'Não foi possível confirmar a alteração. Recarregue antes de tentar novamente.',
    'dashboard.watermark.unavailable': 'Os controles de marca d’água não estão disponíveis para esta conta.',
    'dashboard.watermark.readOnly': 'Você pode visualizar estes controles, mas não alterá-los.',
    'dashboard.watermark.invalidKey': 'A chave do recurso de marca d’água contém um caractere não permitido.',
    'dashboard.watermark.disabledNote': 'Desativado significa que nenhuma marca d’água é composta.',
    'dashboard.watermark.empty': 'Nenhuma marca d’água está configurada para este modelo ainda.',
    'dashboard.watermark.bounds.opacity': 'A opacidade deve ser um número inteiro de 0 a 100.',
    'dashboard.watermark.bounds.scale': 'A escala deve ser um número inteiro de 5 a 100.',
  },
  de: {
    'dashboard.watermark.title': 'Wasserzeichen',
    'dashboard.watermark.intro': 'Wähle das Wasserzeichen, das auf die Medienvarianten dieses Modells gelegt wird. Nicht unterstützte Einstellungen brechen vor einer Transformation sicher ab.',
    'dashboard.watermark.enabled': 'Wasserzeichen anwenden',
    'dashboard.watermark.position': 'Position',
    'dashboard.watermark.position.top-left': 'Oben links',
    'dashboard.watermark.position.top-right': 'Oben rechts',
    'dashboard.watermark.position.bottom-left': 'Unten links',
    'dashboard.watermark.position.bottom-right': 'Unten rechts',
    'dashboard.watermark.position.center': 'Mitte',
    'dashboard.watermark.opacity': 'Deckkraft (%)',
    'dashboard.watermark.scale': 'Skalierung (%)',
    'dashboard.watermark.watermarkKey': 'Schlüssel des Wasserzeichen-Assets',
    'dashboard.watermark.keyHint': 'Objektschlüssel eines bereits für dieses Modell gespeicherten Assets.',
    'dashboard.watermark.save': 'Wasserzeichen speichern',
    'dashboard.watermark.saving': 'Speichern…',
    'dashboard.watermark.saved': 'Wasserzeichen-Richtlinie gespeichert.',
    'dashboard.watermark.notConfirmed': 'Die Änderung konnte nicht bestätigt werden. Vor einem erneuten Versuch neu laden.',
    'dashboard.watermark.unavailable': 'Die Wasserzeichen-Steuerung ist für dieses Konto nicht verfügbar.',
    'dashboard.watermark.readOnly': 'Du kannst diese Steuerung ansehen, aber nicht ändern.',
    'dashboard.watermark.invalidKey': 'Der Schlüssel des Wasserzeichen-Assets enthält ein nicht erlaubtes Zeichen.',
    'dashboard.watermark.disabledNote': 'Deaktiviert bedeutet, dass kein Wasserzeichen gelegt wird.',
    'dashboard.watermark.empty': 'Für dieses Modell ist noch kein Wasserzeichen konfiguriert.',
    'dashboard.watermark.bounds.opacity': 'Die Deckkraft muss eine ganze Zahl von 0 bis 100 sein.',
    'dashboard.watermark.bounds.scale': 'Die Skalierung muss eine ganze Zahl von 5 bis 100 sein.',
  },
};
