import Link from 'next/link';
import { api, getSession } from '@/lib/api';
import GenerateDigestButton from '@/components/GenerateDigestButton';
import DigestScheduleStatus from '@/components/DigestScheduleStatus';
export const dynamic = 'force-dynamic';
export default async function DigestsPage({ searchParams }: { searchParams?: Promise<Record<string, string | string[] | undefined>> }) {
  const session = await getSession(); const canGenerate = ['owner', 'manager', 'operator'].includes(session?.user?.role ?? ''); const query = await searchParams;
  const cursor = typeof query?.cursor === 'string' ? query.cursor : undefined;
  let result: Awaited<ReturnType<typeof api.digests.list>> | undefined;
  try { result = await api.digests.list(cursor); } catch { /* Render a distinct unavailable state. */ }
  return <div className="page-stack"><div className="row" style={{ justifyContent: 'space-between' }}><h1>Weekly digests</h1><Link href="/audit">View audit trail</Link></div>
    <p>Durable workspace summaries generated by the existing digest worker. Queueing a digest does not publish content.</p>
    <DigestScheduleStatus schedule={result?.schedule} canConfigure={session?.user?.role === 'owner'} />
    {canGenerate && <GenerateDigestButton />}
    {!canGenerate && <p className="subtle">Digest generation requires an owner, manager or operator role.</p>}
    {!result ? <p role="alert">Digests could not be loaded. Refresh to try again.</p> : result.data.length === 0 ? <p>No digest cards yet.</p> : <div className="grid">{result.data.map(card => <article className="card stack" key={card.id}><div className="row" style={{ justifyContent: 'space-between' }}><h2>{card.title || 'Weekly digest'}</h2><span className="badge mute">{card.externalDelivery === 'not-attempted' ? 'Stored only' : card.externalDelivery === 'attempted' ? 'Dispatch attempted' : 'Outcome unknown'}</span></div><p style={{ whiteSpace: 'pre-wrap' }}>{card.description || 'No summary text recorded.'}</p><p className="subtle">Created {card.createdAt}</p></article>)}</div>}
    <nav className="action-row" aria-label="Digest pages">{cursor && <Link href="/digests">Latest digests</Link>}{result?.meta?.next_cursor && <Link href={`/digests?${new URLSearchParams({ cursor: result.meta.next_cursor })}`}>Older digests</Link>}</nav>
  </div>;
}
