// --- Types ---
export interface BundleContent {
  id: string;
  /** Persistent relay_card id used to bind action callbacks to one card. */
  cardId?: string;
  mediaUrls: string[];
  caption: string;
  captionVariants: Record<string, string>;
  hashtagSets: Record<string, string[]>;
  tosScores: Record<string, number>;
  targetPlatforms: string[];
  price?: number;
  scheduleAt?: string;
  promptInputs?: Record<string, unknown>;
  /** Authenticated provider button payloads, generated by the worker. */
  commandTokens?: Partial<Record<CardAction, string>>;
}

export interface PlatformVerdict {
  platform: string;
  passed: boolean;
  score: number;
  reason: string;
}

export type CardAction =
  | 'approve'
  | 'approve_all'
  | 'reject'
  | 'edit_caption'
  | 'change_price'
  | 'reschedule'
  | 'regenerate'
  | 'revise'
  | 'hold'
  | 'publish_now';

export interface RelayCard {
  /** Persistent relay_card id; absent only for non-dispatch preview renders. */
  cardId?: string;
  bundleId: string;
  mediaPreview: string;
  caption: string;
  captionVariants: Record<string, string>;
  hashtagSets: Record<string, string[]>;
  verdicts: PlatformVerdict[];
  targetPlatforms: string[];
  price?: number;
  scheduleAt?: string;
  actions: CardAction[];
  /** Authenticated provider button payloads, generated by the worker. */
  commandTokens?: Partial<Record<CardAction, string>>;
  timestamp: number;
  format: 'html' | 'embed' | 'text';
}

// --- CardRenderer ---
export class CardRenderer {
  renderBundleCard(bundle: BundleContent): RelayCard {
    const verdicts: PlatformVerdict[] = bundle.targetPlatforms.map((platform) => ({
      platform,
      passed: (bundle.tosScores[platform] ?? 1) >= 0.7,
      score: bundle.tosScores[platform] ?? 1,
      reason:
        (bundle.tosScores[platform] ?? 1) >= 0.7
          ? 'ToS check passed'
          : 'ToS check failed — score below threshold',
    }));

    const allPassed = verdicts.every((v) => v.passed);

    const actions: CardAction[] = allPassed
      ? [
          'approve',
          'approve_all',
          'edit_caption',
          'reschedule',
          'reject',
          'hold',
          'publish_now',
        ]
      : ['regenerate', 'revise', 'reject', 'hold'];

    return {
      cardId: bundle.cardId,
      bundleId: bundle.id,
      mediaPreview: bundle.mediaUrls[0] ?? '',
      caption: bundle.caption,
      captionVariants: bundle.captionVariants,
      hashtagSets: bundle.hashtagSets,
      verdicts,
      targetPlatforms: bundle.targetPlatforms,
      price: bundle.price,
      scheduleAt: bundle.scheduleAt,
      actions,
      commandTokens: bundle.commandTokens,
      timestamp: Date.now(),
      format: 'html',
    };
  }

  toHtml(card: RelayCard): string {
    const verdictRows = card.verdicts
      .map(
        (v) =>
          `<b>${v.platform}:</b> ${v.passed ? '✅ PASS' : '❌ FAIL'} (${(v.score * 100).toFixed(0)}%)`,
      )
      .join('\n');
    const hashtagRows = Object.entries(card.hashtagSets)
      .map(([p, tags]) => `<b>${p}:</b> ${tags.slice(0, 5).join(' ')}`)
      .join('\n');
    return [
      `<b>📦 Bundle: ${card.bundleId}</b>`,
      '',
      card.mediaPreview ? `<b>Preview:</b> ${card.mediaPreview}` : '',
      `<b>Caption:</b> ${card.caption.slice(0, 200)}`,
      '',
      `<b>ToS Verdicts:</b>`,
      verdictRows,
      '',
      `<b>Hashtags:</b>`,
      hashtagRows,
      '',
      card.price ? `<b>Price:</b> $${card.price}` : '',
      card.scheduleAt ? `<b>Scheduled:</b> ${card.scheduleAt}` : '',
    ]
      .filter(Boolean)
      .join('\n');
  }

  toEmbed(card: RelayCard): Record<string, unknown> {
    return {
      title: `📦 Bundle: ${card.bundleId.slice(0, 8)}`,
      description: card.caption.slice(0, 400),
      color: card.verdicts.every((v) => v.passed) ? 0x00ff00 : 0xff0000,
      ...(card.mediaPreview ? { image: { url: card.mediaPreview } } : {}),
      fields: [
        {
          name: 'ToS Verdicts',
          value: card.verdicts
            .map((v) => `${v.platform}: ${v.passed ? '✅' : '❌'} (${(v.score * 100).toFixed(0)}%)`)
            .join('\n'),
          inline: false,
        },
        {
          name: 'Target Platforms',
          value: card.targetPlatforms.join(', '),
          inline: true,
        },
        ...(card.price ? [{ name: 'Price', value: `$${card.price}`, inline: true }] : []),
        ...(card.scheduleAt ? [{ name: 'Scheduled', value: card.scheduleAt, inline: true }] : []),
      ],
      timestamp: new Date(card.timestamp).toISOString(),
    };
  }

  toText(card: RelayCard): string {
    const lines: string[] = [
      `📦 Bundle: ${card.bundleId}`,
      ...(card.mediaPreview ? [`Preview: ${card.mediaPreview}`] : []),
      `Caption: ${card.caption.slice(0, 200)}`,
      '',
      'ToS Verdicts:',
      ...card.verdicts.map(
        (v) => `  ${v.platform}: ${v.passed ? 'PASS' : 'FAIL'} (${(v.score * 100).toFixed(0)}%)`,
      ),
      '',
      'Actions (reply with keyword):',
      ...card.actions.map((action) => `  ${actionKeyword(action)}`),
    ];
    return lines.join('\n');
  }
}

function actionKeyword(action: CardAction): string {
  switch (action) {
    case 'edit_caption':
      return 'edit <new caption>';
    case 'reschedule':
      return 'schedule <future ISO-8601 timestamp>';
    default:
      return action;
  }
}
