// --- Types ---
export interface BundleContent {
  id: string;
  /** Persistent relay_card id used to bind action callbacks to one card. */
  cardId?: string;
  mediaUrls: string[];
  caption: string;
  captionVariants: Record<string, string>;
  hashtagSets: Record<string, string[]>;
  tosScores: Record<string, number>;
  targetPlatforms: string[];
  price?: number;
  scheduleAt?: string;
  promptInputs?: Record<string, unknown>;
  /** Authenticated provider button payloads, generated by the worker. */
  commandTokens?: Partial<Record<CardAction, string>>;
}

export interface InsightGroup {
  platform: string;
  learningArm: string;
  learningContext: string;
  sampleSize: number;
  meanScore: number;
  publishedHourUtc?: number | null;
}

export interface InsightContent {
  id: string;
  cardId?: string;
  title: string;
  description: string;
  groups: readonly InsightGroup[];
  icon?: string;
}

export interface PlatformVerdict {
  platform: string;
  passed: boolean;
  score: number;
  reason: string;
}

export type CardAction =
  | 'approve'
  | 'approve_all'
  | 'reject'
  | 'edit_caption'
  | 'change_price'
  | 'reschedule'
  | 'regenerate'
  | 'revise'
  | 'hold'
  | 'publish_now';

export interface RelayCard {
  /** Persistent relay_card id; absent only for non-dispatch preview renders. */
  cardId?: string;
  /** Insight cards use the same channel adapters but have no bundle lifecycle. */
  kind?: 'bundle' | 'insight';
  bundleId: string;
  mediaPreview: string;
  caption: string;
  captionVariants: Record<string, string>;
  hashtagSets: Record<string, string[]>;
  verdicts: PlatformVerdict[];
  targetPlatforms: string[];
  price?: number;
  scheduleAt?: string;
  actions: CardAction[];
  /** Authenticated provider button payloads, generated by the worker. */
  commandTokens?: Partial<Record<CardAction, string>>;
  timestamp: number;
  format: 'html' | 'embed' | 'text';
  insight?: {
    title: string;
    description: string;
    icon?: string;
    groups: readonly InsightGroup[];
  };
}

// --- CardRenderer ---
export class CardRenderer {
  renderBundleCard(bundle: BundleContent): RelayCard {
    const verdicts: PlatformVerdict[] = bundle.targetPlatforms.map((platform) => {
      const rawScore = bundle.tosScores[platform];
      const hasScore = typeof rawScore === 'number' && Number.isFinite(rawScore);
      const score = hasScore ? Math.max(0, Math.min(1, rawScore)) : 0;
      const passed = hasScore && score >= 0.7;
      return {
        platform,
        passed,
        score,
        reason: !hasScore
          ? 'ToS check unavailable â€” review required'
          : passed
            ? 'ToS check passed'
            : 'ToS check failed â€” score below threshold',
      };
    });

    const allPassed = verdicts.every((v) => v.passed);

    const actions: CardAction[] = allPassed
      ? ['approve', 'approve_all', 'edit_c×¶¶‰ËkºwµçEÑ¥½¹Ì€¡É•Á±äİ¥Ñ Ñ¡”…Ñ¥½¸…¹¥ÑÌÍ¥¹•Ñ½­•¸¤èœ4(€€€€€€€€è€Ñ¥½¹Ì€¡É•Á±äİ¥Ñ ­•åİ½É¤èœ°4(€€€€€€¸¸¹…É¹…Ñ¥½¹Ì¹µ…À ¡…Ñ¥½¸¤€ôø€€€‘í…Ñ¥½¹-•åİ½É¡…Ñ¥½¸°…É¹½µµ…¹‘Q½­•¹Ìü¹m…Ñ¥½¹t¥õ€¤°4(€€€tì4(€€€É•ÑÕÉ¸±¥¹•Ì¹©½¥¸ q¸œ¤ì4(€ô4(4(€ÁÉ¥Ù…Ñ”Ñ½%¹Í¥¡Ñ!Ñµ°¡…ÉèI•±…å…É¤èÍÑÉ¥¹œì4(€€€½¹ÍĞ¥¹Í¥¡Ğ€ô…É¹¥¹Í¥¡Ğì4(€€€¥˜€ …¥¹Í¥¡Ğ¤Ñ¡É½Ü¹•ÜÉÉ½È ¥¹Í¥¡ĞÉ•±…ä…Éµ¥ÍÍ¥¹œ¥¹Í¥¡ĞÁ…å±½…œ¤ì4(€€€½¹ÍĞÉ½ÕÁÌ€ô¥¹Í¥¡Ğ¹É½ÕÁÌ¹µ…À¡É½ÕÀ€ôøì4(€€€€€½¹ÍĞ¡½ÕÈ€ôÉ½ÕÀ¹ÁÕ‰±¥Í¡•‘!½ÕÉUÑŒ€ôô¹Õ±°€ü€œœ€è€ƒ
Ü€‘íÉ½ÕÀ¹ÁÕ‰±¥Í¡•‘!½ÕÉUÑôèÀÀUQ€ì4(€€€€€É•ÑÕÉ¸€ñˆø‘í•Í…Á•!Ñµ°¡É½ÕÀ¹Á±…Ñ™½É´¥ôğ½ˆøƒ
Ü€‘í•Í…Á•!Ñµ°¡É½ÕÀ¹±•…É¹¥¹É´¥ôƒ
Ü¸ô‘íÉ½ÕÀ¹Í…µÁ±•M¥é•ôƒ
Üµ•…¸€‘íÉ½ÕÀ¹µ•…¹M½É”¹Ñ½¥á• È¥ô‘í¡½ÕÉõ€ì4(€€€ô¤ì4(€€€É•ÑÕÉ¸l4(€€€€€€ñˆø‘í•Í…Á•!Ñµ°¡¥¹Í¥¡Ğ¹¥½¸€üü€ŸÂ~N œ¥ô€‘í•Í…Á•!Ñµ°¡¥¹Í¥¡Ğ¹Ñ¥Ñ±”¥ôğ½ˆù€°4(€€€€€€œœ°4(€€€€€•Í…Á•!Ñµ°¡¥¹Í¥¡Ğ¹‘•ÍÉ¥ÁÑ¥½¸¤°4(€€€€€É½ÕÁÌ¹±•¹Ñ €ø€À€ü€œœ€èÕ¹‘•™¥¹•°4(€€€€€É½ÕÁÌ¹±•¹Ñ €ø€À€ü€œñˆùÙ¥‘•¹”èğ½ˆøœ€èÕ¹‘•™¥¹•°4(€€€€€€¸¸¹É½ÕÁÌ°4(€€€t¹™¥±Ñ•È ¡Ù…±Õ”¤èÙ…±Õ”¥ÌÍÑÉ¥¹œ€ôøÙ…±Õ”€„ôôÕ¹‘•™¥¹•¤¹©½¥¸ q¸œ¤ì4(€ô4(4(€ÁÉ¥Ù…Ñ”Ñ½%¹Í¥¡Ñµ‰•¡…ÉèI•±…å…É¤èI•½ÉñÍÑÉ¥¹œ°Õ¹­¹½İ¸øì4(€€€½¹ÍĞ¥¹Í¥¡Ğ€ô…É¹¥¹Í¥¡Ğì4(€€€¥˜€ …¥¹Í¥¡Ğ¤Ñ¡É½Ü¹•ÜÉÉ½È ¥¹Í¥¡ĞÉ•±…ä…Éµ¥ÍÍ¥¹œ¥¹Í¥¡ĞÁ…å±½…œ¤ì4(€€€É•ÑÕÉ¸ì4(€€€€€Ñ¥Ñ±”è€‘í¥¹Í¥¡Ğ¹¥½¸€üü€ŸÂ~N ô€‘í¥¹Í¥¡Ğ¹Ñ¥Ñ±•õ€¹Í±¥” À°€ÈÔØ¤°4(€€€€€‘•ÍÉ¥ÁÑ¥½¸è¥¹Í¥¡Ğ¹‘•ÍÉ¥ÁÑ¥½¸¹Í±¥” À°€ĞÀÀÀ¤°4(€€€€€½±½Èè€ÁàÑ˜ĞÙ”Ô°4(€€€€€™¥•±‘Ìè¥¹Í¥¡Ğ¹É½ÕÁÌ¹Í±¥” À°€ÄÀ¤¹µ…À¡É½ÕÀ€ôø€¡ì4(€€€€€€€¹…µ”èÉ½ÕÀ¹Á±…Ñ™½É´°4(€€€€€€€Ù…±Õ”è€‘íÉ½ÕÀ¹±•…É¹¥¹Éµôƒ
Ü¸ô‘íÉ½ÕÀ¹Í…µÁ±•M¥é•ôƒ
Üµ•…¸€‘íÉ½ÕÀ¹µ•…¹M½É”¹Ñ½¥á• È¥ô‘íÉ½ÕÀ¹ÁÕ‰±¥Í¡•‘!½ÕÉUÑŒ€ôô¹Õ±°€ü€œœ€è€ƒ
Ü€‘íÉ½ÕÀ¹ÁÕ‰±¥Í¡•‘!½ÕÉUÑôèÀÀUQõ€°4(€€€€€€€¥¹±¥¹”è™…±Í”°4(€€€€€ô¤¤°4(€€€€€Ñ¥µ•ÍÑ…µÀè¹•Ü…Ñ”¡…É¹Ñ¥µ•ÍÑ…µÀ¤¹Ñ½%M=MÑÉ¥¹œ ¤°4(€€€ôì4(€ô4(4(€ÁÉ¥Ù…Ñ”Ñ½%¹Í¥¡ÑQ•áĞ¡…ÉèI•±…å…É¤èÍÑÉ¥¹œì4(€€€½¹ÍĞ¥¹Í¥¡Ğ€ô…É¹¥¹Í¥¡Ğì4(€€€¥˜€ …¥¹Í¥¡Ğ¤Ñ¡É½Ü¹•ÜÉÉ½È ¥¹Í¥¡ĞÉ•±…ä…Éµ¥ÍÍ¥¹œ¥¹Í¥¡ĞÁ…å±½…œ¤ì4(€€€É•ÑÕÉ¸l4(€€€€€€‘í¥¹Í¥¡Ğ¹¥½¸€üü€ŸÂ~N ô€‘í¥¹Í¥¡Ğ¹Ñ¥Ñ±•õ€°4(€€€€€€œœ°4(€€€€€¥¹Í¥¡Ğ¹‘•ÍÉ¥ÁÑ¥½¸°4(€€€€€€¸¸¹¥¹Í¥¡Ğ¹É½ÕÁÌ¹µ…À¡É½ÕÀ€ôø4(€€€€€€€€€€‘íÉ½ÕÀ¹Á±…Ñ™½Éµôƒ
Ü€‘íÉ½ÕÀ¹±•…É¹¥¹Éµôƒ
Ü¸ô‘íÉ½ÕÀ¹Í…µÁ±•M¥é•ôƒ
Üµ•…¸€‘íÉ½ÕÀ¹µ•…¹M½É”¹Ñ½¥á• È¥ô‘íÉ½ÕÀ¹ÁÕ‰±¥Í¡•‘!½ÕÉUÑŒ€ôô¹Õ±°€ü€œœ€è€ƒ
Ü€‘íÉ½ÕÀ¹ÁÕ‰±¥Í¡•‘!½ÕÉUÑôèÀÀUQõ€°4(€€€€€€¤°4(€€€t¹©½¥¸ q¸œ¤ì4(€ô4)ô4(4)™Õ¹Ñ¥½¸•Í…Á•!Ñµ°¡Ù…±Õ”èÍÑÉ¥¹œ¤èÍÑÉ¥¹œì4(€É•ÑÕÉ¸Ù…±Õ”¹É•Á±…” ½l˜ğø‰t½œ°¡…É…Ñ•È€ôø€¡ì(€€€€œ˜œè€œ™…µÀìœ°4(€€€€œğœè€œ™±Ğìœ°4(€€€€œøœè€œ™Ğìœ°4(€€€€œˆœè€œ™ÅÕ½Ğìœ°4(€õm¡…É…Ñ•Ét€üü¡…É…Ñ•È¤¤ì4)ô4(4)™Õ¹Ñ¥½¸…Ñ¥½¹-•åİ½É¡…Ñ¥½¸è…É‘Ñ¥½¸°Ñ½­•¸üèÍÑÉ¥¹œ¤èÍÑÉ¥¹œì4(€Íİ¥Ñ €¡…Ñ¥½¸¤ì4(€€€…Í”€•‘¥Ñ}…ÁÑ¥½¸œè4(€€€€€É•ÑÕÉ¸Ñ½­•¸€ü•‘¥Ğ€‘íÑ½­•¹ô€ñ¹•Ü…ÁÑ¥½¸ù€€è€•‘¥Ğ€ñ¹•Ü…ÁÑ¥½¸øœì4(€€€…Í”€É•Í¡•‘Õ±”œè4(€€€€€É•ÑÕÉ¸Ñ½­•¸4(€€€€€€€€üÍ¡•‘Õ±”€‘íÑ½­•¹ô€ñ™ÕÑÕÉ”%M<´àØÀÄÑ¥µ•ÍÑ…µÀù€4(€€€€€€€€è€Í¡•‘Õ±”€ñ™ÕÑÕÉ”%M<´àØÀÄÑ¥µ•ÍÑ…µÀøœì4(€€€‘•™…Õ±Ğè4(€€€€€É•ÑÕÉ¸Ñ½­•¸€ü€‘í…Ñ¥½¹ô€‘íÑ½­•¹õ€€è…Ñ¥½¸ì4(€ô4)ô4(